// TODO: Implement this for protobuf
pub enum GDELTLanguage {
    Afrikaans(&'static str),
    Albanian(&'static str),
    Armenian(&'static str),
    Arabic(&'static str),
    Azerbaijani(&'static str),
    Bengali(&'static str),
    Bosnian(&'static str),
    Bulgarian(&'static str),
    Catalan(&'static str),
    Chinese(&'static str),
    Croatian(&'static str),
    Czech(&'static str),
    Danish(&'static str),
    Dutch(&'static str),
    Estonian(&'static str),
    Finnish(&'static str),
    French(&'static str),
    Galician(&'static str),
    Georgian(&'static str),
    German(&'static str),
    Greek(&'static str),
    Gujarati(&'static str),
    Hebrew(&'static str),
    Hindi(&'static str),
    Hungarian(&'static str),
    Icelandic(&'static str),
    Indonesian(&'static str),
    Italian(&'static str),
    Japanese(&'static str),
    Kannada(&'static str),
    Kazakh(&'static str),
    Korean(&'static str),
    Latvian(&'static str),
    Lithuanian(&'static str),
    Macedonian(&'static str),
    Malay(&'static str),
    Malayalam(&'static str),
    Marathi(&'static str),
    Mongolian(&'static str),
    Nepali(&'static str),
    Norwegian(&'static str),
    NorwegianNynorsk(&'static str),
    Persian(&'static str),
    Polish(&'static str),
    Portuguese(&'static str),
    Punjabi(&'static str),
    Romanian(&'static str),
    Russian(&'static str),
    Serbian(&'static str),
    Sinhalese(&'static str),
    Slovak(&'static str),
    Slovenian(&'static str),
    Somali(&'static str),
    Spanish(&'static str),
    Swahili(&'static str),
    Swedish(&'static str),
    Tamil(&'static str),
    Telugu(&'static str),
    Thai(&'static str),
    Tibetan(&'static str),
    Turkish(&'static str),
    Ukrainian(&'static str),
    Urdu(&'static str),
    Vietnamese(&'static str),
}

impl GDELTLanguage {
    pub fn code(&self) -> &'static str {
        match self {
            GDELTLanguage::Afrikaans(code) => code,
            GDELTLanguage::Albanian(code) => code,
            GDELTLanguage::Arabic(code) => code,
            GDELTLanguage::Armenian(code) => code,
            GDELTLanguage::Azerbaijani(code) => code,
            GDELTLanguage::Bengali(code) => code,
            GDELTLanguage::Bosnian(code) => code,
            GDELTLanguage::Bulgarian(code) => code,
            GDELTLanguage::Catalan(code) => code,
            GDELTLanguage::Chinese(code) => code,
            GDELTLanguage::Croatian(code) => code,
            GDELTLanguage::Czech(code) => code,
            GDELTLanguage::Danish(code) => code,
            GDELTLanguage::Dutch(code) => code,
            GDELTLanguage::Estonian(code) => code,
            GDELTLanguage::Finnish(code) => code,
            GDELTLanguage::French(code) => code,
            GDELTLanguage::Galician(code) => code,
            GDELTLanguage::Georgian(code) => code,
            GDELTLanguage::German(code) => code,
            GDELTLanguage::Greek(code) => code,
            GDELTLanguage::Gujarati(code) => code,
            GDELTLanguage::Hebrew(code) => code,
            GDELTLanguage::Hindi(code) => code,
            GDELTLanguage::Hungarian(code) => code,
            GDELTLanguage::Icelandic(code) => code,
            GDELTLanguage::Indonesian(code) => code,
            GDELTLanguage::Italian(code) => code,
            GDELTLanguage::Japanese(code) => code,
            GDELTLanguage::Kannada(code) => code,
            GDELTLanguage::Kazakh(code) => code,
            GDELTLanguage::Korean(code) => code,
            GDELTLanguage::Latvian(code) => code,
            GDELTLanguage::Lithuanian(code) => code,
            GDELTLanguage::Macedonian(code) => code,
            GDELTLanguage::Malay(code) => code,
            GDELTLanguage::Malayalam(code) => code,
            GDELTLanguage::Marathi(code) => code,
            GDELTLanguage::Mongolian(code) => code,
            GDELTLanguage::Nepali(code) => code,
            GDELTLanguage::Norwegian(code) => code,
            GDELTLanguage::NorwegianNynorsk(code) => code,
            GDELTLanguage::Persian(code) => code,
            GDELTLanguage::Polish(code) => code,
            GDELTLanguage::Portuguese(code) => code,
            GDELTLanguage::Punjabi(code) => code,
            GDELTLanguage::Romanian(code) => code,
            GDELTLanguage::Russian(code) => code,
            GDELTLanguage::Serbian(code) => code,
            GDELTLanguage::Sinhalese(code) => code,
            GDELTLanguage::Slovak(code) => code,
            GDELTLanguage::Slovenian(code) => code,
            GDELTLanguage::Somali(code) => code,
            GDELTLanguage::Spanish(code) => code,
            GDELTLanguage::Swahili(code) => code,
            GDELTLanguage::Swedish(code) => code,
            GDELTLanguage::Tamil(code) => code,
            GDELTLanguage::Telugu(code) => code,
            GDELTLanguage::Thai(code) => code,
            GDELTLanguage::Tibetan(code) => code,
            GDELTLanguage::Turkish(code) => code,
            GDELTLanguage::Ukrainian(code) => code,
            GDELTLanguage::Urdu(code) => code,
            GDELTLanguage::Vietnamese(code) => code,
        }
    }
}
