#![feature(repr64)]

use crate::models::gdelt::{CellItem, GDELTObject, ToProto};
use std::cell::RefCell;
use std::fmt::{Display};
use std::str::FromStr;
use strum_macros::{Display, EnumString};
use crate::generated::gdelt_categorylist::GdeltCategoryList;

/// The `GDELTCategoryList` enum represents the list of categories that can be assigned to a GDELT event.
/// Each category is represented by a number, and the enum provides a conversion from `u16` to `GDELTCategoryList`.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, PartialEq, EnumString, Display)]
#[repr(u64)]
pub enum GDELTCategoryList {
    UNKNOWN(RefCell<u64>) = 0,
    AFFECT(RefCell<u64>) = 1,
    AGRICULTURE(RefCell<u64>) = 2,
    ALLIANCE(RefCell<u64>) = 3,
    APPOINTMENT(RefCell<u64>) = 4,
    ARMEDCONFLICT(RefCell<u64>) = 5,
    ARREST(RefCell<u64>) = 6,
    ASSASSINATION(RefCell<u64>) = 7,
    AUSTERITY(RefCell<u64>) = 8,
    AVIATION_INCIDENT(RefCell<u64>) = 9,
    BAN(RefCell<u64>) = 10,
    BLACK_MARKET(RefCell<u64>) = 11,
    BLOCKADE(RefCell<u64>) = 12,
    BORDER(RefCell<u64>) = 13,
    BULLYING(RefCell<u64>) = 14,
    CEASEFIRE(RefCell<u64>) = 15,
    CHARASMATIC_LEADERSHIP(RefCell<u64>) = 16,
    CHECKPOINT(RefCell<u64>) = 17,
    CLAIM_CREDIT(RefCell<u64>) = 18,
    CLOSURE(RefCell<u64>) = 19,
    CONFISCATION(RefCell<u64>) = 20,
    CONSTITUTIONAL(RefCell<u64>) = 21,
    CORRUPTION(RefCell<u64>) = 22,
    CRIME_CARTELS(RefCell<u64>) = 23,
    CRIME_COMMON_ROBBERY(RefCell<u64>) = 24,
    CRIME_ILLEGAL_DRUGS(RefCell<u64>) = 25,
    CURFEW(RefCell<u64>) = 26,
    CYBER_ATTACK(RefCell<u64>) = 27,
    DEATH_PENALTY(RefCell<u64>) = 28,
    DEFECTION(RefCell<u64>) = 29,
    DELAY(RefCell<u64>) = 30,
    DEMOCRACY(RefCell<u64>) = 31,
    DISABILITY(RefCell<u64>) = 32,
    DISCRIMINATION(RefCell<u64>) = 33,
    DISPLACED(RefCell<u64>) = 34,
    DRONE(RefCell<u64>) = 35,
    DRUG_TRADE(RefCell<u64>) = 36,
    ECON_BANKRUPTCY(RefCell<u64>) = 37,
    ECON_BOYCOTT(RefCell<u64>) = 38,
    ECON_COST_OF_LIVING(RefCell<u64>) = 39,
    ECON_CURRENCY_EXCHANGE_RATE(RefCell<u64>) = 40,
    ECON_CURRENCY_RESERVES(RefCell<u64>) = 41,
    ECON_CUTOUTLOOK(RefCell<u64>) = 42,
    ECON_DEBT(RefCell<u64>) = 43,
    ECON_DEREGULATION(RefCell<u64>) = 44,
    ECON_EARNINGSREPORT(RefCell<u64>) = 45,
    ECON_ENTREPRENEURSHIP(RefCell<u64>) = 46,
    ECON_FOREIGNINVEST(RefCell<u64>) = 47,
    ECON_FREETRADE(RefCell<u64>) = 48,
    ECON_HOUSING_PRICES(RefCell<u64>) = 49,
    ECON_INFORMAL_ECONOMY(RefCell<u64>) = 50,
    ECON_INTEREST_RATES(RefCell<u64>) = 51,
    ECON_IPO(RefCell<u64>) = 52,
    ECON_MONOPOLY(RefCell<u64>) = 53,
    ECON_MOU(RefCell<u64>) = 54,
    ECON_NATIONALIZE(RefCell<u64>) = 55,
    ECON_PRICECONTROL(RefCell<u64>) = 56,
    ECON_REMITTANCE(RefCell<u64>) = 57,
    ECON_STOCKMARKET(RefCell<u64>) = 58,
    ECON_SUBSIDIES(RefCell<u64>) = 59,
    ECON_TAXATION(RefCell<u64>) = 60,
    ECON_TRADE_DISPUTE(RefCell<u64>) = 61,
    ECON_UNIONS(RefCell<u64>) = 62,
    EDUCATION(RefCell<u64>) = 63,
    ELECTION(RefCell<u64>) = 64,
    ELECTION_FRAUD(RefCell<u64>) = 65,
    ENV_BIOFUEL(RefCell<u64>) = 66,
    ENV_CARBONCAPTURE(RefCell<u64>) = 67,
    ENV_CLIMATECHANGE(RefCell<u64>) = 68,
    ENV_COAL(RefCell<u64>) = 69,
    ENV_DEFORESTATION(RefCell<u64>) = 70,
    ENV_FISHERY(RefCell<u64>) = 71,
    ENV_FORESTRY(RefCell<u64>) = 72,
    ENV_GEOTHERMAL(RefCell<u64>) = 73,
    ENV_GREEN(RefCell<u64>) = 74,
    ENV_HYDRO(RefCell<u64>) = 75,
    ENV_METALS(RefCell<u64>) = 76,
    ENV_MINING(RefCell<u64>) = 77,
    ENV_NATURALGAS(RefCell<u64>) = 78,
    ENV_NUCLEARPOWER(RefCell<u64>) = 79,
    ENV_OIL(RefCell<u64>) = 80,
    ENV_OVERFISH(RefCell<u64>) = 81,
    ENV_POACHING(RefCell<u64>) = 82,
    ENV_SOLAR(RefCell<u64>) = 83,
    ENV_SPECIESENDANGERED(RefCell<u64>) = 84,
    ENV_SPECIESEXTINCT(RefCell<u64>) = 85,
    ENV_WATERWAYS(RefCell<u64>) = 86,
    ENV_WINDPOWER(RefCell<u64>) = 87,
    ETH_INDIGINOUS(RefCell<u64>) = 88,
    EVACUATION(RefCell<u64>) = 89,
    EXHUMATION(RefCell<u64>) = 90,
    EXILE(RefCell<u64>) = 91,
    EXTREMISM(RefCell<u64>) = 92,
    FIREARM_OWNERSHIP(RefCell<u64>) = 93,
    FOOD_SECURITY(RefCell<u64>) = 94,
    FOOD_STAPLE(RefCell<u64>) = 95,
    FREESPEECH(RefCell<u64>) = 96,
    FUELPRICES(RefCell<u64>) = 97,
    GEN_HOLIDAY(RefCell<u64>) = 98,
    GENDER_VIOLENCE(RefCell<u64>) = 99,
    GENERAL_GOVERNMENT(RefCell<u64>) = 100,
    GENERAL_HEALTH(RefCell<u64>) = 101,
    GENTRIFICATION(RefCell<u64>) = 102,
    GOV_DISSOLVEGOV(RefCell<u64>) = 103,
    GOV_DIVISIONOFPOWER(RefCell<u64>) = 104,
    GOV_INTERGOVERNMENTAL(RefCell<u64>) = 105,
    GOV_REFORM(RefCell<u64>) = 106,
    GOV_REPATRIATION(RefCell<u64>) = 107,
    GRIEVANCES(RefCell<u64>) = 108,
    HARASSMENT(RefCell<u64>) = 109,
    HATE_SPEECH(RefCell<u64>) = 110,
    HEALTH_PANDEMIC(RefCell<u64>) = 111,
    HEALTH_SEXTRANSDISEASE(RefCell<u64>) = 112,
    HEALTH_VACCINATION(RefCell<u64>) = 113,
    HUMAN_TRAFFICKING(RefCell<u64>) = 114,
    IDEOLOGY(RefCell<u64>) = 115,
    IMMIGRATION(RefCell<u64>) = 116,
    IMPEACHMENT(RefCell<u64>) = 117,
    INFO_HOAX(RefCell<u64>) = 118,
    INFO_RUMOR(RefCell<u64>) = 119,
    INFRASTRUCTURE_BAD_ROADS(RefCell<u64>) = 120,
    INSURGENCY(RefCell<u64>) = 121,
    INTERNET_BLACKOUT(RefCell<u64>) = 122,
    INTERNET_CENSORSHIP(RefCell<u64>) = 123,
    JIHAD(RefCell<u64>) = 124,
    KIDNAP(RefCell<u64>) = 125,
    KILL(RefCell<u64>) = 126,
    LANDMINE(RefCell<u64>) = 127,
    LEADER(RefCell<u64>) = 128,
    LEGALIZE(RefCell<u64>) = 129,
    LEGISLATION(RefCell<u64>) = 130,
    LGBT(RefCell<u64>) = 131,
    LITERACY(RefCell<u64>) = 132,
    LOCUSTS(RefCell<u64>) = 133,
    MANMADE_DISASTER(RefCell<u64>) = 134,
    MANMADE_DISASTER_IMPLIED(RefCell<u64>) = 135,
    MARITIME(RefCell<u64>) = 136,
    MARITIME_INCIDENT(RefCell<u64>) = 137,
    MARITIME_INCIDENT_IMPLIED(RefCell<u64>) = 138,
    MARITIME_INCIDENT_SELF_IDENTIFIED(RefCell<u64>) = 139,
    MARITIME_PIRACY(RefCell<u64>) = 140,
    MEDIA_CENSORSHIP(RefCell<u64>) = 141,
    MEDIA_MSM(RefCell<u64>) = 142,
    MEDIA_SOCIAL(RefCell<u64>) = 143,
    MEDICAL(RefCell<u64>) = 144,
    MEDICAL_SECURITY(RefCell<u64>) = 145,
    MIL_SELF_IDENTIFIED_ARMS_DEAL(RefCell<u64>) = 146,
    MIL_WEAPONS_PROLIFERATION(RefCell<u64>) = 147,
    MILITARY(RefCell<u64>) = 148,
    MILITARY_COOPERATION(RefCell<u64>) = 149,
    MOVEMENT_ENVIRONMENTAL(RefCell<u64>) = 150,
    MOVEMENT_GENERAL(RefCell<u64>) = 151,
    MOVEMENT_OTHER(RefCell<u64>) = 152,
    MOVEMENT_SOCIAL(RefCell<u64>) = 153,
    MOVEMENT_WOMENS(RefCell<u64>) = 154,
    NATURAL_DISASTER(RefCell<u64>) = 155,
    NEGOTIATIONS(RefCell<u64>) = 156,
    NEW_CONSTRUCTION(RefCell<u64>) = 157,
    ORGANIZED_CRIME(RefCell<u64>) = 158,
    PEACEKEEPING(RefCell<u64>) = 159,
    PERSECUTION(RefCell<u64>) = 160,
    PHONE_OUTAGE(RefCell<u64>) = 161,
    PIPELINE_INCIDENT(RefCell<u64>) = 162,
    PIRACY(RefCell<u64>) = 163,
    POL_HOSTVISIT(RefCell<u64>) = 164,
    POLITICAL_PRISONER(RefCell<u64>) = 165,
    POLITICAL_TURMOIL(RefCell<u64>) = 166,
    POPULATION_DENSITY(RefCell<u64>) = 167,
    POVERTY(RefCell<u64>) = 168,
    POWER_OUTAGE(RefCell<u64>) = 169,
    PRIVATIZATION(RefCell<u64>) = 170,
    PROPAGANDA(RefCell<u64>) = 171,
    PROPERTY_RIGHTS(RefCell<u64>) = 172,
    PROTEST(RefCell<u64>) = 173,
    PUBLIC_TRANSPORT(RefCell<u64>) = 174,
    RAIL_INCIDENT(RefCell<u64>) = 175,
    RAPE(RefCell<u64>) = 176,
    RATIFY(RefCell<u64>) = 177,
    REBELLION(RefCell<u64>) = 178,
    REBELS(RefCell<u64>) = 179,
    RECRUITMENT(RefCell<u64>) = 180,
    REFUGEES(RefCell<u64>) = 181,
    REL_ANTISEMITISM(RefCell<u64>) = 182,
    RELATIONS(RefCell<u64>) = 183,
    RELEASE_HOSTAGE(RefCell<u64>) = 184,
    RELEASE_PRISON(RefCell<u64>) = 185,
    RELIGION(RefCell<u64>) = 186,
    RESIGNATION(RefCell<u64>) = 187,
    RETALIATE(RefCell<u64>) = 188,
    RETIREMENT(RefCell<u64>) = 189,
    RETIREMENTS(RefCell<u64>) = 190,
    ROAD_INCIDENT(RefCell<u64>) = 191,
    RURAL(RefCell<u64>) = 192,
    SANCTIONS(RefCell<u64>) = 193,
    SANITATION(RefCell<u64>) = 194,
    SCANDAL(RefCell<u64>) = 195,
    SCIENCE(RefCell<u64>) = 196,
    SECURITY_SERVICES(RefCell<u64>) = 197,
    SEIGE(RefCell<u64>) = 198,
    SEIZE(RefCell<u64>) = 199,
    SELF_IDENTIFIED_ATROCITY(RefCell<u64>) = 200,
    SELF_IDENTIFIED_ENVIRON_DISASTER(RefCell<u64>) = 201,
    SELF_IDENTIFIED_HUMAN_RIGHTS(RefCell<u64>) = 202,
    SELF_IDENTIFIED_HUMANITARIAN_CRISIS(RefCell<u64>) = 203,
    SEPARATISTS(RefCell<u64>) = 204,
    SHORTAGE(RefCell<u64>) = 205,
    SICKENED(RefCell<u64>) = 206,
    SLFID_CAPACITY_BUILDING(RefCell<u64>) = 207,
    SLFID_CIVIL_LIBERTIES(RefCell<u64>) = 208,
    SLFID_DICTATORSHIP(RefCell<u64>) = 209,
    SLFID_ECONOMIC_DEVELOPMENT(RefCell<u64>) = 210,
    SLFID_ECONOMIC_POWER(RefCell<u64>) = 211,
    SLFID_MILITARY_BUILDUP(RefCell<u64>) = 212,
    SLFID_MILITARY_READINESS(RefCell<u64>) = 213,
    SLFID_MILITARY_SPENDING(RefCell<u64>) = 214,
    SLFID_MINERAL_RESOURCES(RefCell<u64>) = 215,
    SLFID_NATURAL_RESOURCES(RefCell<u64>) = 216,
    SLFID_PEACE_BUILDING(RefCell<u64>) = 217,
    SLFID_POLITICAL_BOUNDARIES(RefCell<u64>) = 218,
    SLFID_RULE_OF_LAW(RefCell<u64>) = 219,
    SLUMS(RefCell<u64>) = 220,
    SMUGGLING(RefCell<u64>) = 221,
    SOC_DIPLOMCOOP(RefCell<u64>) = 222,
    SOC_ECONCOOP(RefCell<u64>) = 223,
    SOC_EXPRESSREGRET(RefCell<u64>) = 224,
    SOC_EXPRESSSUPPORT(RefCell<u64>) = 225,
    SOC_FORCEDRELOCATION(RefCell<u64>) = 226,
    SOC_GENERALCRIME(RefCell<u64>) = 227,
    SOC_INTELSHARING(RefCell<u64>) = 228,
    SOC_JUDICIALCOOP(RefCell<u64>) = 229,
    SOC_MASSMIGRATION(RefCell<u64>) = 230,
    SOC_PARDON(RefCell<u64>) = 231,
    SOC_SUICIDE(RefCell<u64>) = 232,
    SOC_SUSPICIOUSACTIVITIES(RefCell<u64>) = 233,
    SOC_SUSPICIOUSPEOPLE(RefCell<u64>) = 234,
    SOC_TRAFFICACCIDENT(RefCell<u64>) = 235,
    SOVEREIGNTY(RefCell<u64>) = 236,
    STATE_OF_EMERGENCY(RefCell<u64>) = 237,
    STRIKE(RefCell<u64>) = 238,
    SUICIDE_ATTACK(RefCell<u64>) = 239,
    SURVEILLANCE(RefCell<u64>) = 240,
    TAKE_OFFICE(RefCell<u64>) = 241,
    TAX_CARTELS(RefCell<u64>) = 242,
    TAX_DISEASE(RefCell<u64>) = 243,
    TAX_ETHNICITY(RefCell<u64>) = 244,
    TAX_FNCACT(RefCell<u64>) = 245,
    TAX_FOODSTAPLES(RefCell<u64>) = 246,
    TAX_MILITARY_TITLE(RefCell<u64>) = 247,
    TAX_POLITICAL_PARTY(RefCell<u64>) = 248,
    TAX_RELIGION(RefCell<u64>) = 249,
    TAX_SPECIAL_ISSUES(RefCell<u64>) = 250,
    TAX_SPECIALDEATH(RefCell<u64>) = 251,
    TAX_TERROR_GROUP(RefCell<u64>) = 252,
    TAX_WEAPONS(RefCell<u64>) = 253,
    TERROR(RefCell<u64>) = 254,
    TORTURE(RefCell<u64>) = 255,
    TOURISM(RefCell<u64>) = 256,
    TRAFFIC(RefCell<u64>) = 257,
    TRANSPARENCY(RefCell<u64>) = 258,
    TREASON(RefCell<u64>) = 259,
    TRIAL(RefCell<u64>) = 260,
    UNEMPLOYMENT(RefCell<u64>) = 261,
    UNGOVERNED(RefCell<u64>) = 262,
    UNREST_CHECKPOINT(RefCell<u64>) = 263,
    UNREST_CLOSINGBORDER(RefCell<u64>) = 264,
    UNREST_HUNGERSTRIKE(RefCell<u64>) = 265,
    UNREST_MOLOTOVCOCKTAIL(RefCell<u64>) = 266,
    UNREST_POLICEBRUTALITY(RefCell<u64>) = 267,
    UNREST_STONETHROWING(RefCell<u64>) = 268,
    UNREST_STONING(RefCell<u64>) = 269,
    UNSAFE_WORK_ENVIRONMENT(RefCell<u64>) = 270,
    URBAN(RefCell<u64>) = 271,
    URBAN_SPRAWL(RefCell<u64>) = 272,
    VANDALIZE(RefCell<u64>) = 273,
    VETO(RefCell<u64>) = 274,
    VIOLENT_UNREST(RefCell<u64>) = 275,
    WATER_SECURITY(RefCell<u64>) = 276,
    WHISTLEBLOWER(RefCell<u64>) = 277,
    WMD(RefCell<u64>) = 278,
    WOUND(RefCell<u64>) = 279,
}

/// Implement the conversion from `u16` to `GDELTCategoryList`.
impl From<u16> for GDELTCategoryList {
    fn from(value: u16) -> Self {
        match value {
            0 => GDELTCategoryList::UNKNOWN(RefCell::new(0)),
            1 => GDELTCategoryList::AFFECT(RefCell::new(0)),
            2 => GDELTCategoryList::AGRICULTURE(RefCell::new(0)),
            3 => GDELTCategoryList::ALLIANCE(RefCell::new(0)),
            4 => GDELTCategoryList::APPOINTMENT(RefCell::new(0)),
            5 => GDELTCategoryList::ARMEDCONFLICT(RefCell::new(0)),
            6 => GDELTCategoryList::ARREST(RefCell::new(0)),
            7 => GDELTCategoryList::ASSASSINATION(RefCell::new(0)),
            8 => GDELTCategoryList::AUSTERITY(RefCell::new(0)),
            9 => GDELTCategoryList::AVIATION_INCIDENT(RefCell::new(0)),
            10 => GDELTCategoryList::BAN(RefCell::new(0)),
            11 => GDELTCategoryList::BLACK_MARKET(RefCell::new(0)),
            12 => GDELTCategoryList::BLOCKADE(RefCell::new(0)),
            13 => GDELTCategoryList::BORDER(RefCell::new(0)),
            14 => GDELTCategoryList::BULLYING(RefCell::new(0)),
            15 => GDELTCategoryList::CEASEFIRE(RefCell::new(0)),
            16 => GDELTCategoryList::CHARASMATIC_LEADERSHIP(RefCell::new(0)),
            17 => GDELTCategoryList::CHECKPOINT(RefCell::new(0)),
            18 => GDELTCategoryList::CLAIM_CREDIT(RefCell::new(0)),
            19 => GDELTCategoryList::CLOSURE(RefCell::new(0)),
            20 => GDELTCategoryList::CONFISCATION(RefCell::new(0)),
            21 => GDELTCategoryList::CONSTITUTIONAL(RefCell::new(0)),
            22 => GDELTCategoryList::CORRUPTION(RefCell::new(0)),
            23 => GDELTCategoryList::CRIME_CARTELS(RefCell::new(0)),
            24 => GDELTCategoryList::CRIME_COMMON_ROBBERY(RefCell::new(0)),
            25 => GDELTCategoryList::CRIME_ILLEGAL_DRUGS(RefCell::new(0)),
            26 => GDELTCategoryList::CURFEW(RefCell::new(0)),
            27 => GDELTCategoryList::CYBER_ATTACK(RefCell::new(0)),
            28 => GDELTCategoryList::DEATH_PENALTY(RefCell::new(0)),
            29 => GDELTCategoryList::DEFECTION(RefCell::new(0)),
            30 => GDELTCategoryList::DELAY(RefCell::new(0)),
            31 => GDELTCategoryList::DEMOCRACY(RefCell::new(0)),
            32 => GDELTCategoryList::DISABILITY(RefCell::new(0)),
            33 => GDELTCategoryList::DISCRIMINATION(RefCell::new(0)),
            34 => GDELTCategoryList::DISPLACED(RefCell::new(0)),
            35 => GDELTCategoryList::DRONE(RefCell::new(0)),
            36 => GDELTCategoryList::DRUG_TRADE(RefCell::new(0)),
            37 => GDELTCategoryList::ECON_BANKRUPTCY(RefCell::new(0)),
            38 => GDELTCategoryList::ECON_BOYCOTT(RefCell::new(0)),
            39 => GDELTCategoryList::ECON_COST_OF_LIVING(RefCell::new(0)),
            40 => GDELTCategoryList::ECON_CURRENCY_EXCHANGE_RATE(RefCell::new(0)),
            41 => GDELTCategoryList::ECON_CURRENCY_RESERVES(RefCell::new(0)),
            42 => GDELTCategoryList::ECON_CUTOUTLOOK(RefCell::new(0)),
            43 => GDELTCategoryList::ECON_DEBT(RefCell::new(0)),
            44 => GDELTCategoryList::ECON_DEREGULATION(RefCell::new(0)),
            45 => GDELTCategoryList::ECON_EARNINGSREPORT(RefCell::new(0)),
            46 => GDELTCategoryList::ECON_ENTREPRENEURSHIP(RefCell::new(0)),
            47 => GDELTCategoryList::ECON_FOREIGNINVEST(RefCell::new(0)),
            48 => GDELTCategoryList::ECON_FREETRADE(RefCell::new(0)),
            49 => GDELTCategoryList::ECON_HOUSING_PRICES(RefCell::new(0)),
            50 => GDELTCategoryList::ECON_INFORMAL_ECONOMY(RefCell::new(0)),
            51 => GDELTCategoryList::ECON_INTEREST_RATES(RefCell::new(0)),
            52 => GDELTCategoryList::ECON_IPO(RefCell::new(0)),
            53 => GDELTCategoryList::ECON_MONOPOLY(RefCell::new(0)),
            54 => GDELTCategoryList::ECON_MOU(RefCell::new(0)),
            55 => GDELTCategoryList::ECON_NATIONALIZE(RefCell::new(0)),
            56 => GDELTCategoryList::ECON_PRICECONTROL(RefCell::new(0)),
            57 => GDELTCategoryList::ECON_REMITTANCE(RefCell::new(0)),
            58 => GDELTCategoryList::ECON_STOCKMARKET(RefCell::new(0)),
            59 => GDELTCategoryList::ECON_SUBSIDIES(RefCell::new(0)),
            60 => GDELTCategoryList::ECON_TAXATION(RefCell::new(0)),
            61 => GDELTCategoryList::ECON_TRADE_DISPUTE(RefCell::new(0)),
            62 => GDELTCategoryList::ECON_UNIONS(RefCell::new(0)),
            63 => GDELTCategoryList::EDUCATION(RefCell::new(0)),
            64 => GDELTCategoryList::ELECTION(RefCell::new(0)),
            65 => GDELTCategoryList::ELECTION_FRAUD(RefCell::new(0)),
            66 => GDELTCategoryList::ENV_BIOFUEL(RefCell::new(0)),
            67 => GDELTCategoryList::ENV_CARBONCAPTURE(RefCell::new(0)),
            68 => GDELTCategoryList::ENV_CLIMATECHANGE(RefCell::new(0)),
            69 => GDELTCategoryList::ENV_COAL(RefCell::new(0)),
            70 => GDELTCategoryList::ENV_DEFORESTATION(RefCell::new(0)),
            71 => GDELTCategoryList::ENV_FISHERY(RefCell::new(0)),
            72 => GDELTCategoryList::ENV_FORESTRY(RefCell::new(0)),
            73 => GDELTCategoryList::ENV_GEOTHERMAL(RefCell::new(0)),
            74 => GDELTCategoryList::ENV_GREEN(RefCell::new(0)),
            75 => GDELTCategoryList::ENV_HYDRO(RefCell::new(0)),
            76 => GDELTCategoryList::ENV_METALS(RefCell::new(0)),
            77 => GDELTCategoryList::ENV_MINING(RefCell::new(0)),
            78 => GDELTCategoryList::ENV_NATURALGAS(RefCell::new(0)),
            79 => GDELTCategoryList::ENV_NUCLEARPOWER(RefCell::new(0)),
            80 => GDELTCategoryList::ENV_OIL(RefCell::new(0)),
            81 => GDELTCategoryList::ENV_OVERFISH(RefCell::new(0)),
            82 => GDELTCategoryList::ENV_POACHING(RefCell::new(0)),
            83 => GDELTCategoryList::ENV_SOLAR(RefCell::new(0)),
            84 => GDELTCategoryList::ENV_SPECIESENDANGERED(RefCell::new(0)),
            85 => GDELTCategoryList::ENV_SPECIESEXTINCT(RefCell::new(0)),
            86 => GDELTCategoryList::ENV_WATERWAYS(RefCell::new(0)),
            87 => GDELTCategoryList::ENV_WINDPOWER(RefCell::new(0)),
            88 => GDELTCategoryList::ETH_INDIGINOUS(RefCell::new(0)),
            89 => GDELTCategoryList::EVACUATION(RefCell::new(0)),
            90 => GDELTCategoryList::EXHUMATION(RefCell::new(0)),
            91 => GDELTCategoryList::EXILE(RefCell::new(0)),
            92 => GDELTCategoryList::EXTREMISM(RefCell::new(0)),
            93 => GDELTCategoryList::FIREARM_OWNERSHIP(RefCell::new(0)),
            94 => GDELTCategoryList::FOOD_SECURITY(RefCell::new(0)),
            95 => GDELTCategoryList::FOOD_STAPLE(RefCell::new(0)),
            96 => GDELTCategoryList::FREESPEECH(RefCell::new(0)),
            97 => GDELTCategoryList::FUELPRICES(RefCell::new(0)),
            98 => GDELTCategoryList::GEN_HOLIDAY(RefCell::new(0)),
            99 => GDELTCategoryList::GENDER_VIOLENCE(RefCell::new(0)),
            100 => GDELTCategoryList::GENERAL_GOVERNMENT(RefCell::new(0)),
            101 => GDELTCategoryList::GENERAL_HEALTH(RefCell::new(0)),
            102 => GDELTCategoryList::GENTRIFICATION(RefCell::new(0)),
            103 => GDELTCategoryList::GOV_DISSOLVEGOV(RefCell::new(0)),
            104 => GDELTCategoryList::GOV_DIVISIONOFPOWER(RefCell::new(0)),
            105 => GDELTCategoryList::GOV_INTERGOVERNMENTAL(RefCell::new(0)),
            106 => GDELTCategoryList::GOV_REFORM(RefCell::new(0)),
            107 => GDELTCategoryList::GOV_REPATRIATION(RefCell::new(0)),
            108 => GDELTCategoryList::GRIEVANCES(RefCell::new(0)),
            109 => GDELTCategoryList::HARASSMENT(RefCell::new(0)),
            110 => GDELTCategoryList::HATE_SPEECH(RefCell::new(0)),
            111 => GDELTCategoryList::HEALTH_PANDEMIC(RefCell::new(0)),
            112 => GDELTCategoryList::HEALTH_SEXTRANSDISEASE(RefCell::new(0)),
            113 => GDELTCategoryList::HEALTH_VACCINATION(RefCell::new(0)),
            114 => GDELTCategoryList::HUMAN_TRAFFICKING(RefCell::new(0)),
            115 => GDELTCategoryList::IDEOLOGY(RefCell::new(0)),
            116 => GDELTCategoryList::IMMIGRATION(RefCell::new(0)),
            117 => GDELTCategoryList::IMPEACHMENT(RefCell::new(0)),
            118 => GDELTCategoryList::INFO_HOAX(RefCell::new(0)),
            119 => GDELTCategoryList::INFO_RUMOR(RefCell::new(0)),
            120 => GDELTCategoryList::INFRASTRUCTURE_BAD_ROADS(RefCell::new(0)),
            121 => GDELTCategoryList::INSURGENCY(RefCell::new(0)),
            122 => GDELTCategoryList::INTERNET_BLACKOUT(RefCell::new(0)),
            123 => GDELTCategoryList::INTERNET_CENSORSHIP(RefCell::new(0)),
            124 => GDELTCategoryList::JIHAD(RefCell::new(0)),
            125 => GDELTCategoryList::KIDNAP(RefCell::new(0)),
            126 => GDELTCategoryList::KILL(RefCell::new(0)),
            127 => GDELTCategoryList::LANDMINE(RefCell::new(0)),
            128 => GDELTCategoryList::LEADER(RefCell::new(0)),
            129 => GDELTCategoryList::LEGALIZE(RefCell::new(0)),
            130 => GDELTCategoryList::LEGISLATION(RefCell::new(0)),
            131 => GDELTCategoryList::LGBT(RefCell::new(0)),
            132 => GDELTCategoryList::LITERACY(RefCell::new(0)),
            133 => GDELTCategoryList::LOCUSTS(RefCell::new(0)),
            134 => GDELTCategoryList::MANMADE_DISASTER(RefCell::new(0)),
            135 => GDELTCategoryList::MANMADE_DISASTER_IMPLIED(RefCell::new(0)),
            136 => GDELTCategoryList::MARITIME(RefCell::new(0)),
            137 => GDELTCategoryList::MARITIME_INCIDENT(RefCell::new(0)),
            138 => GDELTCategoryList::MARITIME_INCIDENT_IMPLIED(RefCell::new(0)),
            139 => GDELTCategoryList::MARITIME_INCIDENT_SELF_IDENTIFIED(RefCell::new(0)),
            140 => GDELTCategoryList::MARITIME_PIRACY(RefCell::new(0)),
            141 => GDELTCategoryList::MEDIA_CENSORSHIP(RefCell::new(0)),
            142 => GDELTCategoryList::MEDIA_MSM(RefCell::new(0)),
            143 => GDELTCategoryList::MEDIA_SOCIAL(RefCell::new(0)),
            144 => GDELTCategoryList::MEDICAL(RefCell::new(0)),
            145 => GDELTCategoryList::MEDICAL_SECURITY(RefCell::new(0)),
            146 => GDELTCategoryList::MIL_SELF_IDENTIFIED_ARMS_DEAL(RefCell::new(0)),
            147 => GDELTCategoryList::MIL_WEAPONS_PROLIFERATION(RefCell::new(0)),
            148 => GDELTCategoryList::MILITARY(RefCell::new(0)),
            149 => GDELTCategoryList::MILITARY_COOPERATION(RefCell::new(0)),
            150 => GDELTCategoryList::MOVEMENT_ENVIRONMENTAL(RefCell::new(0)),
            151 => GDELTCategoryList::MOVEMENT_GENERAL(RefCell::new(0)),
            152 => GDELTCategoryList::MOVEMENT_OTHER(RefCell::new(0)),
            153 => GDELTCategoryList::MOVEMENT_SOCIAL(RefCell::new(0)),
            154 => GDELTCategoryList::MOVEMENT_WOMENS(RefCell::new(0)),
            155 => GDELTCategoryList::NATURAL_DISASTER(RefCell::new(0)),
            156 => GDELTCategoryList::NEGOTIATIONS(RefCell::new(0)),
            157 => GDELTCategoryList::NEW_CONSTRUCTION(RefCell::new(0)),
            158 => GDELTCategoryList::ORGANIZED_CRIME(RefCell::new(0)),
            159 => GDELTCategoryList::PEACEKEEPING(RefCell::new(0)),
            160 => GDELTCategoryList::PERSECUTION(RefCell::new(0)),
            161 => GDELTCategoryList::PHONE_OUTAGE(RefCell::new(0)),
            162 => GDELTCategoryList::PIPELINE_INCIDENT(RefCell::new(0)),
            163 => GDELTCategoryList::PIRACY(RefCell::new(0)),
            164 => GDELTCategoryList::POL_HOSTVISIT(RefCell::new(0)),
            165 => GDELTCategoryList::POLITICAL_PRISONER(RefCell::new(0)),
            166 => GDELTCategoryList::POLITICAL_TURMOIL(RefCell::new(0)),
            167 => GDELTCategoryList::POPULATION_DENSITY(RefCell::new(0)),
            168 => GDELTCategoryList::POVERTY(RefCell::new(0)),
            169 => GDELTCategoryList::POWER_OUTAGE(RefCell::new(0)),
            170 => GDELTCategoryList::PRIVATIZATION(RefCell::new(0)),
            171 => GDELTCategoryList::PROPAGANDA(RefCell::new(0)),
            172 => GDELTCategoryList::PROPERTY_RIGHTS(RefCell::new(0)),
            173 => GDELTCategoryList::PROTEST(RefCell::new(0)),
            174 => GDELTCategoryList::PUBLIC_TRANSPORT(RefCell::new(0)),
            175 => GDELTCategoryList::RAIL_INCIDENT(RefCell::new(0)),
            176 => GDELTCategoryList::RAPE(RefCell::new(0)),
            177 => GDELTCategoryList::RATIFY(RefCell::new(0)),
            178 => GDELTCategoryList::REBELLION(RefCell::new(0)),
            179 => GDELTCategoryList::REBELS(RefCell::new(0)),
            180 => GDELTCategoryList::RECRUITMENT(RefCell::new(0)),
            181 => GDELTCategoryList::REFUGEES(RefCell::new(0)),
            182 => GDELTCategoryList::REL_ANTISEMITISM(RefCell::new(0)),
            183 => GDELTCategoryList::RELATIONS(RefCell::new(0)),
            184 => GDELTCategoryList::RELEASE_HOSTAGE(RefCell::new(0)),
            185 => GDELTCategoryList::RELEASE_PRISON(RefCell::new(0)),
            186 => GDELTCategoryList::RELIGION(RefCell::new(0)),
            187 => GDELTCategoryList::RESIGNATION(RefCell::new(0)),
            188 => GDELTCategoryList::RETALIATE(RefCell::new(0)),
            189 => GDELTCategoryList::RETIREMENT(RefCell::new(0)),
            190 => GDELTCategoryList::RETIREMENTS(RefCell::new(0)),
            191 => GDELTCategoryList::ROAD_INCIDENT(RefCell::new(0)),
            192 => GDELTCategoryList::RURAL(RefCell::new(0)),
            193 => GDELTCategoryList::SANCTIONS(RefCell::new(0)),
            194 => GDELTCategoryList::SANITATION(RefCell::new(0)),
            195 => GDELTCategoryList::SCANDAL(RefCell::new(0)),
            196 => GDELTCategoryList::SCIENCE(RefCell::new(0)),
            197 => GDELTCategoryList::SECURITY_SERVICES(RefCell::new(0)),
            198 => GDELTCategoryList::SEIGE(RefCell::new(0)),
            199 => GDELTCategoryList::SEIZE(RefCell::new(0)),
            200 => GDELTCategoryList::SELF_IDENTIFIED_ATROCITY(RefCell::new(0)),
            201 => GDELTCategoryList::SELF_IDENTIFIED_ENVIRON_DISASTER(RefCell::new(0)),
            202 => GDELTCategoryList::SELF_IDENTIFIED_HUMAN_RIGHTS(RefCell::new(0)),
            203 => GDELTCategoryList::SELF_IDENTIFIED_HUMANITARIAN_CRISIS(RefCell::new(0)),
            204 => GDELTCategoryList::SEPARATISTS(RefCell::new(0)),
            205 => GDELTCategoryList::SHORTAGE(RefCell::new(0)),
            206 => GDELTCategoryList::SICKENED(RefCell::new(0)),
            207 => GDELTCategoryList::SLFID_CAPACITY_BUILDING(RefCell::new(0)),
            208 => GDELTCategoryList::SLFID_CIVIL_LIBERTIES(RefCell::new(0)),
            209 => GDELTCategoryList::SLFID_DICTATORSHIP(RefCell::new(0)),
            210 => GDELTCategoryList::SLFID_ECONOMIC_DEVELOPMENT(RefCell::new(0)),
            211 => GDELTCategoryList::SLFID_ECONOMIC_POWER(RefCell::new(0)),
            212 => GDELTCategoryList::SLFID_MILITARY_BUILDUP(RefCell::new(0)),
            213 => GDELTCategoryList::SLFID_MILITARY_READINESS(RefCell::new(0)),
            214 => GDELTCategoryList::SLFID_MILITARY_SPENDING(RefCell::new(0)),
            215 => GDELTCategoryList::SLFID_MINERAL_RESOURCES(RefCell::new(0)),
            216 => GDELTCategoryList::SLFID_NATURAL_RESOURCES(RefCell::new(0)),
            217 => GDELTCategoryList::SLFID_PEACE_BUILDING(RefCell::new(0)),
            218 => GDELTCategoryList::SLFID_POLITICAL_BOUNDARIES(RefCell::new(0)),
            219 => GDELTCategoryList::SLFID_RULE_OF_LAW(RefCell::new(0)),
            220 => GDELTCategoryList::SLUMS(RefCell::new(0)),
            221 => GDELTCategoryList::SMUGGLING(RefCell::new(0)),
            222 => GDELTCategoryList::SOC_DIPLOMCOOP(RefCell::new(0)),
            223 => GDELTCategoryList::SOC_ECONCOOP(RefCell::new(0)),
            224 => GDELTCategoryList::SOC_EXPRESSREGRET(RefCell::new(0)),
            225 => GDELTCategoryList::SOC_EXPRESSSUPPORT(RefCell::new(0)),
            226 => GDELTCategoryList::SOC_FORCEDRELOCATION(RefCell::new(0)),
            227 => GDELTCategoryList::SOC_GENERALCRIME(RefCell::new(0)),
            228 => GDELTCategoryList::SOC_INTELSHARING(RefCell::new(0)),
            229 => GDELTCategoryList::SOC_JUDICIALCOOP(RefCell::new(0)),
            230 => GDELTCategoryList::SOC_MASSMIGRATION(RefCell::new(0)),
            231 => GDELTCategoryList::SOC_PARDON(RefCell::new(0)),
            232 => GDELTCategoryList::SOC_SUICIDE(RefCell::new(0)),
            233 => GDELTCategoryList::SOC_SUSPICIOUSACTIVITIES(RefCell::new(0)),
            234 => GDELTCategoryList::SOC_SUSPICIOUSPEOPLE(RefCell::new(0)),
            235 => GDELTCategoryList::SOC_TRAFFICACCIDENT(RefCell::new(0)),
            236 => GDELTCategoryList::SOVEREIGNTY(RefCell::new(0)),
            237 => GDELTCategoryList::STATE_OF_EMERGENCY(RefCell::new(0)),
            238 => GDELTCategoryList::STRIKE(RefCell::new(0)),
            239 => GDELTCategoryList::SUICIDE_ATTACK(RefCell::new(0)),
            240 => GDELTCategoryList::SURVEILLANCE(RefCell::new(0)),
            241 => GDELTCategoryList::TAKE_OFFICE(RefCell::new(0)),
            242 => GDELTCategoryList::TAX_CARTELS(RefCell::new(0)),
            243 => GDELTCategoryList::TAX_DISEASE(RefCell::new(0)),
            244 => GDELTCategoryList::TAX_ETHNICITY(RefCell::new(0)),
            245 => GDELTCategoryList::TAX_FNCACT(RefCell::new(0)),
            246 => GDELTCategoryList::TAX_FOODSTAPLES(RefCell::new(0)),
            247 => GDELTCategoryList::TAX_MILITARY_TITLE(RefCell::new(0)),
            248 => GDELTCategoryList::TAX_POLITICAL_PARTY(RefCell::new(0)),
            249 => GDELTCategoryList::TAX_RELIGION(RefCell::new(0)),
            250 => GDELTCategoryList::TAX_SPECIAL_ISSUES(RefCell::new(0)),
            251 => GDELTCategoryList::TAX_SPECIALDEATH(RefCell::new(0)),
            252 => GDELTCategoryList::TAX_TERROR_GROUP(RefCell::new(0)),
            253 => GDELTCategoryList::TAX_WEAPONS(RefCell::new(0)),
            254 => GDELTCategoryList::TERROR(RefCell::new(0)),
            255 => GDELTCategoryList::TORTURE(RefCell::new(0)),
            256 => GDELTCategoryList::TOURISM(RefCell::new(0)),
            257 => GDELTCategoryList::TRAFFIC(RefCell::new(0)),
            258 => GDELTCategoryList::TRANSPARENCY(RefCell::new(0)),
            259 => GDELTCategoryList::TREASON(RefCell::new(0)),
            260 => GDELTCategoryList::TRIAL(RefCell::new(0)),
            261 => GDELTCategoryList::UNEMPLOYMENT(RefCell::new(0)),
            262 => GDELTCategoryList::UNGOVERNED(RefCell::new(0)),
            263 => GDELTCategoryList::UNREST_CHECKPOINT(RefCell::new(0)),
            264 => GDELTCategoryList::UNREST_CLOSINGBORDER(RefCell::new(0)),
            265 => GDELTCategoryList::UNREST_HUNGERSTRIKE(RefCell::new(0)),
            266 => GDELTCategoryList::UNREST_MOLOTOVCOCKTAIL(RefCell::new(0)),
            267 => GDELTCategoryList::UNREST_POLICEBRUTALITY(RefCell::new(0)),
            268 => GDELTCategoryList::UNREST_STONETHROWING(RefCell::new(0)),
            269 => GDELTCategoryList::UNREST_STONING(RefCell::new(0)),
            270 => GDELTCategoryList::UNSAFE_WORK_ENVIRONMENT(RefCell::new(0)),
            271 => GDELTCategoryList::URBAN(RefCell::new(0)),
            272 => GDELTCategoryList::URBAN_SPRAWL(RefCell::new(0)),
            273 => GDELTCategoryList::VANDALIZE(RefCell::new(0)),
            274 => GDELTCategoryList::VETO(RefCell::new(0)),
            275 => GDELTCategoryList::VIOLENT_UNREST(RefCell::new(0)),
            276 => GDELTCategoryList::WATER_SECURITY(RefCell::new(0)),
            277 => GDELTCategoryList::WHISTLEBLOWER(RefCell::new(0)),
            278 => GDELTCategoryList::WMD(RefCell::new(0)),
            279 => GDELTCategoryList::WOUND(RefCell::new(0)),
            _ => GDELTCategoryList::UNKNOWN(RefCell::new(0)), // Default case for unknown values
        }
    }
}

/// Implement the conversion from `GDELTCategoryList` to `u16`.
impl From<GDELTCategoryList> for u16 {
    fn from(value: GDELTCategoryList) -> u16 {
        match value {
            GDELTCategoryList::UNKNOWN(_) => 0,
            GDELTCategoryList::AFFECT(_) => 1,
            GDELTCategoryList::AGRICULTURE(_) => 2,
            GDELTCategoryList::ALLIANCE(_) => 3,
            GDELTCategoryList::APPOINTMENT(_) => 4,
            GDELTCategoryList::ARMEDCONFLICT(_) => 5,
            GDELTCategoryList::ARREST(_) => 6,
            GDELTCategoryList::ASSASSINATION(_) => 7,
            GDELTCategoryList::AUSTERITY(_) => 8,
            GDELTCategoryList::AVIATION_INCIDENT(_) => 9,
            GDELTCategoryList::BAN(_) => 10,
            GDELTCategoryList::BLACK_MARKET(_) => 11,
            GDELTCategoryList::BLOCKADE(_) => 12,
            GDELTCategoryList::BORDER(_) => 13,
            GDELTCategoryList::BULLYING(_) => 14,
            GDELTCategoryList::CEASEFIRE(_) => 15,
            GDELTCategoryList::CHARASMATIC_LEADERSHIP(_) => 16,
            GDELTCategoryList::CHECKPOINT(_) => 17,
            GDELTCategoryList::CLAIM_CREDIT(_) => 18,
            GDELTCategoryList::CLOSURE(_) => 19,
            GDELTCategoryList::CONFISCATION(_) => 20,
            GDELTCategoryList::CONSTITUTIONAL(_) => 21,
            GDELTCategoryList::CORRUPTION(_) => 22,
            GDELTCategoryList::CRIME_CARTELS(_) => 23,
            GDELTCategoryList::CRIME_COMMON_ROBBERY(_) => 24,
            GDELTCategoryList::CRIME_ILLEGAL_DRUGS(_) => 25,
            GDELTCategoryList::CURFEW(_) => 26,
            GDELTCategoryList::CYBER_ATTACK(_) => 27,
            GDELTCategoryList::DEATH_PENALTY(_) => 28,
            GDELTCategoryList::DEFECTION(_) => 29,
            GDELTCategoryList::DELAY(_) => 30,
            GDELTCategoryList::DEMOCRACY(_) => 31,
            GDELTCategoryList::DISABILITY(_) => 32,
            GDELTCategoryList::DISCRIMINATION(_) => 33,
            GDELTCategoryList::DISPLACED(_) => 34,
            GDELTCategoryList::DRONE(_) => 35,
            GDELTCategoryList::DRUG_TRADE(_) => 36,
            GDELTCategoryList::ECON_BANKRUPTCY(_) => 37,
            GDELTCategoryList::ECON_BOYCOTT(_) => 38,
            GDELTCategoryList::ECON_COST_OF_LIVING(_) => 39,
            GDELTCategoryList::ECON_CURRENCY_EXCHANGE_RATE(_) => 40,
            GDELTCategoryList::ECON_CURRENCY_RESERVES(_) => 41,
            GDELTCategoryList::ECON_CUTOUTLOOK(_) => 42,
            GDELTCategoryList::ECON_DEBT(_) => 43,
            GDELTCategoryList::ECON_DEREGULATION(_) => 44,
            GDELTCategoryList::ECON_EARNINGSREPORT(_) => 45,
            GDELTCategoryList::ECON_ENTREPRENEURSHIP(_) => 46,
            GDELTCategoryList::ECON_FOREIGNINVEST(_) => 47,
            GDELTCategoryList::ECON_FREETRADE(_) => 48,
            GDELTCategoryList::ECON_HOUSING_PRICES(_) => 49,
            GDELTCategoryList::ECON_INFORMAL_ECONOMY(_) => 50,
            GDELTCategoryList::ECON_INTEREST_RATES(_) => 51,
            GDELTCategoryList::ECON_IPO(_) => 52,
            GDELTCategoryList::ECON_MONOPOLY(_) => 53,
            GDELTCategoryList::ECON_MOU(_) => 54,
            GDELTCategoryList::ECON_NATIONALIZE(_) => 55,
            GDELTCategoryList::ECON_PRICECONTROL(_) => 56,
            GDELTCategoryList::ECON_REMITTANCE(_) => 57,
            GDELTCategoryList::ECON_STOCKMARKET(_) => 58,
            GDELTCategoryList::ECON_SUBSIDIES(_) => 59,
            GDELTCategoryList::ECON_TAXATION(_) => 60,
            GDELTCategoryList::ECON_TRADE_DISPUTE(_) => 61,
            GDELTCategoryList::ECON_UNIONS(_) => 62,
            GDELTCategoryList::EDUCATION(_) => 63,
            GDELTCategoryList::ELECTION(_) => 64,
            GDELTCategoryList::ELECTION_FRAUD(_) => 65,
            GDELTCategoryList::ENV_BIOFUEL(_) => 66,
            GDELTCategoryList::ENV_CARBONCAPTURE(_) => 67,
            GDELTCategoryList::ENV_CLIMATECHANGE(_) => 68,
            GDELTCategoryList::ENV_COAL(_) => 69,
            GDELTCategoryList::ENV_DEFORESTATION(_) => 70,
            GDELTCategoryList::ENV_FISHERY(_) => 71,
            GDELTCategoryList::ENV_FORESTRY(_) => 72,
            GDELTCategoryList::ENV_GEOTHERMAL(_) => 73,
            GDELTCategoryList::ENV_GREEN(_) => 74,
            GDELTCategoryList::ENV_HYDRO(_) => 75,
            GDELTCategoryList::ENV_METALS(_) => 76,
            GDELTCategoryList::ENV_MINING(_) => 77,
            GDELTCategoryList::ENV_NATURALGAS(_) => 78,
            GDELTCategoryList::ENV_NUCLEARPOWER(_) => 79,
            GDELTCategoryList::ENV_OIL(_) => 80,
            GDELTCategoryList::ENV_OVERFISH(_) => 81,
            GDELTCategoryList::ENV_POACHING(_) => 82,
            GDELTCategoryList::ENV_SOLAR(_) => 83,
            GDELTCategoryList::ENV_SPECIESENDANGERED(_) => 84,
            GDELTCategoryList::ENV_SPECIESEXTINCT(_) => 85,
            GDELTCategoryList::ENV_WATERWAYS(_) => 86,
            GDELTCategoryList::ENV_WINDPOWER(_) => 87,
            GDELTCategoryList::ETH_INDIGINOUS(_) => 88,
            GDELTCategoryList::EVACUATION(_) => 89,
            GDELTCategoryList::EXHUMATION(_) => 90,
            GDELTCategoryList::EXILE(_) => 91,
            GDELTCategoryList::EXTREMISM(_) => 92,
            GDELTCategoryList::FIREARM_OWNERSHIP(_) => 93,
            GDELTCategoryList::FOOD_SECURITY(_) => 94,
            GDELTCategoryList::FOOD_STAPLE(_) => 95,
            GDELTCategoryList::FREESPEECH(_) => 96,
            GDELTCategoryList::FUELPRICES(_) => 97,
            GDELTCategoryList::GEN_HOLIDAY(_) => 98,
            GDELTCategoryList::GENDER_VIOLENCE(_) => 99,
            GDELTCategoryList::GENERAL_GOVERNMENT(_) => 100,
            GDELTCategoryList::GENERAL_HEALTH(_) => 101,
            GDELTCategoryList::GENTRIFICATION(_) => 102,
            GDELTCategoryList::GOV_DISSOLVEGOV(_) => 103,
            GDELTCategoryList::GOV_DIVISIONOFPOWER(_) => 104,
            GDELTCategoryList::GOV_INTERGOVERNMENTAL(_) => 105,
            GDELTCategoryList::GOV_REFORM(_) => 106,
            GDELTCategoryList::GOV_REPATRIATION(_) => 107,
            GDELTCategoryList::GRIEVANCES(_) => 108,
            GDELTCategoryList::HARASSMENT(_) => 109,
            GDELTCategoryList::HATE_SPEECH(_) => 110,
            GDELTCategoryList::HEALTH_PANDEMIC(_) => 111,
            GDELTCategoryList::HEALTH_SEXTRANSDISEASE(_) => 112,
            GDELTCategoryList::HEALTH_VACCINATION(_) => 113,
            GDELTCategoryList::HUMAN_TRAFFICKING(_) => 114,
            GDELTCategoryList::IDEOLOGY(_) => 115,
            GDELTCategoryList::IMMIGRATION(_) => 116,
            GDELTCategoryList::IMPEACHMENT(_) => 117,
            GDELTCategoryList::INFO_HOAX(_) => 118,
            GDELTCategoryList::INFO_RUMOR(_) => 119,
            GDELTCategoryList::INFRASTRUCTURE_BAD_ROADS(_) => 120,
            GDELTCategoryList::INSURGENCY(_) => 121,
            GDELTCategoryList::INTERNET_BLACKOUT(_) => 122,
            GDELTCategoryList::INTERNET_CENSORSHIP(_) => 123,
            GDELTCategoryList::JIHAD(_) => 124,
            GDELTCategoryList::KIDNAP(_) => 125,
            GDELTCategoryList::KILL(_) => 126,
            GDELTCategoryList::LANDMINE(_) => 127,
            GDELTCategoryList::LEADER(_) => 128,
            GDELTCategoryList::LEGALIZE(_) => 129,
            GDELTCategoryList::LEGISLATION(_) => 130,
            GDELTCategoryList::LGBT(_) => 131,
            GDELTCategoryList::LITERACY(_) => 132,
            GDELTCategoryList::LOCUSTS(_) => 133,
            GDELTCategoryList::MANMADE_DISASTER(_) => 134,
            GDELTCategoryList::MANMADE_DISASTER_IMPLIED(_) => 135,
            GDELTCategoryList::MARITIME(_) => 136,
            GDELTCategoryList::MARITIME_INCIDENT(_) => 137,
            GDELTCategoryList::MARITIME_INCIDENT_IMPLIED(_) => 138,
            GDELTCategoryList::MARITIME_INCIDENT_SELF_IDENTIFIED(_) => 139,
            GDELTCategoryList::MARITIME_PIRACY(_) => 140,
            GDELTCategoryList::MEDIA_CENSORSHIP(_) => 141,
            GDELTCategoryList::MEDIA_MSM(_) => 142,
            GDELTCategoryList::MEDIA_SOCIAL(_) => 143,
            GDELTCategoryList::MEDICAL(_) => 144,
            GDELTCategoryList::MEDICAL_SECURITY(_) => 145,
            GDELTCategoryList::MIL_SELF_IDENTIFIED_ARMS_DEAL(_) => 146,
            GDELTCategoryList::MIL_WEAPONS_PROLIFERATION(_) => 147,
            GDELTCategoryList::MILITARY(_) => 148,
            GDELTCategoryList::MILITARY_COOPERATION(_) => 149,
            GDELTCategoryList::MOVEMENT_ENVIRONMENTAL(_) => 150,
            GDELTCategoryList::MOVEMENT_GENERAL(_) => 151,
            GDELTCategoryList::MOVEMENT_OTHER(_) => 152,
            GDELTCategoryList::MOVEMENT_SOCIAL(_) => 153,
            GDELTCategoryList::MOVEMENT_WOMENS(_) => 154,
            GDELTCategoryList::NATURAL_DISASTER(_) => 155,
            GDELTCategoryList::NEGOTIATIONS(_) => 156,
            GDELTCategoryList::NEW_CONSTRUCTION(_) => 157,
            GDELTCategoryList::ORGANIZED_CRIME(_) => 158,
            GDELTCategoryList::PEACEKEEPING(_) => 159,
            GDELTCategoryList::PERSECUTION(_) => 160,
            GDELTCategoryList::PHONE_OUTAGE(_) => 161,
            GDELTCategoryList::PIPELINE_INCIDENT(_) => 162,
            GDELTCategoryList::PIRACY(_) => 163,
            GDELTCategoryList::POL_HOSTVISIT(_) => 164,
            GDELTCategoryList::POLITICAL_PRISONER(_) => 165,
            GDELTCategoryList::POLITICAL_TURMOIL(_) => 166,
            GDELTCategoryList::POPULATION_DENSITY(_) => 167,
            GDELTCategoryList::POVERTY(_) => 168,
            GDELTCategoryList::POWER_OUTAGE(_) => 169,
            GDELTCategoryList::PRIVATIZATION(_) => 170,
            GDELTCategoryList::PROPAGANDA(_) => 171,
            GDELTCategoryList::PROPERTY_RIGHTS(_) => 172,
            GDELTCategoryList::PROTEST(_) => 173,
            GDELTCategoryList::PUBLIC_TRANSPORT(_) => 174,
            GDELTCategoryList::RAIL_INCIDENT(_) => 175,
            GDELTCategoryList::RAPE(_) => 176,
            GDELTCategoryList::RATIFY(_) => 177,
            GDELTCategoryList::REBELLION(_) => 178,
            GDELTCategoryList::REBELS(_) => 179,
            GDELTCategoryList::RECRUITMENT(_) => 180,
            GDELTCategoryList::REFUGEES(_) => 181,
            GDELTCategoryList::REL_ANTISEMITISM(_) => 182,
            GDELTCategoryList::RELATIONS(_) => 183,
            GDELTCategoryList::RELEASE_HOSTAGE(_) => 184,
            GDELTCategoryList::RELEASE_PRISON(_) => 185,
            GDELTCategoryList::RELIGION(_) => 186,
            GDELTCategoryList::RESIGNATION(_) => 187,
            GDELTCategoryList::RETALIATE(_) => 188,
            GDELTCategoryList::RETIREMENT(_) => 189,
            GDELTCategoryList::RETIREMENTS(_) => 190,
            GDELTCategoryList::ROAD_INCIDENT(_) => 191,
            GDELTCategoryList::RURAL(_) => 192,
            GDELTCategoryList::SANCTIONS(_) => 193,
            GDELTCategoryList::SANITATION(_) => 194,
            GDELTCategoryList::SCANDAL(_) => 195,
            GDELTCategoryList::SCIENCE(_) => 196,
            GDELTCategoryList::SECURITY_SERVICES(_) => 197,
            GDELTCategoryList::SEIGE(_) => 198,
            GDELTCategoryList::SEIZE(_) => 199,
            GDELTCategoryList::SELF_IDENTIFIED_ATROCITY(_) => 200,
            GDELTCategoryList::SELF_IDENTIFIED_ENVIRON_DISASTER(_) => 201,
            GDELTCategoryList::SELF_IDENTIFIED_HUMAN_RIGHTS(_) => 202,
            GDELTCategoryList::SELF_IDENTIFIED_HUMANITARIAN_CRISIS(_) => 203,
            GDELTCategoryList::SEPARATISTS(_) => 204,
            GDELTCategoryList::SHORTAGE(_) => 205,
            GDELTCategoryList::SICKENED(_) => 206,
            GDELTCategoryList::SLFID_CAPACITY_BUILDING(_) => 207,
            GDELTCategoryList::SLFID_CIVIL_LIBERTIES(_) => 208,
            GDELTCategoryList::SLFID_DICTATORSHIP(_) => 209,
            GDELTCategoryList::SLFID_ECONOMIC_DEVELOPMENT(_) => 210,
            GDELTCategoryList::SLFID_ECONOMIC_POWER(_) => 211,
            GDELTCategoryList::SLFID_MILITARY_BUILDUP(_) => 212,
            GDELTCategoryList::SLFID_MILITARY_READINESS(_) => 213,
            GDELTCategoryList::SLFID_MILITARY_SPENDING(_) => 214,
            GDELTCategoryList::SLFID_MINERAL_RESOURCES(_) => 215,
            GDELTCategoryList::SLFID_NATURAL_RESOURCES(_) => 216,
            GDELTCategoryList::SLFID_PEACE_BUILDING(_) => 217,
            GDELTCategoryList::SLFID_POLITICAL_BOUNDARIES(_) => 218,
            GDELTCategoryList::SLFID_RULE_OF_LAW(_) => 219,
            GDELTCategoryList::SLUMS(_) => 220,
            GDELTCategoryList::SMUGGLING(_) => 221,
            GDELTCategoryList::SOC_DIPLOMCOOP(_) => 222,
            GDELTCategoryList::SOC_ECONCOOP(_) => 223,
            GDELTCategoryList::SOC_EXPRESSREGRET(_) => 224,
            GDELTCategoryList::SOC_EXPRESSSUPPORT(_) => 225,
            GDELTCategoryList::SOC_FORCEDRELOCATION(_) => 226,
            GDELTCategoryList::SOC_GENERALCRIME(_) => 227,
            GDELTCategoryList::SOC_INTELSHARING(_) => 228,
            GDELTCategoryList::SOC_JUDICIALCOOP(_) => 229,
            GDELTCategoryList::SOC_MASSMIGRATION(_) => 230,
            GDELTCategoryList::SOC_PARDON(_) => 231,
            GDELTCategoryList::SOC_SUICIDE(_) => 232,
            GDELTCategoryList::SOC_SUSPICIOUSACTIVITIES(_) => 233,
            GDELTCategoryList::SOC_SUSPICIOUSPEOPLE(_) => 234,
            GDELTCategoryList::SOC_TRAFFICACCIDENT(_) => 235,
            GDELTCategoryList::SOVEREIGNTY(_) => 236,
            GDELTCategoryList::STATE_OF_EMERGENCY(_) => 237,
            GDELTCategoryList::STRIKE(_) => 238,
            GDELTCategoryList::SUICIDE_ATTACK(_) => 239,
            GDELTCategoryList::SURVEILLANCE(_) => 240,
            GDELTCategoryList::TAKE_OFFICE(_) => 241,
            GDELTCategoryList::TAX_CARTELS(_) => 242,
            GDELTCategoryList::TAX_DISEASE(_) => 243,
            GDELTCategoryList::TAX_ETHNICITY(_) => 244,
            GDELTCategoryList::TAX_FNCACT(_) => 245,
            GDELTCategoryList::TAX_FOODSTAPLES(_) => 246,
            GDELTCategoryList::TAX_MILITARY_TITLE(_) => 247,
            GDELTCategoryList::TAX_POLITICAL_PARTY(_) => 248,
            GDELTCategoryList::TAX_RELIGION(_) => 249,
            GDELTCategoryList::TAX_SPECIAL_ISSUES(_) => 250,
            GDELTCategoryList::TAX_SPECIALDEATH(_) => 251,
            GDELTCategoryList::TAX_TERROR_GROUP(_) => 252,
            GDELTCategoryList::TAX_WEAPONS(_) => 253,
            GDELTCategoryList::TERROR(_) => 254,
            GDELTCategoryList::TORTURE(_) => 255,
            GDELTCategoryList::TOURISM(_) => 256,
            GDELTCategoryList::TRAFFIC(_) => 257,
            GDELTCategoryList::TRANSPARENCY(_) => 258,
            GDELTCategoryList::TREASON(_) => 259,
            GDELTCategoryList::TRIAL(_) => 260,
            GDELTCategoryList::UNEMPLOYMENT(_) => 261,
            GDELTCategoryList::UNGOVERNED(_) => 262,
            GDELTCategoryList::UNREST_CHECKPOINT(_) => 263,
            GDELTCategoryList::UNREST_CLOSINGBORDER(_) => 264,
            GDELTCategoryList::UNREST_HUNGERSTRIKE(_) => 265,
            GDELTCategoryList::UNREST_MOLOTOVCOCKTAIL(_) => 266,
            GDELTCategoryList::UNREST_POLICEBRUTALITY(_) => 267,
            GDELTCategoryList::UNREST_STONETHROWING(_) => 268,
            GDELTCategoryList::UNREST_STONING(_) => 269,
            GDELTCategoryList::UNSAFE_WORK_ENVIRONMENT(_) => 270,
            GDELTCategoryList::URBAN(_) => 271,
            GDELTCategoryList::URBAN_SPRAWL(_) => 272,
            GDELTCategoryList::VANDALIZE(_) => 273,
            GDELTCategoryList::VETO(_) => 274,
            GDELTCategoryList::VIOLENT_UNREST(_) => 275,
            GDELTCategoryList::WATER_SECURITY(_) => 276,
            GDELTCategoryList::WHISTLEBLOWER(_) => 277,
            GDELTCategoryList::WMD(_) => 278,
            GDELTCategoryList::WOUND(_) => 279,
        }
    }
}

/// The `GDELTObject` trait defines a method for creating an instance of a type from a string.
impl GDELTObject for GDELTCategoryList {
    /// Creates an instance of `GDELTCategoryList` from a string representation of its unique identifier.
    ///
    /// # Arguments
    ///
    /// * `record` - A string slice that holds the string representation of the unique identifier.
    ///
    /// # Returns
    ///
    /// An `Option<Self>` which is `Some` if the string can be parsed into a `u16` and converted to a `GDELTCategoryList`.
    /// Returns `None` if the parsing fails.
    fn from_strings(record: &str) -> Option<Self> {
        let split = record.split(",").collect::<Vec<&str>>();

        match split.len() {
            1 => match split.get(0) {
                None => None,
                Some(val) => match GDELTCategoryList::from_str(val) {
                    Ok(val) => Some(val),
                    Err(_) => None,
                },
            },
            2 => match split.get(1) {
                None => Some(GDELTCategoryList::from(record.parse::<u16>().ok()?)),
                Some(offset) => match offset.parse::<u64>() {
                    Ok(offset_u128) => {
                        let mut cat = match GDELTCategoryList::from_str(split.get(0)?) {
                            Ok(val) => GDELTCategoryList::from(val),
                            Err(_) => return None,
                        };
                        match cat {
                            GDELTCategoryList::UNKNOWN(ref val1)
                            | GDELTCategoryList::AFFECT(ref val1)
                            | GDELTCategoryList::AGRICULTURE(ref val1)
                            | GDELTCategoryList::ALLIANCE(ref val1)
                            | GDELTCategoryList::APPOINTMENT(ref val1)
                            | GDELTCategoryList::ARMEDCONFLICT(ref val1)
                            | GDELTCategoryList::ARREST(ref val1)
                            | GDELTCategoryList::ASSASSINATION(ref val1)
                            | GDELTCategoryList::AUSTERITY(ref val1)
                            | GDELTCategoryList::AVIATION_INCIDENT(ref val1)
                            | GDELTCategoryList::BAN(ref val1)
                            | GDELTCategoryList::BLACK_MARKET(ref val1)
                            | GDELTCategoryList::BLOCKADE(ref val1)
                            | GDELTCategoryList::BORDER(ref val1)
                            | GDELTCategoryList::BULLYING(ref val1)
                            | GDELTCategoryList::CEASEFIRE(ref val1)
                            | GDELTCategoryList::CHARASMATIC_LEADERSHIP(ref val1)
                            | GDELTCategoryList::CHECKPOINT(ref val1)
                            | GDELTCategoryList::CLAIM_CREDIT(ref val1)
                            | GDELTCategoryList::CLOSURE(ref val1)
                            | GDELTCategoryList::CONFISCATION(ref val1)
                            | GDELTCategoryList::CONSTITUTIONAL(ref val1)
                            | GDELTCategoryList::CORRUPTION(ref val1)
                            | GDELTCategoryList::CRIME_CARTELS(ref val1)
                            | GDELTCategoryList::CRIME_COMMON_ROBBERY(ref val1)
                            | GDELTCategoryList::CRIME_ILLEGAL_DRUGS(ref val1)
                            | GDELTCategoryList::CURFEW(ref val1)
                            | GDELTCategoryList::CYBER_ATTACK(ref val1)
                            | GDELTCategoryList::DEATH_PENALTY(ref val1)
                            | GDELTCategoryList::DEFECTION(ref val1)
                            | GDELTCategoryList::DELAY(ref val1)
                            | GDELTCategoryList::DEMOCRACY(ref val1)
                            | GDELTCategoryList::DISABILITY(ref val1)
                            | GDELTCategoryList::DISCRIMINATION(ref val1)
                            | GDELTCategoryList::DISPLACED(ref val1)
                            | GDELTCategoryList::DRONE(ref val1)
                            | GDELTCategoryList::DRUG_TRADE(ref val1)
                            | GDELTCategoryList::ECON_BANKRUPTCY(ref val1)
                            | GDELTCategoryList::ECON_BOYCOTT(ref val1)
                            | GDELTCategoryList::ECON_COST_OF_LIVING(ref val1)
                            | GDELTCategoryList::ECON_CURRENCY_EXCHANGE_RATE(ref val1)
                            | GDELTCategoryList::ECON_CURRENCY_RESERVES(ref val1)
                            | GDELTCategoryList::ECON_CUTOUTLOOK(ref val1)
                            | GDELTCategoryList::ECON_DEBT(ref val1)
                            | GDELTCategoryList::ECON_DEREGULATION(ref val1)
                            | GDELTCategoryList::ECON_EARNINGSREPORT(ref val1)
                            | GDELTCategoryList::ECON_ENTREPRENEURSHIP(ref val1)
                            | GDELTCategoryList::ECON_FOREIGNINVEST(ref val1)
                            | GDELTCategoryList::ECON_FREETRADE(ref val1)
                            | GDELTCategoryList::ECON_HOUSING_PRICES(ref val1)
                            | GDELTCategoryList::ECON_INFORMAL_ECONOMY(ref val1)
                            | GDELTCategoryList::ECON_INTEREST_RATES(ref val1)
                            | GDELTCategoryList::ECON_IPO(ref val1)
                            | GDELTCategoryList::ECON_MONOPOLY(ref val1)
                            | GDELTCategoryList::ECON_MOU(ref val1)
                            | GDELTCategoryList::ECON_NATIONALIZE(ref val1)
                            | GDELTCategoryList::ECON_PRICECONTROL(ref val1)
                            | GDELTCategoryList::ECON_REMITTANCE(ref val1)
                            | GDELTCategoryList::ECON_STOCKMARKET(ref val1)
                            | GDELTCategoryList::ECON_SUBSIDIES(ref val1)
                            | GDELTCategoryList::ECON_TAXATION(ref val1)
                            | GDELTCategoryList::ECON_TRADE_DISPUTE(ref val1)
                            | GDELTCategoryList::ECON_UNIONS(ref val1)
                            | GDELTCategoryList::EDUCATION(ref val1)
                            | GDELTCategoryList::ELECTION(ref val1)
                            | GDELTCategoryList::ELECTION_FRAUD(ref val1)
                            | GDELTCategoryList::ENV_BIOFUEL(ref val1)
                            | GDELTCategoryList::ENV_CARBONCAPTURE(ref val1)
                            | GDELTCategoryList::ENV_CLIMATECHANGE(ref val1)
                            | GDELTCategoryList::ENV_COAL(ref val1)
                            | GDELTCategoryList::ENV_DEFORESTATION(ref val1)
                            | GDELTCategoryList::ENV_FISHERY(ref val1)
                            | GDELTCategoryList::ENV_FORESTRY(ref val1)
                            | GDELTCategoryList::ENV_GEOTHERMAL(ref val1)
                            | GDELTCategoryList::ENV_GREEN(ref val1)
                            | GDELTCategoryList::ENV_HYDRO(ref val1)
                            | GDELTCategoryList::ENV_METALS(ref val1)
                            | GDELTCategoryList::ENV_MINING(ref val1)
                            | GDELTCategoryList::ENV_NATURALGAS(ref val1)
                            | GDELTCategoryList::ENV_NUCLEARPOWER(ref val1)
                            | GDELTCategoryList::ENV_OIL(ref val1)
                            | GDELTCategoryList::ENV_OVERFISH(ref val1)
                            | GDELTCategoryList::ENV_POACHING(ref val1)
                            | GDELTCategoryList::ENV_SOLAR(ref val1)
                            | GDELTCategoryList::ENV_SPECIESENDANGERED(ref val1)
                            | GDELTCategoryList::ENV_SPECIESEXTINCT(ref val1)
                            | GDELTCategoryList::ENV_WATERWAYS(ref val1)
                            | GDELTCategoryList::ENV_WINDPOWER(ref val1)
                            | GDELTCategoryList::ETH_INDIGINOUS(ref val1)
                            | GDELTCategoryList::EVACUATION(ref val1)
                            | GDELTCategoryList::EXHUMATION(ref val1)
                            | GDELTCategoryList::EXILE(ref val1)
                            | GDELTCategoryList::EXTREMISM(ref val1)
                            | GDELTCategoryList::FIREARM_OWNERSHIP(ref val1)
                            | GDELTCategoryList::FOOD_SECURITY(ref val1)
                            | GDELTCategoryList::FOOD_STAPLE(ref val1)
                            | GDELTCategoryList::FREESPEECH(ref val1)
                            | GDELTCategoryList::FUELPRICES(ref val1)
                            | GDELTCategoryList::GEN_HOLIDAY(ref val1)
                            | GDELTCategoryList::GENDER_VIOLENCE(ref val1)
                            | GDELTCategoryList::GENERAL_GOVERNMENT(ref val1)
                            | GDELTCategoryList::GENERAL_HEALTH(ref val1)
                            | GDELTCategoryList::GENTRIFICATION(ref val1)
                            | GDELTCategoryList::GOV_DISSOLVEGOV(ref val1)
                            | GDELTCategoryList::GOV_DIVISIONOFPOWER(ref val1)
                            | GDELTCategoryList::GOV_INTERGOVERNMENTAL(ref val1)
                            | GDELTCategoryList::GOV_REFORM(ref val1)
                            | GDELTCategoryList::GOV_REPATRIATION(ref val1)
                            | GDELTCategoryList::GRIEVANCES(ref val1)
                            | GDELTCategoryList::HARASSMENT(ref val1)
                            | GDELTCategoryList::HATE_SPEECH(ref val1)
                            | GDELTCategoryList::HEALTH_PANDEMIC(ref val1)
                            | GDELTCategoryList::HEALTH_SEXTRANSDISEASE(ref val1)
                            | GDELTCategoryList::HEALTH_VACCINATION(ref val1)
                            | GDELTCategoryList::HUMAN_TRAFFICKING(ref val1)
                            | GDELTCategoryList::IDEOLOGY(ref val1)
                            | GDELTCategoryList::IMMIGRATION(ref val1)
                            | GDELTCategoryList::IMPEACHMENT(ref val1)
                            | GDELTCategoryList::INFO_HOAX(ref val1)
                            | GDELTCategoryList::INFO_RUMOR(ref val1)
                            | GDELTCategoryList::INFRASTRUCTURE_BAD_ROADS(ref val1)
                            | GDELTCategoryList::INSURGENCY(ref val1)
                            | GDELTCategoryList::INTERNET_BLACKOUT(ref val1)
                            | GDELTCategoryList::INTERNET_CENSORSHIP(ref val1)
                            | GDELTCategoryList::JIHAD(ref val1)
                            | GDELTCategoryList::KIDNAP(ref val1)
                            | GDELTCategoryList::KILL(ref val1)
                            | GDELTCategoryList::LANDMINE(ref val1)
                            | GDELTCategoryList::LEADER(ref val1)
                            | GDELTCategoryList::LEGALIZE(ref val1)
                            | GDELTCategoryList::LEGISLATION(ref val1)
                            | GDELTCategoryList::LGBT(ref val1)
                            | GDELTCategoryList::LITERACY(ref val1)
                            | GDELTCategoryList::LOCUSTS(ref val1)
                            | GDELTCategoryList::MANMADE_DISASTER(ref val1)
                            | GDELTCategoryList::MANMADE_DISASTER_IMPLIED(ref val1)
                            | GDELTCategoryList::MARITIME(ref val1)
                            | GDELTCategoryList::MARITIME_INCIDENT(ref val1)
                            | GDELTCategoryList::MARITIME_INCIDENT_IMPLIED(ref val1)
                            | GDELTCategoryList::MARITIME_INCIDENT_SELF_IDENTIFIED(ref val1)
                            | GDELTCategoryList::MARITIME_PIRACY(ref val1)
                            | GDELTCategoryList::MEDIA_CENSORSHIP(ref val1)
                            | GDELTCategoryList::MEDIA_MSM(ref val1)
                            | GDELTCategoryList::MEDIA_SOCIAL(ref val1)
                            | GDELTCategoryList::MEDICAL(ref val1)
                            | GDELTCategoryList::MEDICAL_SECURITY(ref val1)
                            | GDELTCategoryList::MIL_SELF_IDENTIFIED_ARMS_DEAL(ref val1)
                            | GDELTCategoryList::MIL_WEAPONS_PROLIFERATION(ref val1)
                            | GDELTCategoryList::MILITARY(ref val1)
                            | GDELTCategoryList::MILITARY_COOPERATION(ref val1)
                            | GDELTCategoryList::MOVEMENT_ENVIRONMENTAL(ref val1)
                            | GDELTCategoryList::MOVEMENT_GENERAL(ref val1)
                            | GDELTCategoryList::MOVEMENT_OTHER(ref val1)
                            | GDELTCategoryList::MOVEMENT_SOCIAL(ref val1)
                            | GDELTCategoryList::MOVEMENT_WOMENS(ref val1)
                            | GDELTCategoryList::NATURAL_DISASTER(ref val1)
                            | GDELTCategoryList::NEGOTIATIONS(ref val1)
                            | GDELTCategoryList::NEW_CONSTRUCTION(ref val1)
                            | GDELTCategoryList::ORGANIZED_CRIME(ref val1)
                            | GDELTCategoryList::PEACEKEEPING(ref val1)
                            | GDELTCategoryList::PERSECUTION(ref val1)
                            | GDELTCategoryList::PHONE_OUTAGE(ref val1)
                            | GDELTCategoryList::PIPELINE_INCIDENT(ref val1)
                            | GDELTCategoryList::PIRACY(ref val1)
                            | GDELTCategoryList::POL_HOSTVISIT(ref val1)
                            | GDELTCategoryList::POLITICAL_PRISONER(ref val1)
                            | GDELTCategoryList::POLITICAL_TURMOIL(ref val1)
                            | GDELTCategoryList::POPULATION_DENSITY(ref val1)
                            | GDELTCategoryList::POVERTY(ref val1)
                            | GDELTCategoryList::POWER_OUTAGE(ref val1)
                            | GDELTCategoryList::PRIVATIZATION(ref val1)
                            | GDELTCategoryList::PROPAGANDA(ref val1)
                            | GDELTCategoryList::PROPERTY_RIGHTS(ref val1)
                            | GDELTCategoryList::PROTEST(ref val1)
                            | GDELTCategoryList::PUBLIC_TRANSPORT(ref val1)
                            | GDELTCategoryList::RAIL_INCIDENT(ref val1)
                            | GDELTCategoryList::RAPE(ref val1)
                            | GDELTCategoryList::RATIFY(ref val1)
                            | GDELTCategoryList::REBELLION(ref val1)
                            | GDELTCategoryList::REBELS(ref val1)
                            | GDELTCategoryList::RECRUITMENT(ref val1)
                            | GDELTCategoryList::REFUGEES(ref val1)
                            | GDELTCategoryList::REL_ANTISEMITISM(ref val1)
                            | GDELTCategoryList::RELATIONS(ref val1)
                            | GDELTCategoryList::RELEASE_HOSTAGE(ref val1)
                            | GDELTCategoryList::RELEASE_PRISON(ref val1)
                            | GDELTCategoryList::RELIGION(ref val1)
                            | GDELTCategoryList::RESIGNATION(ref val1)
                            | GDELTCategoryList::RETALIATE(ref val1)
                            | GDELTCategoryList::RETIREMENT(ref val1)
                            | GDELTCategoryList::RETIREMENTS(ref val1)
                            | GDELTCategoryList::ROAD_INCIDENT(ref val1)
                            | GDELTCategoryList::RURAL(ref val1)
                            | GDELTCategoryList::SANCTIONS(ref val1)
                            | GDELTCategoryList::SANITATION(ref val1)
                            | GDELTCategoryList::SCANDAL(ref val1)
                            | GDELTCategoryList::SCIENCE(ref val1)
                            | GDELTCategoryList::SECURITY_SERVICES(ref val1)
                            | GDELTCategoryList::SEIGE(ref val1)
                            | GDELTCategoryList::SEIZE(ref val1)
                            | GDELTCategoryList::SELF_IDENTIFIED_ATROCITY(ref val1)
                            | GDELTCategoryList::SELF_IDENTIFIED_ENVIRON_DISASTER(ref val1)
                            | GDELTCategoryList::SELF_IDENTIFIED_HUMAN_RIGHTS(ref val1)
                            | GDELTCategoryList::SELF_IDENTIFIED_HUMANITARIAN_CRISIS(ref val1)
                            | GDELTCategoryList::SEPARATISTS(ref val1)
                            | GDELTCategoryList::SHORTAGE(ref val1)
                            | GDELTCategoryList::SICKENED(ref val1)
                            | GDELTCategoryList::SLFID_CAPACITY_BUILDING(ref val1)
                            | GDELTCategoryList::SLFID_CIVIL_LIBERTIES(ref val1)
                            | GDELTCategoryList::SLFID_DICTATORSHIP(ref val1)
                            | GDELTCategoryList::SLFID_ECONOMIC_DEVELOPMENT(ref val1)
                            | GDELTCategoryList::SLFID_ECONOMIC_POWER(ref val1)
                            | GDELTCategoryList::SLFID_MILITARY_BUILDUP(ref val1)
                            | GDELTCategoryList::SLFID_MILITARY_READINESS(ref val1)
                            | GDELTCategoryList::SLFID_MILITARY_SPENDING(ref val1)
                            | GDELTCategoryList::SLFID_MINERAL_RESOURCES(ref val1)
                            | GDELTCategoryList::SLFID_NATURAL_RESOURCES(ref val1)
                            | GDELTCategoryList::SLFID_PEACE_BUILDING(ref val1)
                            | GDELTCategoryList::SLFID_POLITICAL_BOUNDARIES(ref val1)
                            | GDELTCategoryList::SLFID_RULE_OF_LAW(ref val1)
                            | GDELTCategoryList::SLUMS(ref val1)
                            | GDELTCategoryList::SMUGGLING(ref val1)
                            | GDELTCategoryList::SOC_DIPLOMCOOP(ref val1)
                            | GDELTCategoryList::SOC_ECONCOOP(ref val1)
                            | GDELTCategoryList::SOC_EXPRESSREGRET(ref val1)
                            | GDELTCategoryList::SOC_EXPRESSSUPPORT(ref val1)
                            | GDELTCategoryList::SOC_FORCEDRELOCATION(ref val1)
                            | GDELTCategoryList::SOC_GENERALCRIME(ref val1)
                            | GDELTCategoryList::SOC_INTELSHARING(ref val1)
                            | GDELTCategoryList::SOC_JUDICIALCOOP(ref val1)
                            | GDELTCategoryList::SOC_MASSMIGRATION(ref val1)
                            | GDELTCategoryList::SOC_PARDON(ref val1)
                            | GDELTCategoryList::SOC_SUICIDE(ref val1)
                            | GDELTCategoryList::SOC_SUSPICIOUSACTIVITIES(ref val1)
                            | GDELTCategoryList::SOC_SUSPICIOUSPEOPLE(ref val1)
                            | GDELTCategoryList::SOC_TRAFFICACCIDENT(ref val1)
                            | GDELTCategoryList::SOVEREIGNTY(ref val1)
                            | GDELTCategoryList::STATE_OF_EMERGENCY(ref val1)
                            | GDELTCategoryList::STRIKE(ref val1)
                            | GDELTCategoryList::SUICIDE_ATTACK(ref val1)
                            | GDELTCategoryList::SURVEILLANCE(ref val1)
                            | GDELTCategoryList::TAKE_OFFICE(ref val1)
                            | GDELTCategoryList::TAX_CARTELS(ref val1)
                            | GDELTCategoryList::TAX_DISEASE(ref val1)
                            | GDELTCategoryList::TAX_ETHNICITY(ref val1)
                            | GDELTCategoryList::TAX_FNCACT(ref val1)
                            | GDELTCategoryList::TAX_FOODSTAPLES(ref val1)
                            | GDELTCategoryList::TAX_MILITARY_TITLE(ref val1)
                            | GDELTCategoryList::TAX_POLITICAL_PARTY(ref val1)
                            | GDELTCategoryList::TAX_RELIGION(ref val1)
                            | GDELTCategoryList::TAX_SPECIAL_ISSUES(ref val1)
                            | GDELTCategoryList::TAX_SPECIALDEATH(ref val1)
                            | GDELTCategoryList::TAX_TERROR_GROUP(ref val1)
                            | GDELTCategoryList::TAX_WEAPONS(ref val1)
                            | GDELTCategoryList::TERROR(ref val1)
                            | GDELTCategoryList::TORTURE(ref val1)
                            | GDELTCategoryList::TOURISM(ref val1)
                            | GDELTCategoryList::TRAFFIC(ref val1)
                            | GDELTCategoryList::TRANSPARENCY(ref val1)
                            | GDELTCategoryList::TREASON(ref val1)
                            | GDELTCategoryList::TRIAL(ref val1)
                            | GDELTCategoryList::UNEMPLOYMENT(ref val1)
                            | GDELTCategoryList::UNGOVERNED(ref val1)
                            | GDELTCategoryList::UNREST_CHECKPOINT(ref val1)
                            | GDELTCategoryList::UNREST_CLOSINGBORDER(ref val1)
                            | GDELTCategoryList::UNREST_HUNGERSTRIKE(ref val1)
                            | GDELTCategoryList::UNREST_MOLOTOVCOCKTAIL(ref val1)
                            | GDELTCategoryList::UNREST_POLICEBRUTALITY(ref val1)
                            | GDELTCategoryList::UNREST_STONETHROWING(ref val1)
                            | GDELTCategoryList::UNREST_STONING(ref val1)
                            | GDELTCategoryList::UNSAFE_WORK_ENVIRONMENT(ref val1)
                            | GDELTCategoryList::URBAN(ref val1)
                            | GDELTCategoryList::URBAN_SPRAWL(ref val1)
                            | GDELTCategoryList::VANDALIZE(ref val1)
                            | GDELTCategoryList::VETO(ref val1)
                            | GDELTCategoryList::VIOLENT_UNREST(ref val1)
                            | GDELTCategoryList::WATER_SECURITY(ref val1)
                            | GDELTCategoryList::WHISTLEBLOWER(ref val1)
                            | GDELTCategoryList::WMD(ref val1)
                            | GDELTCategoryList::WOUND(ref val1) => {
                                *val1.borrow_mut() = offset_u128;
                            }
                        }
                        Some(cat)
                    }
                    Err(_) => None,
                },
            },
            _ => None,
        }
    }
    
    /// Creates a new instance of `GDELTCategoryList` from a vector of string slices.
    ///
    /// # Arguments
    ///
    /// * `fields` - A vector of string slices representing the fields to be parsed into a `GDELTCategoryList`.
    ///
    /// # Returns
    ///
    /// * `Option<Self>` - Returns `Some(GDELTCategoryList)` if the first field can be successfully parsed into a `GDELTCategoryList`.
    ///   Returns `None` if the first field is empty or if parsing fails.
    fn new(fields: Vec<&str>) -> Option<Self> {
        match fields.get(0) {
            // If the first field is empty or not present, return None.
            Some(&"") | None => None,
            // If the first field is present, attempt to parse it into a GDELTCategoryList.
            Some(value) => GDELTCategoryList::from_strings(value),
        }
    }
}

/// Implementation of the `CellItem` trait for the `GDELTCategoryList` enum.
impl CellItem for GDELTCategoryList {
    /// Converts a delimited string into a vector of `GDELTCategoryList` items.
    ///
    /// # Arguments
    ///
    /// * `string` - A string slice containing the delimited items to be converted.
    ///
    /// # Returns
    ///
    /// * `Option<Vec<Self>>` - Returns `Some(Vec<GDELTCategoryList>)` if the conversion is successful.
    ///   Returns `None` if the conversion fails or if the resulting vector is empty.
    fn vec_from_cell(string: &str) -> Option<Vec<Self>> {
        // Split the input string into a vector of items using the delimiter ";"
        let list_of_items = <Self as GDELTObject>::delimited_vector(";", string);

        // Flag to determine if the items are in version 2 format (contain a comma)
        let mut is_v2 = false;

        // Check if the first item contains a comma to set the version flag
        if list_of_items[0].contains(",") {
            is_v2 = true;
        }

        // Initialize an empty vector to store the resulting `GDELTCategoryList` items
        let mut result = Vec::new();

        // Iterate over each item in the list
        for item in list_of_items {
            if is_v2 {
                // If the item is in version 2 format, attempt to convert it to `GDELTCategoryList`
                if let Some(category) = GDELTCategoryList::from_strings(item) {
                    result.push(category);
                }
            } else {
                // If the item is not in version 2 format, attempt to convert it to `GDELTCategoryList`
                if let Some(category) = GDELTCategoryList::from_strings(item) {
                    result.push(category);
                }
            }
        }

        // Return `None` if the result vector is empty, otherwise return the result vector wrapped in `Some`
        if result.is_empty() {
            None
        } else {
            Some(result)
        }
    }
}

/// The `GDELTCategoryList` enum represents various categories in the GDELT dataset.
/// Each variant corresponds to a specific category with a unique identifier.
impl GDELTCategoryList {
    /// Returns the unique identifier associated with the `GDELTCategoryList` variant.
    ///
    /// # Returns
    ///
    /// A `u16` value representing the unique identifier of the category.
    pub fn value(&self) -> u16 {
        u16::from(self.clone())
    }

    /// Extracts the inner `u64` value from a `GDELTCategoryList` variant.
    ///
    /// # Arguments
    ///
    /// * `value` - A `GDELTCategoryList` variant from which the inner value is to be extracted.
    ///
    /// # Returns
    ///
    /// * `Option<u64>` - Returns `Some(u64)` containing the inner value if the variant contains one.
    ///   Returns `None` if the variant does not contain an inner value.
    pub(crate) fn extract_value(value: GDELTCategoryList) -> Option<u64> {
        match value {
            GDELTCategoryList::UNKNOWN(ref val1)
            | GDELTCategoryList::AFFECT(ref val1)
            | GDELTCategoryList::AGRICULTURE(ref val1)
            | GDELTCategoryList::ALLIANCE(ref val1)
            | GDELTCategoryList::APPOINTMENT(ref val1)
            | GDELTCategoryList::ARMEDCONFLICT(ref val1)
            | GDELTCategoryList::ARREST(ref val1)
            | GDELTCategoryList::ASSASSINATION(ref val1)
            | GDELTCategoryList::AUSTERITY(ref val1)
            | GDELTCategoryList::AVIATION_INCIDENT(ref val1)
            | GDELTCategoryList::BAN(ref val1)
            | GDELTCategoryList::BLACK_MARKET(ref val1)
            | GDELTCategoryList::BLOCKADE(ref val1)
            | GDELTCategoryList::BORDER(ref val1)
            | GDELTCategoryList::BULLYING(ref val1)
            | GDELTCategoryList::CEASEFIRE(ref val1)
            | GDELTCategoryList::CHARASMATIC_LEADERSHIP(ref val1)
            | GDELTCategoryList::CHECKPOINT(ref val1)
            | GDELTCategoryList::CLAIM_CREDIT(ref val1)
            | GDELTCategoryList::CLOSURE(ref val1)
            | GDELTCategoryList::CONFISCATION(ref val1)
            | GDELTCategoryList::CONSTITUTIONAL(ref val1)
            | GDELTCategoryList::CORRUPTION(ref val1)
            | GDELTCategoryList::CRIME_CARTELS(ref val1)
            | GDELTCategoryList::CRIME_COMMON_ROBBERY(ref val1)
            | GDELTCategoryList::CRIME_ILLEGAL_DRUGS(ref val1)
            | GDELTCategoryList::CURFEW(ref val1)
            | GDELTCategoryList::CYBER_ATTACK(ref val1)
            | GDELTCategoryList::DEATH_PENALTY(ref val1)
            | GDELTCategoryList::DEFECTION(ref val1)
            | GDELTCategoryList::DELAY(ref val1)
            | GDELTCategoryList::DEMOCRACY(ref val1)
            | GDELTCategoryList::DISABILITY(ref val1)
            | GDELTCategoryList::DISCRIMINATION(ref val1)
            | GDELTCategoryList::DISPLACED(ref val1)
            | GDELTCategoryList::DRONE(ref val1)
            | GDELTCategoryList::DRUG_TRADE(ref val1)
            | GDELTCategoryList::ECON_BANKRUPTCY(ref val1)
            | GDELTCategoryList::ECON_BOYCOTT(ref val1)
            | GDELTCategoryList::ECON_COST_OF_LIVING(ref val1)
            | GDELTCategoryList::ECON_CURRENCY_EXCHANGE_RATE(ref val1)
            | GDELTCategoryList::ECON_CURRENCY_RESERVES(ref val1)
            | GDELTCategoryList::ECON_CUTOUTLOOK(ref val1)
            | GDELTCategoryList::ECON_DEBT(ref val1)
            | GDELTCategoryList::ECON_DEREGULATION(ref val1)
            | GDELTCategoryList::ECON_EARNINGSREPORT(ref val1)
            | GDELTCategoryList::ECON_ENTREPRENEURSHIP(ref val1)
            | GDELTCategoryList::ECON_FOREIGNINVEST(ref val1)
            | GDELTCategoryList::ECON_FREETRADE(ref val1)
            | GDELTCategoryList::ECON_HOUSING_PRICES(ref val1)
            | GDELTCategoryList::ECON_INFORMAL_ECONOMY(ref val1)
            | GDELTCategoryList::ECON_INTEREST_RATES(ref val1)
            | GDELTCategoryList::ECON_IPO(ref val1)
            | GDELTCategoryList::ECON_MONOPOLY(ref val1)
            | GDELTCategoryList::ECON_MOU(ref val1)
            | GDELTCategoryList::ECON_NATIONALIZE(ref val1)
            | GDELTCategoryList::ECON_PRICECONTROL(ref val1)
            | GDELTCategoryList::ECON_REMITTANCE(ref val1)
            | GDELTCategoryList::ECON_STOCKMARKET(ref val1)
            | GDELTCategoryList::ECON_SUBSIDIES(ref val1)
            | GDELTCategoryList::ECON_TAXATION(ref val1)
            | GDELTCategoryList::ECON_TRADE_DISPUTE(ref val1)
            | GDELTCategoryList::ECON_UNIONS(ref val1)
            | GDELTCategoryList::EDUCATION(ref val1)
            | GDELTCategoryList::ELECTION(ref val1)
            | GDELTCategoryList::ELECTION_FRAUD(ref val1)
            | GDELTCategoryList::ENV_BIOFUEL(ref val1)
            | GDELTCategoryList::ENV_CARBONCAPTURE(ref val1)
            | GDELTCategoryList::ENV_CLIMATECHANGE(ref val1)
            | GDELTCategoryList::ENV_COAL(ref val1)
            | GDELTCategoryList::ENV_DEFORESTATION(ref val1)
            | GDELTCategoryList::ENV_FISHERY(ref val1)
            | GDELTCategoryList::ENV_FORESTRY(ref val1)
            | GDELTCategoryList::ENV_GEOTHERMAL(ref val1)
            | GDELTCategoryList::ENV_GREEN(ref val1)
            | GDELTCategoryList::ENV_HYDRO(ref val1)
            | GDELTCategoryList::ENV_METALS(ref val1)
            | GDELTCategoryList::ENV_MINING(ref val1)
            | GDELTCategoryList::ENV_NATURALGAS(ref val1)
            | GDELTCategoryList::ENV_NUCLEARPOWER(ref val1)
            | GDELTCategoryList::ENV_OIL(ref val1)
            | GDELTCategoryList::ENV_OVERFISH(ref val1)
            | GDELTCategoryList::ENV_POACHING(ref val1)
            | GDELTCategoryList::ENV_SOLAR(ref val1)
            | GDELTCategoryList::ENV_SPECIESENDANGERED(ref val1)
            | GDELTCategoryList::ENV_SPECIESEXTINCT(ref val1)
            | GDELTCategoryList::ENV_WATERWAYS(ref val1)
            | GDELTCategoryList::ENV_WINDPOWER(ref val1)
            | GDELTCategoryList::ETH_INDIGINOUS(ref val1)
            | GDELTCategoryList::EVACUATION(ref val1)
            | GDELTCategoryList::EXHUMATION(ref val1)
            | GDELTCategoryList::EXILE(ref val1)
            | GDELTCategoryList::EXTREMISM(ref val1)
            | GDELTCategoryList::FIREARM_OWNERSHIP(ref val1)
            | GDELTCategoryList::FOOD_SECURITY(ref val1)
            | GDELTCategoryList::FOOD_STAPLE(ref val1)
            | GDELTCategoryList::FREESPEECH(ref val1)
            | GDELTCategoryList::FUELPRICES(ref val1)
            | GDELTCategoryList::GEN_HOLIDAY(ref val1)
            | GDELTCategoryList::GENDER_VIOLENCE(ref val1)
            | GDELTCategoryList::GENERAL_GOVERNMENT(ref val1)
            | GDELTCategoryList::GENERAL_HEALTH(ref val1)
            | GDELTCategoryList::GENTRIFICATION(ref val1)
            | GDELTCategoryList::GOV_DISSOLVEGOV(ref val1)
            | GDELTCategoryList::GOV_DIVISIONOFPOWER(ref val1)
            | GDELTCategoryList::GOV_INTERGOVERNMENTAL(ref val1)
            | GDELTCategoryList::GOV_REFORM(ref val1)
            | GDELTCategoryList::GOV_REPATRIATION(ref val1)
            | GDELTCategoryList::GRIEVANCES(ref val1)
            | GDELTCategoryList::HARASSMENT(ref val1)
            | GDELTCategoryList::HATE_SPEECH(ref val1)
            | GDELTCategoryList::HEALTH_PANDEMIC(ref val1)
            | GDELTCategoryList::HEALTH_SEXTRANSDISEASE(ref val1)
            | GDELTCategoryList::HEALTH_VACCINATION(ref val1)
            | GDELTCategoryList::HUMAN_TRAFFICKING(ref val1)
            | GDELTCategoryList::IDEOLOGY(ref val1)
            | GDELTCategoryList::IMMIGRATION(ref val1)
            | GDELTCategoryList::IMPEACHMENT(ref val1)
            | GDELTCategoryList::INFO_HOAX(ref val1)
            | GDELTCategoryList::INFO_RUMOR(ref val1)
            | GDELTCategoryList::INFRASTRUCTURE_BAD_ROADS(ref val1)
            | GDELTCategoryList::INSURGENCY(ref val1)
            | GDELTCategoryList::INTERNET_BLACKOUT(ref val1)
            | GDELTCategoryList::INTERNET_CENSORSHIP(ref val1)
            | GDELTCategoryList::JIHAD(ref val1)
            | GDELTCategoryList::KIDNAP(ref val1)
            | GDELTCategoryList::KILL(ref val1)
            | GDELTCategoryList::LANDMINE(ref val1)
            | GDELTCategoryList::LEADER(ref val1)
            | GDELTCategoryList::LEGALIZE(ref val1)
            | GDELTCategoryList::LEGISLATION(ref val1)
            | GDELTCategoryList::LGBT(ref val1)
            | GDELTCategoryList::LITERACY(ref val1)
            | GDELTCategoryList::LOCUSTS(ref val1)
            | GDELTCategoryList::MANMADE_DISASTER(ref val1)
            | GDELTCategoryList::MANMADE_DISASTER_IMPLIED(ref val1)
            | GDELTCategoryList::MARITIME(ref val1)
            | GDELTCategoryList::MARITIME_INCIDENT(ref val1)
            | GDELTCategoryList::MARITIME_INCIDENT_IMPLIED(ref val1)
            | GDELTCategoryList::MARITIME_INCIDENT_SELF_IDENTIFIED(ref val1)
            | GDELTCategoryList::MARITIME_PIRACY(ref val1)
            | GDELTCategoryList::MEDIA_CENSORSHIP(ref val1)
            | GDELTCategoryList::MEDIA_MSM(ref val1)
            | GDELTCategoryList::MEDIA_SOCIAL(ref val1)
            | GDELTCategoryList::MEDICAL(ref val1)
            | GDELTCategoryList::MEDICAL_SECURITY(ref val1)
            | GDELTCategoryList::MIL_SELF_IDENTIFIED_ARMS_DEAL(ref val1)
            | GDELTCategoryList::MIL_WEAPONS_PROLIFERATION(ref val1)
            | GDELTCategoryList::MILITARY(ref val1)
            | GDELTCategoryList::MILITARY_COOPERATION(ref val1)
            | GDELTCategoryList::MOVEMENT_ENVIRONMENTAL(ref val1)
            | GDELTCategoryList::MOVEMENT_GENERAL(ref val1)
            | GDELTCategoryList::MOVEMENT_OTHER(ref val1)
            | GDELTCategoryList::MOVEMENT_SOCIAL(ref val1)
            | GDELTCategoryList::MOVEMENT_WOMENS(ref val1)
            | GDELTCategoryList::NATURAL_DISASTER(ref val1)
            | GDELTCategoryList::NEGOTIATIONS(ref val1)
            | GDELTCategoryList::NEW_CONSTRUCTION(ref val1)
            | GDELTCategoryList::ORGANIZED_CRIME(ref val1)
            | GDELTCategoryList::PEACEKEEPING(ref val1)
            | GDELTCategoryList::PERSECUTION(ref val1)
            | GDELTCategoryList::PHONE_OUTAGE(ref val1)
            | GDELTCategoryList::PIPELINE_INCIDENT(ref val1)
            | GDELTCategoryList::PIRACY(ref val1)
            | GDELTCategoryList::POL_HOSTVISIT(ref val1)
            | GDELTCategoryList::POLITICAL_PRISONER(ref val1)
            | GDELTCategoryList::POLITICAL_TURMOIL(ref val1)
            | GDELTCategoryList::POPULATION_DENSITY(ref val1)
            | GDELTCategoryList::POVERTY(ref val1)
            | GDELTCategoryList::POWER_OUTAGE(ref val1)
            | GDELTCategoryList::PRIVATIZATION(ref val1)
            | GDELTCategoryList::PROPAGANDA(ref val1)
            | GDELTCategoryList::PROPERTY_RIGHTS(ref val1)
            | GDELTCategoryList::PROTEST(ref val1)
            | GDELTCategoryList::PUBLIC_TRANSPORT(ref val1)
            | GDELTCategoryList::RAIL_INCIDENT(ref val1)
            | GDELTCategoryList::RAPE(ref val1)
            | GDELTCategoryList::RATIFY(ref val1)
            | GDELTCategoryList::REBELLION(ref val1)
            | GDELTCategoryList::REBELS(ref val1)
            | GDELTCategoryList::RECRUITMENT(ref val1)
            | GDELTCategoryList::REFUGEES(ref val1)
            | GDELTCategoryList::REL_ANTISEMITISM(ref val1)
            | GDELTCategoryList::RELATIONS(ref val1)
            | GDELTCategoryList::RELEASE_HOSTAGE(ref val1)
            | GDELTCategoryList::RELEASE_PRISON(ref val1)
            | GDELTCategoryList::RELIGION(ref val1)
            | GDELTCategoryList::RESIGNATION(ref val1)
            | GDELTCategoryList::RETALIATE(ref val1)
            | GDELTCategoryList::RETIREMENT(ref val1)
            | GDELTCategoryList::RETIREMENTS(ref val1)
            | GDELTCategoryList::ROAD_INCIDENT(ref val1)
            | GDELTCategoryList::RURAL(ref val1)
            | GDELTCategoryList::SANCTIONS(ref val1)
            | GDELTCategoryList::SANITATION(ref val1)
            | GDELTCategoryList::SCANDAL(ref val1)
            | GDELTCategoryList::SCIENCE(ref val1)
            | GDELTCategoryList::SECURITY_SERVICES(ref val1)
            | GDELTCategoryList::SEIGE(ref val1)
            | GDELTCategoryList::SEIZE(ref val1)
            | GDELTCategoryList::SELF_IDENTIFIED_ATROCITY(ref val1)
            | GDELTCategoryList::SELF_IDENTIFIED_ENVIRON_DISASTER(ref val1)
            | GDELTCategoryList::SELF_IDENTIFIED_HUMAN_RIGHTS(ref val1)
            | GDELTCategoryList::SELF_IDENTIFIED_HUMANITARIAN_CRISIS(ref val1)
            | GDELTCategoryList::SEPARATISTS(ref val1)
            | GDELTCategoryList::SHORTAGE(ref val1)
            | GDELTCategoryList::SICKENED(ref val1)
            | GDELTCategoryList::SLFID_CAPACITY_BUILDING(ref val1)
            | GDELTCategoryList::SLFID_CIVIL_LIBERTIES(ref val1)
            | GDELTCategoryList::SLFID_DICTATORSHIP(ref val1)
            | GDELTCategoryList::SLFID_ECONOMIC_DEVELOPMENT(ref val1)
            | GDELTCategoryList::SLFID_ECONOMIC_POWER(ref val1)
            | GDELTCategoryList::SLFID_MILITARY_BUILDUP(ref val1)
            | GDELTCategoryList::SLFID_MILITARY_READINESS(ref val1)
            | GDELTCategoryList::SLFID_MILITARY_SPENDING(ref val1)
            | GDELTCategoryList::SLFID_MINERAL_RESOURCES(ref val1)
            | GDELTCategoryList::SLFID_NATURAL_RESOURCES(ref val1)
            | GDELTCategoryList::SLFID_PEACE_BUILDING(ref val1)
            | GDELTCategoryList::SLFID_POLITICAL_BOUNDARIES(ref val1)
            | GDELTCategoryList::SLFID_RULE_OF_LAW(ref val1)
            | GDELTCategoryList::SLUMS(ref val1)
            | GDELTCategoryList::SMUGGLING(ref val1)
            | GDELTCategoryList::SOC_DIPLOMCOOP(ref val1)
            | GDELTCategoryList::SOC_ECONCOOP(ref val1)
            | GDELTCategoryList::SOC_EXPRESSREGRET(ref val1)
            | GDELTCategoryList::SOC_EXPRESSSUPPORT(ref val1)
            | GDELTCategoryList::SOC_FORCEDRELOCATION(ref val1)
            | GDELTCategoryList::SOC_GENERALCRIME(ref val1)
            | GDELTCategoryList::SOC_INTELSHARING(ref val1)
            | GDELTCategoryList::SOC_JUDICIALCOOP(ref val1)
            | GDELTCategoryList::SOC_MASSMIGRATION(ref val1)
            | GDELTCategoryList::SOC_PARDON(ref val1)
            | GDELTCategoryList::SOC_SUICIDE(ref val1)
            | GDELTCategoryList::SOC_SUSPICIOUSACTIVITIES(ref val1)
            | GDELTCategoryList::SOC_SUSPICIOUSPEOPLE(ref val1)
            | GDELTCategoryList::SOC_TRAFFICACCIDENT(ref val1)
            | GDELTCategoryList::SOVEREIGNTY(ref val1)
            | GDELTCategoryList::STATE_OF_EMERGENCY(ref val1)
            | GDELTCategoryList::STRIKE(ref val1)
            | GDELTCategoryList::SUICIDE_ATTACK(ref val1)
            | GDELTCategoryList::SURVEILLANCE(ref val1)
            | GDELTCategoryList::TAKE_OFFICE(ref val1)
            | GDELTCategoryList::TAX_CARTELS(ref val1)
            | GDELTCategoryList::TAX_DISEASE(ref val1)
            | GDELTCategoryList::TAX_ETHNICITY(ref val1)
            | GDELTCategoryList::TAX_FNCACT(ref val1)
            | GDELTCategoryList::TAX_FOODSTAPLES(ref val1)
            | GDELTCategoryList::TAX_MILITARY_TITLE(ref val1)
            | GDELTCategoryList::TAX_POLITICAL_PARTY(ref val1)
            | GDELTCategoryList::TAX_RELIGION(ref val1)
            | GDELTCategoryList::TAX_SPECIAL_ISSUES(ref val1)
            | GDELTCategoryList::TAX_SPECIALDEATH(ref val1)
            | GDELTCategoryList::TAX_TERROR_GROUP(ref val1)
            | GDELTCategoryList::TAX_WEAPONS(ref val1)
            | GDELTCategoryList::TERROR(ref val1)
            | GDELTCategoryList::TORTURE(ref val1)
            | GDELTCategoryList::TOURISM(ref val1)
            | GDELTCategoryList::TRAFFIC(ref val1)
            | GDELTCategoryList::TRANSPARENCY(ref val1)
            | GDELTCategoryList::TREASON(ref val1)
            | GDELTCategoryList::TRIAL(ref val1)
            | GDELTCategoryList::UNEMPLOYMENT(ref val1)
            | GDELTCategoryList::UNGOVERNED(ref val1)
            | GDELTCategoryList::UNREST_CHECKPOINT(ref val1)
            | GDELTCategoryList::UNREST_CLOSINGBORDER(ref val1)
            | GDELTCategoryList::UNREST_HUNGERSTRIKE(ref val1)
            | GDELTCategoryList::UNREST_MOLOTOVCOCKTAIL(ref val1)
            | GDELTCategoryList::UNREST_POLICEBRUTALITY(ref val1)
            | GDELTCategoryList::UNREST_STONETHROWING(ref val1)
            | GDELTCategoryList::UNREST_STONING(ref val1)
            | GDELTCategoryList::UNSAFE_WORK_ENVIRONMENT(ref val1)
            | GDELTCategoryList::URBAN(ref val1)
            | GDELTCategoryList::URBAN_SPRAWL(ref val1)
            | GDELTCategoryList::VANDALIZE(ref val1)
            | GDELTCategoryList::VETO(ref val1)
            | GDELTCategoryList::VIOLENT_UNREST(ref val1)
            | GDELTCategoryList::WATER_SECURITY(ref val1)
            | GDELTCategoryList::WHISTLEBLOWER(ref val1)
            | GDELTCategoryList::WMD(ref val1)
            | GDELTCategoryList::WOUND(ref val1) => Some(val1.clone().into_inner()),
        }
    }
}

impl ToProto for GDELTCategoryList {
    type ProtoType = GdeltCategoryList;
    
    fn to_proto(&self) -> Option<Self::ProtoType> {
        let temp = self.clone().to_string();
        GdeltCategoryList::from_str_name(&temp)
    }
}
