// TODO: Implement this for protobuf
pub enum GDELTLanguage {
    Afrikaans,
    Albanian,
    Armenian,
    Arabic,
    Azerbaijani,
    Bengali,
    Bosnian,
    Bulgarian,
    Catalan,
    Chinese,
    Croatian,
    Czech,
    Danish,
    Dutch,
    Estonian,
    Finnish,
    French,
    Galician,
    Georgian,
    German,
    Greek,
    Gujarati,
    Hebrew,
    Hindi,
    Hungarian,
    Icelandic,
    Indonesian,
    Italian,
    Japanese,
    Kannada,
    Kazakh,
    Korean,
    Latvian,
    Lithuanian,
    Macedonian,
    Malay,
    Malayalam,
    Marathi,
    Mongolian,
    Nepali,
    Norwegian,
    NorwegianNynorsk,
    Persian,
    Polish,
    Portuguese,
    Punjabi,
    Romanian,
    Russian,
    Serbian,
    Sinhalese,
    Slovak,
    Slovenian,
    Somali,
    Spanish,
    Swahili,
    Swedish,
    Tamil,
    Telugu,
    Thai,
    Tibetan,
    Turkish,
    Ukrainian,
    Urdu,
    Vietnamese,
}

impl GDELTLanguage {
    pub fn code(&self) -> &'static str {
        match self {
            GDELTLanguage::Afrikaans => "afr",
            GDELTLanguage::Albanian => "sqi",
            GDELTLanguage::Arabic => "ara",
            GDELTLanguage::Armenian => "hye",
            GDELTLanguage::Azerbaijani => "aze",
            GDELTLanguage::Bengali => "ben",
            GDELTLanguage::Bosnian => "bos",
            GDELTLanguage::Bulgarian => "bul",
            GDELTLanguage::Catalan => "cat",
            GDELTLanguage::Chinese => "zho",
            GDELTLanguage::Croatian => "hrv",
            GDELTLanguage::Czech => "ces",
            GDELTLanguage::Danish => "dan",
            GDELTLanguage::Dutch => "nld",
            GDELTLanguage::Estonian => "est",
            GDELTLanguage::Finnish => "fin",
            GDELTLanguage::French => "fra",
            GDELTLanguage::Galician => "glg",
            GDELTLanguage::Georgian => "kat",
            GDELTLanguage::German => "deu",
            GDELTLanguage::Greek => "ell",
            GDELTLanguage::Gujarati => "guj",
            GDELTLanguage::Hebrew => "heb",
            GDELTLanguage::Hindi => "hin",
            GDELTLanguage::Hungarian => "hun",
            GDELTLanguage::Icelandic => "isl",
            GDELTLanguage::Indonesian => "ind",
            GDELTLanguage::Italian => "ita",
            GDELTLanguage::Japanese => "jpn",
            GDELTLanguage::Kannada => "kan",
            GDELTLanguage::Kazakh => "kaz",
            GDELTLanguage::Korean => "kor",
            GDELTLanguage::Latvian => "lav",
            GDELTLanguage::Lithuanian => "lit",
            GDELTLanguage::Macedonian => "mkd",
            GDELTLanguage::Malay => "msa",
            GDELTLanguage::Malayalam => "mal",
            GDELTLanguage::Marathi => "mar",
            GDELTLanguage::Mongolian => "mon",
            GDELTLanguage::Nepali => "nep",
            GDELTLanguage::Norwegian => "nor",
            GDELTLanguage::NorwegianNynorsk => "nno",
            GDELTLanguage::Persian => "fas",
            GDELTLanguage::Polish => "pol",
            GDELTLanguage::Portuguese => "por",
            GDELTLanguage::Punjabi => "pan",
            GDELTLanguage::Romanian => "ron",
            GDELTLanguage::Russian => "rus",
            GDELTLanguage::Serbian => "srp",
            GDELTLanguage::Sinhalese => "sin",
            GDELTLanguage::Slovak => "slk",
            GDELTLanguage::Slovenian => "slv",
            GDELTLanguage::Somali => "som",
            GDELTLanguage::Spanish => "spa",
            GDELTLanguage::Swahili => "swa",
            GDELTLanguage::Swedish => "swe",
            GDELTLanguage::Tamil => "tam",
            GDELTLanguage::Telugu => "tel",
            GDELTLanguage::Thai => "tha",
            GDELTLanguage::Tibetan => "bod",
            GDELTLanguage::Turkish => "tur",
            GDELTLanguage::Ukrainian => "ukr",
            GDELTLanguage::Urdu => "urd",
            GDELTLanguage::Vietnamese => "vie",
        }
    }
}
