use super::raw_types::{
    count::*,
    date::V2EnhancedDate,
    extras_xml::cited_reference::{RawCitedReference, RawDate},
    language::RawTranslationInfo,
    location::*,
    quotation::RawV2Quotation,
    *,
};
pub mod gdelt_category;

pub struct RawGlobalKnowledgeGraph<'a> {
    gkg_record: RawGlobalKnowledgeGraphRecordID<'a>,
    v2_date: RawDate<'a>,
    v2_source_collection_identifier: V2SourceCollectionIdentifier,
    v2_source_common_name: RawV2SourceCommonName<'a>,
    v2_document_identifier: RawV2DocumentIdentifier<'a>,
    v1_counts: RawV1Count<'a>,
    v2_counts: RawV2Count<'a>,
    v1_themes: RawV1Theme<'a>,
    v2_themes: RawV2Theme<'a>,
    v1_locations: RawV1Location<'a>,
    v2_locations: RawV2Location<'a>,
    v1_persons: RawV1Person<'a>,
    v2_persons: RawV2Person<'a>,
    v1_organisations: RawV1Organisation<'a>,
    v2_organisations: RawV2Organisation<'a>,
    v15_tone: RawV1Count<'a>,
    v2_dates: V2EnhancedDate,
    v2_sharing_image: RawV2SharingImage<'a>,
    v2_related_images: RawV2RelatedImage<'a>,
    v2_social_media_embeds: RawV2SocialMediaEmbed<'a>,
    v2_social_video_embeds: RawV2SocialVideoEmbed<'a>,
    v2_quotations: RawV2Quotation<'a>,
    v2_all_names: RawV2AllName<'a>,
    v2_amounts: RawV2Amount<'a>,
    v2_translation_info: RawTranslationInfo<'a>,
    v2_extra_xml: RawCitedReference<'a>,
}
impl<'a> From<csv::StringRecordIter<'a>> for RawGlobalKnowledgeGraph<'a> {
    fn from(mut iter: csv::StringRecordIter<'a>) -> Self {
        RawGlobalKnowledgeGraph {
            gkg_record: RawGlobalKnowledgeGraphRecordID::from(iter.next().unwrap()),
            v2_date: RawDate(iter.next().unwrap()),
            v2_source_collection_identifier: V2SourceCollectionIdentifier::from(
                iter.next().unwrap(),
            ),
            v2_source_common_name: RawV2SourceCommonName::from(iter.next().unwrap()),
            v2_document_identifier: RawV2DocumentIdentifier::from(iter.next().unwrap()),
            v1_counts: RawV1Count::from(iter.next().unwrap()),
            v2_counts: RawV2Count::from(iter.next().unwrap()),
            v1_themes: RawV1Theme::from(iter.next().unwrap()),
            v2_themes: RawV2Theme::from(iter.next().unwrap()),
            v1_locations: RawV1Location::from(iter.next().unwrap()),
            v2_locations: RawV2Location::from(iter.next().unwrap()),
            v1_persons: RawV1Person::from(iter.next().unwrap()),
            v2_persons: RawV2Person::from(iter.next().unwrap()),
            v1_organisations: RawV1Organisation::from(iter.next().unwrap()),
            v2_organisations: RawV2Organisation::from(iter.next().unwrap()),
            v15_tone: RawV1Count::from(iter.next().unwrap()),
            v2_dates: super::raw_types::date::V2EnhancedDate::from(iter.next().unwrap()),
            v2_sharing_image: RawV2SharingImage::from(iter.next().unwrap()),
            v2_related_images: RawV2RelatedImage::from(iter.next().unwrap()),
            v2_social_media_embeds: RawV2SocialMediaEmbed::from(iter.next().unwrap()),
            v2_social_video_embeds: RawV2SocialVideoEmbed::from(iter.next().unwrap()),
            v2_quotations: RawV2Quotation::from(iter.next().unwrap()),
            v2_all_names: RawV2AllName::from(iter.next().unwrap()),
            v2_amounts: RawV2Amount::from(iter.next().unwrap()),
            v2_translation_info: RawTranslationInfo::from(iter.next().unwrap()),
            v2_extra_xml: RawCitedReference::from(iter.next().unwrap()),
        }
    }
}
