pub enum Religion {
    AtheismAgnosticism(SecondaryTierReligionCode),
    Bahai(SecondaryTierReligionCode),
    Buddhism(SecondaryTierReligionCode),
    Christianity(SecondaryTierReligionCode),
    Confucianism(SecondaryTierReligionCode),
    Hinduism(SecondaryTierReligionCode),
    Jainism(SecondaryTierReligionCode),
    Judaism(SecondaryTierReligionCode),
    Islam(SecondaryTierReligionCode),
    Shintoism(SecondaryTierReligionCode),
    Sikhism(SecondaryTierReligionCode),
    Taoism(SecondaryTierReligionCode),
    SecondAbrahamicReligions(SecondaryTierReligionCode),
    AfricanDiasporicReligions(SecondaryTierReligionCode),
    EastAsianReligions(SecondaryTierReligionCode),
    IndianReligions(SecondaryTierReligionCode),
    IranicReligions(SecondaryTierReligionCode),
    IndigenousTribalReligions(SecondaryTierReligionCode),
    NewReligiousMovements(SecondaryTierReligionCode),
}

pub enum SecondaryTierReligionCode {
    NotSpecified,
    Offshoot,
    NamedDenominations,
    AfricanDiasporicReligionsPriority,
    Gnostic,
    Millenarian,
    Pagan,
    Racialist,
    Syncretic,
    Extraterrestrial,
    WellnessCentric,
    ControversialStatus,
    NewReligiousMovementsPriority,
}
