use anyhow::anyhow;

use crate::types::event_table::{actor::CAMEOCountryCode, event_geography::FIPSCountryCode};

#[derive(Debug, PartialOrd, PartialEq)]
pub enum CountryZone {
    Unspecified,
    WestBank,
    Baghdad,
    GazaStrip,
    Africa,
    Asia,
    Balkans,
    Caribbean,
    Caucasus,
    CentralAfrica,
    CentralAsia,
    CentralEurope,
    EastIndies,
    EasternAfrica,
    EasternEurope,
    Europe,
    LatinAmerica,
    MiddleEast,
    Mediterranean,
    NorthAfrica,
    NorthAmerica,
    PersianGulf,
    Scandinavia,
    SouthAmerica,
    SouthAsia,
    SoutheastAsia,
    SouthernAfrica,
    WestAfrica,
    TheWest,
    Afghanistan,
    AlandIslands,
    Albania,
    Algeria,
    AmericanSamoa,
    Andorra,
    Angola,
    Anguilla,
    AntiguaandBarbuda,
    Argentina,
    Armenia,
    Aruba,
    Australia,
    Austria,
    Azerbaijan,
    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bermuda,
    Bhutan,
    Bolivia,
    BosniaandHerzegovina,
    Botswana,
    Brazil,
    BritishVirginIslands,
    BruneiDarussalam,
    Bulgaria,
    BurkinaFaso,
    Burundi,
    Cambodia,
    Cameroon,
    Canada,
    CapeVerde,
    CaymanIslands,
    CentralAfricanRepublic,
    Chad,
    Chile,
    China,
    Columbia,
    Comoros,
    DemocraticRepublicoftheCongo,
    PeoplesRepublicoftheCongo,
    CookIslands,
    CostaRica,
    IvoryCoast,
    Croatia,
    Cuba,
    Cyprus,
    CzechRepublic,
    Denmark,
    Djibouti,
    Dominica,
    DominicanRepublic,
    EastTimor,
    Ecuador,
    Egypt,
    ElSalvador,
    EquatorialGuinea,
    Eritrea,
    Estonia,
    Ethiopia,
    FaeroeIslands,
    FalklandIslands,
    Fiji,
    Finland,
    France,
    FrenchGuiana,
    FrenchPolynesia,
    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Gibraltar,
    Greece,
    Greenland,
    Grenada,
    Guadeloupe,
    Guam,
    Guatemala,
    Guinea,
    GuineaBissau,
    Guyana,
    Haiti,
    VaticanCity,
    Honduras,
    HongKong,
    Hungary,
    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    IsleofMan,
    Israel,
    Italy,
    Jamaica,
    Japan,
    Jordan,
    Kazakhstan,
    Kenya,
    Kiribati,
    NorthKorea,
    SouthKorea,
    Kuwait,
    Kyrgyzstan,
    Laos,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Macao,
    Macedonia,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    MarshallIslands,
    Martinique,
    Mauritania,
    Mauritius,
    Mayotte,
    Mexico,
    Micronesia,
    Moldova,
    Monaco,
    Mongolia,
    Montenegro,
    Montserrat,
    Morocco,
    Mozambique,
    Myanmar,
    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    NetherlandsAntilles,
    NewCaledonia,
    NewZealand,
    Nicaragua,
    Niger,
    Nigeria,
    Niue,
    NorfolkIsland,
    NorthernMarianaIslands,
    Norway,
    OccupiedPalestinianTerritory,
    Oman,
    Pakistan,
    Palau,
    Panama,
    PapuaNewGuinea,
    Paraguay,
    Peru,
    Philippines,
    Pitcairn,
    Poland,
    Portugal,
    PuertoRico,
    Qatar,
    Runion,
    Romania,
    Russia,
    Rwanda,
    SaintHelena,
    SaintKittsNevis,
    SaintLucia,
    SaintPierreandMiquelon,
    SaintVincentandtheGrenadines,
    Samoa,
    SanMarino,
    SaoTomeandPrincipe,
    SaudiArabia,
    Senegal,
    Serbia,
    Seychelles,
    SierraLeone,
    Singapore,
    Slovakia,
    Slovenia,
    SolomonIslands,
    Somalia,
    SouthAfrica,
    Spain,
    SriLanka,
    Sudan,
    Suriname,
    SvalbardandJanMayenIslands,
    Swaziland,
    Sweden,
    Switzerland,
    Syria,
    Taiwan,
    Tajikistan,
    Tanzania,
    Thailand,
    Togo,
    Tokelau,
    Tonga,
    TrinidadandTobago,
    Tunisia,
    Turkey,
    Turkmenistan,
    TurksandCaicosIslands,
    Tuvalu,
    Uganda,
    Ukraine,
    UnitedArabEmirates,
    UnitedKingdom,
    UnitedStates,
    UnitedStatesVirginIslands,
    Uruguay,
    Uzbekistan,
    Vanuatu,
    Venezuela,
    Vietnam,
    WallisandFutunaIslands,
    WesternSahara,
    Yemen,
    Zambia,
    Zimbabwe,

    AkrotiriSovereignBaseArea,
    Antarctica,
    AshmoreandCartierIslands,

    BahamasThe,
    BakerIsland,
    BassasdaIndia,
    BosniaHerzegovina,
    BouvetIsland,
    BritishIndianOceanTerritory,
    Brunei,
    ChristmasIsland,
    ClippertonIsland,
    CocosKeelingIslands,
    Colombia,
    Congo,
    CoralSeaIslands,
    CotedIvoire,
    Czechoslovakia,
    DhekeliaSovereignBaseArea,
    EtorofuHabomaiKunashiriandShikotanIslands,
    EuropaIsland,
    FalklandIslandsIslasMalvinas,
    FaroeIslands,
    FrenchSouthernandAntarcticLands,
    GloriosoIslands,
    Guernsey,
    HeardIslandandMcDonaldIslands,
    HowlandIsland,
    JanMayen,
    JarvisIsland,
    Jersey,
    JohnstonAtoll,
    JuandeNovaIsland,
    KingmanReef,
    Kosovo,
    Macau,
    MidwayIslands,
    NavassaIsland,
    NoMansLand,
    Oceans,
    PalmyraAtoll,
    ParacelIslands,
    PitcairnIslands,
    Reunion,
    SaintKittsandNevis,
    SaintMartin,
    SaintBarthelemyIsland,
    SouthGeorgiaandtheSouthSandwichIslands,
    SouthSudan,
    SpratlyIslands,
    Svalbard,
    TromelinIsland,
    UnderseaFeatures,
    UndesignatedSovereignty,
    VietnamDemocraticRepublicof,
    VirginIslands,
    WakeIsland,
    WallisandFutuna,
}

impl TryFrom<FIPSCountryCode> for CountryZone {
    type Error = anyhow::Error;

    fn try_from(value: FIPSCountryCode) -> Result<Self, Self::Error> {
       log::info!("Attempting to convert FIPSCountryCode to CountryZone: {:?}", value);
        match std::str::from_utf8(&value.0)? {
            "AF" => Ok(CountryZone::Afghanistan),
            "AX" => Ok(CountryZone::AkrotiriSovereignBaseArea),
            "AL" => Ok(CountryZone::Albania),
            "AG" => Ok(CountryZone::Algeria),
            "AQ" => Ok(CountryZone::AmericanSamoa),
            "AN" => Ok(CountryZone::Andorra),
            "AO" => Ok(CountryZone::Angola),
            "AV" => Ok(CountryZone::Anguilla),
            "AY" => Ok(CountryZone::Antarctica),
            "AC" => Ok(CountryZone::AntiguaandBarbuda),
            "AR" => Ok(CountryZone::Argentina),
            "AM" => Ok(CountryZone::Armenia),
            "AA" => Ok(CountryZone::Aruba),
            "AT" => Ok(CountryZone::AshmoreandCartierIslands),
            "AS" => Ok(CountryZone::Australia),
            "AU" => Ok(CountryZone::Austria),
            "AJ" => Ok(CountryZone::Azerbaijan),
            "BF" => Ok(CountryZone::BahamasThe),
            "BA" => Ok(CountryZone::Bahrain),
            "FQ" => Ok(CountryZone::BakerIsland),
            "BG" => Ok(CountryZone::Bangladesh),
            "BB" => Ok(CountryZone::Barbados),
            "BS" => Ok(CountryZone::BassasdaIndia),
            "BO" => Ok(CountryZone::Belarus),
            "BE" => Ok(CountryZone::Belgium),
            "BH" => Ok(CountryZone::Belize),
            "BN" => Ok(CountryZone::Benin),
            "BD" => Ok(CountryZone::Bermuda),
            "BT" => Ok(CountryZone::Bhutan),
            "BL" => Ok(CountryZone::Bolivia),
            "BK" => Ok(CountryZone::BosniaHerzegovina),
            "BC" => Ok(CountryZone::Botswana),
            "BV" => Ok(CountryZone::BouvetIsland),
            "BR" => Ok(CountryZone::Brazil),
            "IO" => Ok(CountryZone::BritishIndianOceanTerritory),
            "VI" => Ok(CountryZone::BritishVirginIslands),
            "BX" => Ok(CountryZone::Brunei),
            "BU" => Ok(CountryZone::Bulgaria),
            "UV" => Ok(CountryZone::BurkinaFaso),
            "BY" => Ok(CountryZone::Burundi),
            "CB" => Ok(CountryZone::Cambodia),
            "CM" => Ok(CountryZone::Cameroon),
            "CA" => Ok(CountryZone::Canada),
            "CV" => Ok(CountryZone::CapeVerde),
            "CJ" => Ok(CountryZone::CaymanIslands),
            "CT" => Ok(CountryZone::CentralAfricanRepublic),
            "CD" => Ok(CountryZone::Chad),
            "CI" => Ok(CountryZone::Chile),
            "CH" => Ok(CountryZone::China),
            "KT" => Ok(CountryZone::ChristmasIsland),
            "IP" => Ok(CountryZone::ClippertonIsland),
            "CK" => Ok(CountryZone::CocosKeelingIslands),
            "CO" => Ok(CountryZone::Colombia),
            "CN" => Ok(CountryZone::Comoros),
            "CF" => Ok(CountryZone::Congo),
            "CW" => Ok(CountryZone::CookIslands),
            "CR" => Ok(CountryZone::CoralSeaIslands),
            "CS" => Ok(CountryZone::CostaRica),
            "IV" => Ok(CountryZone::CotedIvoire),
            "HR" => Ok(CountryZone::Croatia),
            "CU" => Ok(CountryZone::Cuba),
            "CY" => Ok(CountryZone::Cyprus),
            "EZ" => Ok(CountryZone::CzechRepublic),
            "LO" => Ok(CountryZone::Czechoslovakia),
            "CG" => Ok(CountryZone::DemocraticRepublicoftheCongo),
            "DA" => Ok(CountryZone::Denmark),
            "DX" => Ok(CountryZone::DhekeliaSovereignBaseArea),
            "DJ" => Ok(CountryZone::Djibouti),
            "DO" => Ok(CountryZone::Dominica),
            "DR" => Ok(CountryZone::DominicanRepublic),
            "TT" => Ok(CountryZone::EastTimor),
            "EC" => Ok(CountryZone::Ecuador),
            "EG" => Ok(CountryZone::Egypt),
            "ES" => Ok(CountryZone::ElSalvador),
            "GV" => Ok(CountryZone::EquatorialGuinea),
            "EK" => Ok(CountryZone::EquatorialGuinea),
            "ER" => Ok(CountryZone::Eritrea),
            "EN" => Ok(CountryZone::Estonia),
            "ET" => Ok(CountryZone::Ethiopia),
            "PJ" => Ok(CountryZone::EtorofuHabomaiKunashiriandShikotanIslands),
            "EU" => Ok(CountryZone::EuropaIsland),
            "FK" => Ok(CountryZone::FalklandIslandsIslasMalvinas),
            "FO" => Ok(CountryZone::FaroeIslands),
            "FJ" => Ok(CountryZone::Fiji),
            "FI" => Ok(CountryZone::Finland),
            "FR" => Ok(CountryZone::France),
            "FG" => Ok(CountryZone::FrenchGuiana),
            "FP" => Ok(CountryZone::FrenchPolynesia),
            "FS" => Ok(CountryZone::FrenchSouthernandAntarcticLands),
            "GB" => Ok(CountryZone::Gabon),
            "GA" => Ok(CountryZone::Gambia),
            "GZ" => Ok(CountryZone::GazaStrip),
            "GG" => Ok(CountryZone::Georgia),
            "GM" => Ok(CountryZone::Germany),
            "GH" => Ok(CountryZone::Ghana),
            "GI" => Ok(CountryZone::Gibraltar),
            "GO" => Ok(CountryZone::GloriosoIslands),
            "GR" => Ok(CountryZone::Greece),
            "GL" => Ok(CountryZone::Greenland),
            "GJ" => Ok(CountryZone::Grenada),
            "GP" => Ok(CountryZone::Guadeloupe),
            "GQ" => Ok(CountryZone::Guam),
            "GT" => Ok(CountryZone::Guatemala),
            "GK" => Ok(CountryZone::Guernsey),
            "PU" => Ok(CountryZone::GuineaBissau),
            "GY" => Ok(CountryZone::Guyana),
            "HA" => Ok(CountryZone::Haiti),
            "HM" => Ok(CountryZone::HeardIslandandMcDonaldIslands),
            "HO" => Ok(CountryZone::Honduras),
            "HK" => Ok(CountryZone::HongKong),
            "HQ" => Ok(CountryZone::HowlandIsland),
            "HU" => Ok(CountryZone::Hungary),
            "IC" => Ok(CountryZone::Iceland),
            "IN" => Ok(CountryZone::India),
            "ID" => Ok(CountryZone::Indonesia),
            "IR" => Ok(CountryZone::Iran),
            "IZ" => Ok(CountryZone::Iraq),
            "EI" => Ok(CountryZone::Ireland),
            "IM" => Ok(CountryZone::IsleofMan),
            "IS" => Ok(CountryZone::Israel),
            "IT" => Ok(CountryZone::Italy),
            "JM" => Ok(CountryZone::Jamaica),
            "JN" => Ok(CountryZone::JanMayen),
            "JA" => Ok(CountryZone::Japan),
            "DQ" => Ok(CountryZone::JarvisIsland),
            "JE" => Ok(CountryZone::Jersey),
            "JQ" => Ok(CountryZone::JohnstonAtoll),
            "JO" => Ok(CountryZone::Jordan),
            "JU" => Ok(CountryZone::JuandeNovaIsland),
            "KZ" => Ok(CountryZone::Kazakhstan),
            "KE" => Ok(CountryZone::Kenya),
            "KQ" => Ok(CountryZone::KingmanReef),
            "KR" => Ok(CountryZone::Kiribati),
            "KV" => Ok(CountryZone::Kosovo),
            "KU" => Ok(CountryZone::Kuwait),
            "KG" => Ok(CountryZone::Kyrgyzstan),
            "LA" => Ok(CountryZone::Laos),
            "LG" => Ok(CountryZone::Latvia),
            "LE" => Ok(CountryZone::Lebanon),
            "LT" => Ok(CountryZone::Lesotho),
            "LI" => Ok(CountryZone::Liberia),
            "LY" => Ok(CountryZone::Libya),
            "LS" => Ok(CountryZone::Liechtenstein),
            "LH" => Ok(CountryZone::Lithuania),
            "LU" => Ok(CountryZone::Luxembourg),
            "MC" => Ok(CountryZone::Macau),
            "MK" => Ok(CountryZone::Macedonia),
            "MA" => Ok(CountryZone::Madagascar),
            "MI" => Ok(CountryZone::Malawi),
            "MY" => Ok(CountryZone::Malaysia),
            "MV" => Ok(CountryZone::Maldives),
            "ML" => Ok(CountryZone::Mali),
            "MT" => Ok(CountryZone::Malta),
            "RM" => Ok(CountryZone::MarshallIslands),
            "MB" => Ok(CountryZone::Martinique),
            "MR" => Ok(CountryZone::Mauritania),
            "MP" => Ok(CountryZone::Mauritius),
            "MF" => Ok(CountryZone::Mayotte),
            "MX" => Ok(CountryZone::Mexico),
            "FM" => Ok(CountryZone::Micronesia),
            "MQ" => Ok(CountryZone::MidwayIslands),
            "MD" => Ok(CountryZone::Moldova),
            "MN" => Ok(CountryZone::Monaco),
            "MG" => Ok(CountryZone::Mongolia),
            "MJ" => Ok(CountryZone::Montenegro),
            "MH" => Ok(CountryZone::Montserrat),
            "MO" => Ok(CountryZone::Morocco),
            "MZ" => Ok(CountryZone::Mozambique),
            "BM" => Ok(CountryZone::Myanmar),
            "WA" => Ok(CountryZone::Namibia),
            "NR" => Ok(CountryZone::Nauru),
            "BQ" => Ok(CountryZone::NavassaIsland),
            "NP" => Ok(CountryZone::Nepal),
            "NL" => Ok(CountryZone::Netherlands),
            "NT" => Ok(CountryZone::NetherlandsAntilles),
            "NC" => Ok(CountryZone::NewCaledonia),
            "NZ" => Ok(CountryZone::NewZealand),
            "NU" => Ok(CountryZone::Nicaragua),
            "NG" => Ok(CountryZone::Niger),
            "NI" => Ok(CountryZone::Nigeria),
            "NE" => Ok(CountryZone::Niue),
            "NM" => Ok(CountryZone::NoMansLand),
            "NF" => Ok(CountryZone::NorfolkIsland),
            "KN" => Ok(CountryZone::NorthKorea),
            "CQ" => Ok(CountryZone::NorthernMarianaIslands),
            "NO" => Ok(CountryZone::Norway),
            "OS" => Ok(CountryZone::Oceans),
            "MU" => Ok(CountryZone::Oman),
            "PK" => Ok(CountryZone::Pakistan),
            "PS" => Ok(CountryZone::Palau),
            "LQ" => Ok(CountryZone::PalmyraAtoll),
            "PM" => Ok(CountryZone::Panama),
            "PP" => Ok(CountryZone::PapuaNewGuinea),
            "PF" => Ok(CountryZone::ParacelIslands),
            "PA" => Ok(CountryZone::Paraguay),
            "PE" => Ok(CountryZone::Peru),
            "RP" => Ok(CountryZone::Philippines),
            "PC" => Ok(CountryZone::PitcairnIslands),
            "PL" => Ok(CountryZone::Poland),
            "PO" => Ok(CountryZone::Portugal),
            "RQ" => Ok(CountryZone::PuertoRico),
            "QA" => Ok(CountryZone::Qatar),
            "RE" => Ok(CountryZone::Reunion),
            "RO" => Ok(CountryZone::Romania),
            "RS" => Ok(CountryZone::Russia),
            "RW" => Ok(CountryZone::Rwanda),
            "SH" => Ok(CountryZone::SaintHelena),
            "SC" => Ok(CountryZone::SaintKittsandNevis),
            "ST" => Ok(CountryZone::SaintLucia),
            "RN" => Ok(CountryZone::SaintMartin),
            "SB" => Ok(CountryZone::SaintPierreandMiquelon),
            "VC" => Ok(CountryZone::SaintVincentandtheGrenadines),
            "TB" => Ok(CountryZone::SaintBarthelemyIsland),
            "WS" => Ok(CountryZone::Samoa),
            "SM" => Ok(CountryZone::SanMarino),
            "TP" => Ok(CountryZone::SaoTomeandPrincipe),
            "SA" => Ok(CountryZone::SaudiArabia),
            "SG" => Ok(CountryZone::Senegal),
            "RI" => Ok(CountryZone::Serbia),
            "SE" => Ok(CountryZone::Seychelles),
            "SL" => Ok(CountryZone::SierraLeone),
            "SN" => Ok(CountryZone::Singapore),
            "SI" => Ok(CountryZone::Slovenia),
            "BP" => Ok(CountryZone::SolomonIslands),
            "SO" => Ok(CountryZone::Somalia),
            "SF" => Ok(CountryZone::SouthAfrica),
            "SX" => Ok(CountryZone::SouthGeorgiaandtheSouthSandwichIslands),
            "KS" => Ok(CountryZone::SouthKorea),
            "OD" => Ok(CountryZone::SouthSudan),
            "SP" => Ok(CountryZone::Spain),
            "PG" => Ok(CountryZone::SpratlyIslands),
            "CE" => Ok(CountryZone::SriLanka),
            "SU" => Ok(CountryZone::Sudan),
            "NS" => Ok(CountryZone::Suriname),
            "SV" => Ok(CountryZone::Svalbard),
            "WZ" => Ok(CountryZone::Swaziland),
            "SW" => Ok(CountryZone::Sweden),
            "SZ" => Ok(CountryZone::Switzerland),
            "SY" => Ok(CountryZone::Syria),
            "TW" => Ok(CountryZone::Taiwan),
            "TI" => Ok(CountryZone::Tajikistan),
            "TZ" => Ok(CountryZone::Tanzania),
            "TH" => Ok(CountryZone::Thailand),
            "TO" => Ok(CountryZone::Togo),
            "TL" => Ok(CountryZone::Tokelau),
            "TN" => Ok(CountryZone::Tonga),
            "TD" => Ok(CountryZone::TrinidadandTobago),
            "TE" => Ok(CountryZone::TromelinIsland),
            "TS" => Ok(CountryZone::Tunisia),
            "TU" => Ok(CountryZone::Turkey),
            "TX" => Ok(CountryZone::Turkmenistan),
            "TK" => Ok(CountryZone::TurksandCaicosIslands),
            "TV" => Ok(CountryZone::Tuvalu),
            "UG" => Ok(CountryZone::Uganda),
            "UP" => Ok(CountryZone::Ukraine),
            "UF" => Ok(CountryZone::UnderseaFeatures),
            "UU" => Ok(CountryZone::UndesignatedSovereignty),
            "AE" => Ok(CountryZone::UnitedArabEmirates),
            "UK" => Ok(CountryZone::UnitedKingdom),
            "US" => Ok(CountryZone::UnitedStates),
            "UY" => Ok(CountryZone::Uruguay),
            "UZ" => Ok(CountryZone::Uzbekistan),
            "NH" => Ok(CountryZone::Vanuatu),
            "VT" => Ok(CountryZone::VaticanCity),
            "VE" => Ok(CountryZone::Venezuela),
            "VM" => Ok(CountryZone::VietnamDemocraticRepublicof),
            "VQ" => Ok(CountryZone::VirginIslands),
            "WQ" => Ok(CountryZone::WakeIsland),
            "WF" => Ok(CountryZone::WallisandFutuna),
            "WE" => Ok(CountryZone::WestBank),
            "WI" => Ok(CountryZone::WesternSahara),
            "YM" => Ok(CountryZone::Yemen),
            "ZA" => Ok(CountryZone::Zambia),
            "ZI" => Ok(CountryZone::Zimbabwe),
            _ => Err(anyhow!("Invalid FIPS Code")),
        }
    }
}

impl TryFrom<CAMEOCountryCode> for CountryZone {
    type Error = anyhow::Error;

    fn try_from(value: CAMEOCountryCode) -> Result<Self, Self::Error> {
        match std::str::from_utf8(&value.0)? {
            "WSB" => Ok(CountryZone::WestBank),
            "BAG" => Ok(CountryZone::Baghdad),
            "GZS" => Ok(CountryZone::GazaStrip),
            "AFR" => Ok(CountryZone::Africa),
            "ASA" => Ok(CountryZone::Asia),
            "BLK" => Ok(CountryZone::Balkans),
            "CRB" => Ok(CountryZone::Caribbean),
            "CAU" => Ok(CountryZone::Caucasus),
            "CFR" => Ok(CountryZone::CentralAfrica),
            "CAS" => Ok(CountryZone::CentralAsia),
            "CEU" => Ok(CountryZone::CentralEurope),
            "EIN" => Ok(CountryZone::EastIndies),
            "EAF" => Ok(CountryZone::EasternAfrica),
            "EEU" => Ok(CountryZone::EasternEurope),
            "EUR" => Ok(CountryZone::Europe),
            "LAM" => Ok(CountryZone::LatinAmerica),
            "MEA" => Ok(CountryZone::MiddleEast),
            "MDT" => Ok(CountryZone::Mediterranean),
            "NAF" => Ok(CountryZone::NorthAfrica),
            "NMR" => Ok(CountryZone::NorthAmerica),
            "PGS" => Ok(CountryZone::PersianGulf),
            "SCN" => Ok(CountryZone::Scandinavia),
            "SAM" => Ok(CountryZone::SouthAmerica),
            "SAS" => Ok(CountryZone::SouthAsia),
            "SEA" => Ok(CountryZone::SoutheastAsia),
            "SAF" => Ok(CountryZone::SouthernAfrica),
            "WAF" => Ok(CountryZone::WestAfrica),
            "WST" => Ok(CountryZone::TheWest),
            "AFG" => Ok(CountryZone::Afghanistan),
            "ALA" => Ok(CountryZone::AlandIslands),
            "ALB" => Ok(CountryZone::Albania),
            "DZA" => Ok(CountryZone::Algeria),
            "ASM" => Ok(CountryZone::AmericanSamoa),
            "AND" => Ok(CountryZone::Andorra),
            "AGO" => Ok(CountryZone::Angola),
            "AIA" => Ok(CountryZone::Anguilla),
            "ATG" => Ok(CountryZone::AntiguaandBarbuda),
            "ARG" => Ok(CountryZone::Argentina),
            "ARM" => Ok(CountryZone::Armenia),
            "ABW" => Ok(CountryZone::Aruba),
            "AUS" => Ok(CountryZone::Australia),
            "AUT" => Ok(CountryZone::Austria),
            "AZE" => Ok(CountryZone::Azerbaijan),
            "BHS" => Ok(CountryZone::Bahamas),
            "BHR" => Ok(CountryZone::Bahrain),
            "BGD" => Ok(CountryZone::Bangladesh),
            "BRB" => Ok(CountryZone::Barbados),
            "BLR" => Ok(CountryZone::Belarus),
            "BEL" => Ok(CountryZone::Belgium),
            "BLZ" => Ok(CountryZone::Belize),
            "BEN" => Ok(CountryZone::Benin),
            "BMU" => Ok(CountryZone::Bermuda),
            "BTN" => Ok(CountryZone::Bhutan),
            "BOL" => Ok(CountryZone::Bolivia),
            "BIH" => Ok(CountryZone::BosniaandHerzegovina),
            "BWA" => Ok(CountryZone::Botswana),
            "BRA" => Ok(CountryZone::Brazil),
            "VGB" => Ok(CountryZone::BritishVirginIslands),
            "BRN" => Ok(CountryZone::BruneiDarussalam),
            "BGR" => Ok(CountryZone::Bulgaria),
            "BFA" => Ok(CountryZone::BurkinaFaso),
            "BDI" => Ok(CountryZone::Burundi),
            "KHM" => Ok(CountryZone::Cambodia),
            "CMR" => Ok(CountryZone::Cameroon),
            "CAN" => Ok(CountryZone::Canada),
            "CPV" => Ok(CountryZone::CapeVerde),
            "CYM" => Ok(CountryZone::CaymanIslands),
            "CAF" => Ok(CountryZone::CentralAfricanRepublic),
            "TCD" => Ok(CountryZone::Chad),
            "CHL" => Ok(CountryZone::Chile),
            "CHN" => Ok(CountryZone::China),
            "COL" => Ok(CountryZone::Columbia),
            "COM" => Ok(CountryZone::Comoros),
            "COD" => Ok(CountryZone::DemocraticRepublicoftheCongo),
            "COG" => Ok(CountryZone::PeoplesRepublicoftheCongo),
            "COK" => Ok(CountryZone::CookIslands),
            "CRI" => Ok(CountryZone::CostaRica),
            "CIV" => Ok(CountryZone::IvoryCoast),
            "HRV" => Ok(CountryZone::Croatia),
            "CUB" => Ok(CountryZone::Cuba),
            "CYP" => Ok(CountryZone::Cyprus),
            "CZE" => Ok(CountryZone::CzechRepublic),
            "DNK" => Ok(CountryZone::Denmark),
            "DJI" => Ok(CountryZone::Djibouti),
            "DMA" => Ok(CountryZone::Dominica),
            "DOM" => Ok(CountryZone::DominicanRepublic),
            "TMP" => Ok(CountryZone::EastTimor),
            "ECU" => Ok(CountryZone::Ecuador),
            "EGY" => Ok(CountryZone::Egypt),
            "SLV" => Ok(CountryZone::ElSalvador),
            "GNQ" => Ok(CountryZone::EquatorialGuinea),
            "ERI" => Ok(CountryZone::Eritrea),
            "EST" => Ok(CountryZone::Estonia),
            "ETH" => Ok(CountryZone::Ethiopia),
            "FRO" => Ok(CountryZone::FaeroeIslands),
            "FLK" => Ok(CountryZone::FalklandIslands),
            "FJI" => Ok(CountryZone::Fiji),
            "FIN" => Ok(CountryZone::Finland),
            "FRA" => Ok(CountryZone::France),
            "GUF" => Ok(CountryZone::FrenchGuiana),
            "PYF" => Ok(CountryZone::FrenchPolynesia),
            "GAB" => Ok(CountryZone::Gabon),
            "GMB" => Ok(CountryZone::Gambia),
            "GEO" => Ok(CountryZone::Georgia),
            "DEU" => Ok(CountryZone::Germany),
            "GHA" => Ok(CountryZone::Ghana),
            "GIB" => Ok(CountryZone::Gibraltar),
            "GRC" => Ok(CountryZone::Greece),
            "GRL" => Ok(CountryZone::Greenland),
            "GRD" => Ok(CountryZone::Grenada),
            "GLP" => Ok(CountryZone::Guadeloupe),
            "GUM" => Ok(CountryZone::Guam),
            "GTM" => Ok(CountryZone::Guatemala),
            "GIN" => Ok(CountryZone::Guinea),
            "GNB" => Ok(CountryZone::GuineaBissau),
            "GUY" => Ok(CountryZone::Guyana),
            "HTI" => Ok(CountryZone::Haiti),
            "VAT" => Ok(CountryZone::VaticanCity),
            "HND" => Ok(CountryZone::Honduras),
            "HKG" => Ok(CountryZone::HongKong),
            "HUN" => Ok(CountryZone::Hungary),
            "ISL" => Ok(CountryZone::Iceland),
            "IND" => Ok(CountryZone::India),
            "IDN" => Ok(CountryZone::Indonesia),
            "IRN" => Ok(CountryZone::Iran),
            "IRQ" => Ok(CountryZone::Iraq),
            "IRL" => Ok(CountryZone::Ireland),
            "IMY" => Ok(CountryZone::IsleofMan),
            "ISR" => Ok(CountryZone::Israel),
            "ITA" => Ok(CountryZone::Italy),
            "JAM" => Ok(CountryZone::Jamaica),
            "JPN" => Ok(CountryZone::Japan),
            "JOR" => Ok(CountryZone::Jordan),
            "KAZ" => Ok(CountryZone::Kazakhstan),
            "KEN" => Ok(CountryZone::Kenya),
            "KIR" => Ok(CountryZone::Kiribati),
            "PRK" => Ok(CountryZone::NorthKorea),
            "KOR" => Ok(CountryZone::SouthKorea),
            "KWT" => Ok(CountryZone::Kuwait),
            "KGZ" => Ok(CountryZone::Kyrgyzstan),
            "LAO" => Ok(CountryZone::Laos),
            "LVA" => Ok(CountryZone::Latvia),
            "LBN" => Ok(CountryZone::Lebanon),
            "LSO" => Ok(CountryZone::Lesotho),
            "LBR" => Ok(CountryZone::Liberia),
            "LBY" => Ok(CountryZone::Libya),
            "LIE" => Ok(CountryZone::Liechtenstein),
            "LTU" => Ok(CountryZone::Lithuania),
            "LUX" => Ok(CountryZone::Luxembourg),
            "MAC" => Ok(CountryZone::Macao),
            "MKD" => Ok(CountryZone::Macedonia),
            "MDG" => Ok(CountryZone::Madagascar),
            "MWI" => Ok(CountryZone::Malawi),
            "MYS" => Ok(CountryZone::Malaysia),
            "MDV" => Ok(CountryZone::Maldives),
            "MLI" => Ok(CountryZone::Mali),
            "MLT" => Ok(CountryZone::Malta),
            "MHL" => Ok(CountryZone::MarshallIslands),
            "MTQ" => Ok(CountryZone::Martinique),
            "MRT" => Ok(CountryZone::Mauritania),
            "MUS" => Ok(CountryZone::Mauritius),
            "MYT" => Ok(CountryZone::Mayotte),
            "MEX" => Ok(CountryZone::Mexico),
            "FSM" => Ok(CountryZone::Micronesia),
            "MDA" => Ok(CountryZone::Moldova),
            "MCO" => Ok(CountryZone::Monaco),
            "MNG" => Ok(CountryZone::Mongolia),
            "MTN" => Ok(CountryZone::Montenegro),
            "MSR" => Ok(CountryZone::Montserrat),
            "MAR" => Ok(CountryZone::Morocco),
            "MOZ" => Ok(CountryZone::Mozambique),
            "MMR" => Ok(CountryZone::Myanmar),
            "NAM" => Ok(CountryZone::Namibia),
            "NRU" => Ok(CountryZone::Nauru),
            "NPL" => Ok(CountryZone::Nepal),
            "NLD" => Ok(CountryZone::Netherlands),
            "ANT" => Ok(CountryZone::NetherlandsAntilles),
            "NCL" => Ok(CountryZone::NewCaledonia),
            "NZL" => Ok(CountryZone::NewZealand),
            "NIC" => Ok(CountryZone::Nicaragua),
            "NER" => Ok(CountryZone::Niger),
            "NGA" => Ok(CountryZone::Nigeria),
            "NIU" => Ok(CountryZone::Niue),
            "NFK" => Ok(CountryZone::NorfolkIsland),
            "MNP" => Ok(CountryZone::NorthernMarianaIslands),
            "NOR" => Ok(CountryZone::Norway),
            "PSE" => Ok(CountryZone::OccupiedPalestinianTerritory),
            "OMN" => Ok(CountryZone::Oman),
            "PAK" => Ok(CountryZone::Pakistan),
            "PLW" => Ok(CountryZone::Palau),
            "PAN" => Ok(CountryZone::Panama),
            "PNG" => Ok(CountryZone::PapuaNewGuinea),
            "PRY" => Ok(CountryZone::Paraguay),
            "PER" => Ok(CountryZone::Peru),
            "PHL" => Ok(CountryZone::Philippines),
            "PCN" => Ok(CountryZone::Pitcairn),
            "POL" => Ok(CountryZone::Poland),
            "PRT" => Ok(CountryZone::Portugal),
            "PRI" => Ok(CountryZone::PuertoRico),
            "QAT" => Ok(CountryZone::Qatar),
            "REU" => Ok(CountryZone::Runion),
            "ROM" => Ok(CountryZone::Romania),
            "RUS" => Ok(CountryZone::Russia),
            "RWA" => Ok(CountryZone::Rwanda),
            "SHN" => Ok(CountryZone::SaintHelena),
            "KNA" => Ok(CountryZone::SaintKittsNevis),
            "LCA" => Ok(CountryZone::SaintLucia),
            "SPM" => Ok(CountryZone::SaintPierreandMiquelon),
            "VCT" => Ok(CountryZone::SaintVincentandtheGrenadines),
            "WSM" => Ok(CountryZone::Samoa),
            "SMR" => Ok(CountryZone::SanMarino),
            "STP" => Ok(CountryZone::SaoTomeandPrincipe),
            "SAU" => Ok(CountryZone::SaudiArabia),
            "SEN" => Ok(CountryZone::Senegal),
            "SRB" => Ok(CountryZone::Serbia),
            "SYC" => Ok(CountryZone::Seychelles),
            "SLE" => Ok(CountryZone::SierraLeone),
            "SGP" => Ok(CountryZone::Singapore),
            "SVK" => Ok(CountryZone::Slovakia),
            "SVN" => Ok(CountryZone::Slovenia),
            "SLB" => Ok(CountryZone::SolomonIslands),
            "SOM" => Ok(CountryZone::Somalia),
            "ZAF" => Ok(CountryZone::SouthAfrica),
            "ESP" => Ok(CountryZone::Spain),
            "LKA" => Ok(CountryZone::SriLanka),
            "SDN" => Ok(CountryZone::Sudan),
            "SUR" => Ok(CountryZone::Suriname),
            "SJM" => Ok(CountryZone::SvalbardandJanMayenIslands),
            "SWZ" => Ok(CountryZone::Swaziland),
            "SWE" => Ok(CountryZone::Sweden),
            "CHE" => Ok(CountryZone::Switzerland),
            "SYR" => Ok(CountryZone::Syria),
            "TWN" => Ok(CountryZone::Taiwan),
            "TJK" => Ok(CountryZone::Tajikistan),
            "TZA" => Ok(CountryZone::Tanzania),
            "THA" => Ok(CountryZone::Thailand),
            "TGO" => Ok(CountryZone::Togo),
            "TKL" => Ok(CountryZone::Tokelau),
            "TON" => Ok(CountryZone::Tonga),
            "TTO" => Ok(CountryZone::TrinidadandTobago),
            "TUN" => Ok(CountryZone::Tunisia),
            "TUR" => Ok(CountryZone::Turkey),
            "TKM" => Ok(CountryZone::Turkmenistan),
            "TCA" => Ok(CountryZone::TurksandCaicosIslands),
            "TUV" => Ok(CountryZone::Tuvalu),
            "UGA" => Ok(CountryZone::Uganda),
            "UKR" => Ok(CountryZone::Ukraine),
            "ARE" => Ok(CountryZone::UnitedArabEmirates),
            "GBR" => Ok(CountryZone::UnitedKingdom),
            "USA" => Ok(CountryZone::UnitedStates),
            "VIR" => Ok(CountryZone::UnitedStatesVirginIslands),
            "URY" => Ok(CountryZone::Uruguay),
            "UZB" => Ok(CountryZone::Uzbekistan),
            "VUT" => Ok(CountryZone::Vanuatu),
            "VEN" => Ok(CountryZone::Venezuela),
            "VNM" => Ok(CountryZone::Vietnam),
            "WLF" => Ok(CountryZone::WallisandFutunaIslands),
            "ESH" => Ok(CountryZone::WesternSahara),
            "YEM" => Ok(CountryZone::Yemen),
            "ZMB" => Ok(CountryZone::Zambia),
            "ZWE" => Ok(CountryZone::Zimbabwe),
            _ => Err(anyhow!("Invalid CAMEO Country Code")),
        }
    }
}

use std::sync::Once;

static INIT: Once = Once::new();

fn init_logger() {
    INIT.call_once(|| {
        env_logger::init();
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use log::info;

    #[test]
    fn test_cameo_country_code_try_from() {
        init_logger();

        let valid_code = "USA";
        let invalid_code = "XX";
        let empty_code = "";
        let short_code = "US";

        info!("Testing valid CAMEO country code: {:?}", valid_code);
        let valid_result = CAMEOCountryCode::try_from(Some(valid_code));
        assert!(valid_result.is_ok());
        assert_eq!(valid_result.unwrap().0, [b'U', b'S', b'A']);

        info!("Testing invalid CAMEO country code: {:?}", invalid_code);
        let invalid_result = CAMEOCountryCode::try_from(Some(invalid_code));
        assert!(invalid_result.is_err());

        info!("Testing empty CAMEO country code: {:?}", empty_code);
        let empty_result = CAMEOCountryCode::try_from(Some(empty_code));
        assert!(empty_result.is_err());

        info!("Testing short CAMEO country code: {:?}", short_code);
        let short_result = CAMEOCountryCode::try_from(Some(short_code));
        assert!(short_result.is_err());
    }

    #[test]
    fn test_fips_country_code_try_from() {
        init_logger();

        let valid_code = "US";
        let invalid_code = "XX";
        let empty_code = "";
        let long_code = "USA";

        info!("Testing valid FIPS country code: {:?}", valid_code);
        let valid_result = FIPSCountryCode::try_from(Some(valid_code));
        assert!(valid_result.is_ok());
        assert_eq!(valid_result.unwrap().0, [b'U', b'S']);

        info!("Testing invalid FIPS country code: {:?}", invalid_code);
        let invalid_result = FIPSCountryCode::try_from(Some(invalid_code));
        assert!(invalid_result.is_ok()); // Still valid as it matches the size

        info!("Testing empty FIPS country code: {:?}", empty_code);
        let empty_result = FIPSCountryCode::try_from(Some(empty_code));
        assert!(empty_result.is_err());

        info!("Testing long FIPS country code: {:?}", long_code);
        let long_result = FIPSCountryCode::try_from(Some(long_code));
        assert!(long_result.is_err());
    }
}