use anyhow::anyhow;

use crate::types::event_table::actor::CAMEOEthnicityCode;

pub enum Ethnicity {
    Unspecified,
    Afar,
    Abkhaz,
    AboriginalAustralians,
    Acehnese,
    Achang,
    Acholi,
    Ga,
    Adivasi,
    Adjarians,
    Adyghe,
    BlackAfrican,
    Afrikaners,
    Ahmadis,
    Ainu,
    Aja,
    Akan,
    Aku,
    Alawi,
    Albanian,
    Aleut,
    Algonquian,
    Altay,
    Alur,
    Ambonese,
    AmericoLiberians,
    Amhara,
    AngikaSpeakers,
    Apache,
    Arab,
    Aragonese,
    Armenian,
    Mapuche,
    Arapaho,
    Arawak,
    Asian,
    AshkenaziJews,
    Assamese,
    Asturian,
    Assyrian,
    Atacamenos,
    Argentinians,
    Athabaskan,
    AgnosticAthiest,
    Australians,
    Austrians,
    CaucasianAvars,
    Awadhi,
    Aymara,
    Azerbaijani,
    Baganda,
    Bahais,
    Bamileke,
    Bashkirs,
    Baloch,
    Bambara,
    Balinese,
    Basque,
    Bari,
    Basoga,
    Gbaya,
    Rakhine,
    Beja,
    Belarusians,
    Bemba,
    BengaliHindu,
    Berber,
    Beydan,
    Bhojpuri,
    Bihari,
    Bai,
    Bicolano,
    Edo,
    UrbanniVanautu,
    Bateke,
    Bakongo,
    Bakweri,
    Siksikawa,
    Blang,
    Balkars,
    Balanta,
    Bamar,
    BeniShugalGumez,
    Bantu,
    Banyarwanda,
    Bodo,
    Tibetan,
    Bolivia,
    Bonan,
    Bosniaks,
    Buyei,
    Brijwasi,
    Bariba,
    Breton,
    Brahui,
    Burakumin,
    Kurichiya,
    Bushmen,
    Baster,
    Subiya,
    BetiPahuin,
    Batak,
    Buryat,
    Buddhist,
    Bugis,
    Bulgarian,
    Bilen,
    CabindanMayombe,
    Caddo,
    CapeVerdean,
    Kalina,
    Catalan,
    Cebuano,
    Chamorro,
    Chukchi,
    Chechen,
    Chagatai,
    Chinese,
    Chuukese,
    Chileans,
    Mari,
    Chinook,
    Choctaw,
    Chipewyan,
    Cherokee,
    Chorti,
    Chuvash,
    Chewa,
    Cheyenne,
    Cham,
    Colombian,
    Confusian,
    CopticChristians,
    Cornish,
    Corsican,
    Cotiers,
    EnglishCreole,
    FrenchCreole,
    PortugueseCreole,
    Cree,
    CrimeanTatar,
    Christian,
    OrthodoxChristian,
    Creole,
    Kashubian,
    CostaRicans,
    Catholics,
    Cushitic,
    Czech,
    Dai,
    Sioux,
    Dalit,
    Damara,
    Danes,
    YaoAsia,
    Dargwa,
    Daur,
    Dayak,
    Lenape,
    Slavey,
    Dogrib,
    Dinka,
    Maldivian,
    DjermaSonghai,
    Dogras,
    Dominicans,
    Dong,
    Dongxiang,
    Dravidian,
    Druze,
    LowerSorbian,
    Duala,
    Dutch,
    Dyula,
    Ngalop,
    EastTimorese,
    Ecuadorians,
    Efik,
    EastIndian,
    Ekajuk,
    English,
    Eshira,
    Estonian,
    EthiopianJews,
    Europeans,
    Evenks,
    Ewe,
    Ewondo,
    Fang,
    Faroese,
    Fante,
    Fijian,
    Filipino,
    Finns,
    FinnoUgric,
    Fon,
    French,
    Santals,
    Frisians,
    Fur,
    Fula,
    Friulan,
    Garifuna,
    Gayo,
    Gelao,
    Georgian,
    German,
    GiaRai,
    Kiribati,
    Gin,
    Gio,
    Gaels,
    Irish,
    Galician,
    Manx,
    Gondi,
    Gorontalonese,
    Grassfielders,
    Grebo,
    Greek,
    Guarani,
    SwissGermans,
    Guatemalan,
    Gujarati,
    Guan,
    Gwichin,
    Hadjerai,
    Haida,
    Harari,
    Haitian,
    Hausa,
    Hawaiian,
    Hazara,
    Herero,
    HillTribes,
    Hiligayon,
    Himachali,
    Hindu,
    Hasidic,
    Hmong,
    HiriMotu,
    Hani,
    Hoa,
    Hondurans,
    Haratin,
    Croats,
    UpperSorbian,
    Hui,
    Hungarian,
    Hupa,
    Hutu,
    Iban,
    Igbo,
    Icelanders,
    Indigenous,
    Indian,
    Yi,
    Ijaw,
    Inuit,
    Ilocono,
    Indonesian,
    Ingush,
    Inupiat,
    Iranian,
    Iroquois,
    Itallian,
    Jain,
    Javanese,
    Jewish,
    JehovahsWitnesses,
    Jino,
    Jola,
    Japanese,
    Karakalpak,
    Kabyle,
    Kachin,
    Kadazan,
    KakwaNubian,
    Kalaallit,
    Kamba,
    Kannada,
    Kaonde,
    Karen,
    Kashmiri,
    Kanuri,
    Kavango,
    Kazakhs,
    Kabarday,
    Kabye,
    Karachays,
    Khasi,
    Khoikhoi,
    Khakas,
    Khmer,
    Khmu,
    Kikuyu,
    KinyarwandaSpeakers,
    Kyrgyz,
    Kisii,
    Kalmyk,
    NorthMbundu,
    Kono,
    Kokani,
    Komi,
    Kongo,
    Korean,
    Kosraean,
    Kouyou,
    Kpelle,
    Krahn,
    Karelians,
    Karamojong,
    Kru,
    Kurukh,
    Kwanyama,
    Kumyks,
    Kurd,
    Ktunaxa,
    SephardicJew,
    LakRussia,
    Lamba,
    Lao,
    Lari,
    Latvian,
    Limba,
    LatterDaySaints,
    Lenca,
    Lezgian,
    Lugbara,
    Lahu,
    Li,
    Limburgian,
    Lingala,
    Lithuanian,
    Mongo,
    Lomwe,
    Lovale,
    Lozi,
    Lisu,
    Latoka,
    Latinos,
    Luxembourgers,
    LubaKasai,
    LubaKatanga,
    Luhya,
    Luiseno,
    Lulua,
    Lunda,
    Luo,
    Lusei,
    Macedonian,
    Madurese,
    Mafwe,
    Magahi,
    Marshallese,
    Maithili,
    Makassarese,
    Malayalam,
    Mandinka,
    Maori,
    Marathi,
    Maasai,
    Malays,
    Mbandja,
    Mbere,
    MBaka,
    Mbochi,
    MbunduMestico,
    Mokshas,
    Madhesi,
    Madi,
    Mandar,
    Mende,
    Miao,
    Mikmaq,
    Mijikenda,
    Minangkabau,
    Mizo,
    Mulatto,
    MoleDagbani,
    Malagasy,
    Mulao,
    Maltese,
    Manchu,
    Mande,
    MananjaNayanja,
    Minahasa,
    Manipuri,
    Manjack,
    Mano,
    Lumad,
    Mon,
    Manyika,
    Mohajirs,
    Mohawk,
    Makonde,
    Maonan,
    Mongol,
    Mossi,
    Maronites,
    Moro,
    Miskito,
    Muslim,
    Montenegrins,
    Mestizo,
    Munda,
    Muong,
    Muscogee,
    Mirandese,
    Marwaris,
    Mayangnas,
    Myene,
    Maya,
    Mordvins,
    Naga,
    Nahua,
    NativeAmerican,
    Nama,
    Neapolitan,
    Nauruan,
    Navajo,
    Nakhi,
    Nuba,
    SouthNdebele,
    Nicaraguan,
    NorthernNdebele,
    Ndonga,
    Nepali,
    Nuer,
    Newars,
    Ngbandi,
    Ngoni,
    Niasans,
    Nibolek,
    Niari,
    Niuean,
    Nkomi,
    Nung,
    Nogais,
    Norwegians,
    NorthernSotho,
    Nubian,
    Nuristani,
    Nu,
    Nyakyusa,
    Nyamwezi,
    Ankole,
    Nyoro,
    NewZealanders,
    Nzema,
    Occitanians,
    Ogoni,
    Ojibwe,
    OrthodoxUltraOrthodoxJew,
    Okinawan,
    Oriya,
    Oromo,
    Orgunu,
    Osage,
    Ossetians,
    Otomi,
    Ovambo,
    Papuan,
    PacificIslanders,
    Pangasinan,
    Palestinian,
    Kapampangan,
    Punjabi,
    PapiamentoCreole,
    Paraguayan,
    Palauan,
    Persian,
    AnimistPagan,
    Puthai,
    Panamanians,
    Poles,
    Pomaks,
    Pehnpeian,
    Portuguese,
    Papel,
    Protestant,
    Peruvian,
    Pashayi,
    Pumi,
    Pashtun,
    Qiang,
    Qizilbash,
    Quechua,
    Rajasthani,
    PahariRajput,
    RapaNui,
    CookIslandsMaori,
    UnspecifiedReligion,
    Romansh,
    Romani,
    Romanian,
    Rundi,
    Aromanians,
    Russian,
    Sandawe,
    Sango,
    Yakuts,
    Salish,
    Sara,
    Sasak,
    Sudanese,
    Sicilian,
    Scottish,
    Selkup,
    Sena,
    Sufi,
    Shafii,
    She,
    Shiites,
    Shilluk,
    Shan,
    Shaigiya,
    Sidama,
    Sinhalese,
    Siouan,
    Slavic,
    Slovaks,
    Salar,
    Slovenes,
    Sami,
    Samoans,
    Shona,
    Sindhi,
    Soninke,
    Somali,
    Songhai,
    Sotho,
    Spanish,
    Sardinian,
    SrananTongo,
    Serbs,
    Serer,
    Swazi,
    Sui,
    Sukama,
    Sunni,
    Susu,
    Swahili,
    Swedes,
    SwissFrench,
    SwissItalian,
    Tabasaran,
    Tahitian,
    Tai,
    Tamil,
    Taoist,
    Tatars,
    Tawahka,
    Tay,
    Telugu,
    Temne,
    Terenan,
    Teso,
    Tetum,
    Tajik,
    Tagalog,
    Thai,
    Tigre,
    TigrayTigrinya,
    Tiv,
    Tokelauan,
    Tlingit,
    Tuareg,
    Tama,
    TongaAfrica,
    TongaPacific,
    Tooro,
    Toubou,
    TokPisin,
    Transnistrians,
    Tripuri,
    Ternate,
    Tsimshian,
    Tswana,
    Tsonga,
    Tutsi,
    Tujia,
    Turkmen,
    Tumbuka,
    Tupi,
    Turkish,
    Mongour,
    Tuvaluans,
    Ashanti,
    Taiwanese,
    Tuvans,
    Udmurt,
    Uyghur,
    Ukranian,
    SouthernMbundu,
    Undetermined,
    Urdu,
    Uzbeks,
    Va,
    Vai,
    Venda,
    Vietnamese,
    Vili,
    Venezuelan,
    Votes,
    Wakashan,
    Welayta,
    Waray,
    Washoe,
    Welsch,
    Welsh,
    Sorbs,
    Whites,
    Walloons,
    Wolof,
    Xhosa,
    Xibe,
    Xinca,
    Yao,
    Yapese,
    Yoruba,
    Yupik,
    Yugur,
    Zaghawa,
    Zapotec,
    Zaidiyya,
    Zenaga,
    Zhuang,
    Azande,
    Zomi,
    Zoroastrians,
    Zulu,
    Zuni,
    Zaza,
}

impl TryFrom<CAMEOEthnicityCode> for Ethnicity {
    type Error = anyhow::Error;

    fn try_from(value: CAMEOEthnicityCode) -> anyhow::Result<Self> {
        match std::str::from_utf8(&value.0)? {
            "aar" => Ok(Self::Afar),
            "abk" => Ok(Self::Abkhaz),
            "abr" => Ok(Self::AboriginalAustralians),
            "ace" => Ok(Self::Acehnese),
            "acg" => Ok(Self::Achang),
            "ach" => Ok(Self::Acholi),
            "ada" => Ok(Self::Ga),
            "adi" => Ok(Self::Adivasi),
            "adj" => Ok(Self::Adjarians),
            "ady" => Ok(Self::Adyghe),
            "afa" => Ok(Self::BlackAfrican),
            "afr" => Ok(Self::Afrikaners),
            "ahm" => Ok(Self::Ahmadis),
            "ain" => Ok(Self::Ainu),
            "aja" => Ok(Self::Aja),
            "aka" => Ok(Self::Akan),
            "aku" => Ok(Self::Aku),
            "ala" => Ok(Self::Alawi),
            "alb" => Ok(Self::Albanian),
            "ale" => Ok(Self::Aleut),
            "alg" => Ok(Self::Algonquian),
            "alt" => Ok(Self::Altay),
            "alu" => Ok(Self::Alur),
            "amb" => Ok(Self::Ambonese),
            "ame" => Ok(Self::AmericoLiberians),
            "amh" => Ok(Self::Amhara),
            "anp" => Ok(Self::AngikaSpeakers),
            "apa" => Ok(Self::Apache),
            "ara" => Ok(Self::Arab),
            "ARB" => Ok(Self::Arab),
            "arg" => Ok(Self::Aragonese),
            "arm" => Ok(Self::Armenian),
            "arn" => Ok(Self::Mapuche),
            "arp" => Ok(Self::Arapaho),
            "arw" => Ok(Self::Arawak),
            "asa" => Ok(Self::Asian),
            "ash" => Ok(Self::AshkenaziJews),
            "asm" => Ok(Self::Assamese),
            "ast" => Ok(Self::Asturian),
            "asy" => Ok(Self::Assyrian),
            "ata" => Ok(Self::Atacamenos),
            "atg" => Ok(Self::Argentinians),
            "ath" => Ok(Self::Athabaskan),
            "ats" => Ok(Self::AgnosticAthiest),
            "aus" => Ok(Self::Australians),
            "auu" => Ok(Self::Austrians),
            "ava" => Ok(Self::CaucasianAvars),
            "awa" => Ok(Self::Awadhi),
            "aym" => Ok(Self::Aymara),
            "aze" => Ok(Self::Azerbaijani),
            "bad" => Ok(Self::Baganda),
            "bah" => Ok(Self::Bahais),
            "bai" => Ok(Self::Bamileke),
            "bak" => Ok(Self::Bashkirs),
            "bal" => Ok(Self::Baloch),
            "bam" => Ok(Self::Bambara),
            "ban" => Ok(Self::Balinese),
            "baq" => Ok(Self::Basque),
            "bar" => Ok(Self::Bari),
            "bas" => Ok(Self::Basoga),
            "bay" => Ok(Self::Gbaya),
            "bda" => Ok(Self::Rakhine),
            "bej" => Ok(Self::Beja),
            "bel" => Ok(Self::Belarusians),
            "bem" => Ok(Self::Bemba),
            "ben" => Ok(Self::BengaliHindu),
            "ber" => Ok(Self::Berber),
            "bey" => Ok(Self::Beydan),
            "bho" => Ok(Self::Bhojpuri),
            "bih" => Ok(Self::Bihari),
            "bii" => Ok(Self::Bai),
            "bik" => Ok(Self::Bicolano),
            "bin" => Ok(Self::Edo),
            "bis" => Ok(Self::UrbanniVanautu),
            "bke" => Ok(Self::Bateke),
            "bkn" => Ok(Self::Bakongo),
            "bkw" => Ok(Self::Bakweri),
            "bla" => Ok(Self::Siksikawa),
            "blg" => Ok(Self::Blang),
            "blk" => Ok(Self::Balkars),
            "bln" => Ok(Self::Balanta),
            "bmr" => Ok(Self::Bamar),
            "bni" => Ok(Self::BeniShugalGumez),
            "bnt" => Ok(Self::Bantu),
            "bny" => Ok(Self::Banyarwanda),
            "bod" => Ok(Self::Tibetan),
            "bol" => Ok(Self::Bolivia),
            "bon" => Ok(Self::Bonan),
            "bos" => Ok(Self::Bosniaks),
            "bou" => Ok(Self::Buyei),
            "bra" => Ok(Self::Brijwasi),
            "brb" => Ok(Self::Bariba),
            "bre" => Ok(Self::Breton),
            "brh" => Ok(Self::Brahui),
            "brk" => Ok(Self::Burakumin),
            "brm" => Ok(Self::Kurichiya),
            "bsh" => Ok(Self::Bushmen),
            "bst" => Ok(Self::Baster),
            "bsu" => Ok(Self::Subiya),
            "bte" => Ok(Self::BetiPahuin),
            "btk" => Ok(Self::Batak),
            "bua" => Ok(Self::Buryat),
            "bud" => Ok(Self::Buddhist),
            "bug" => Ok(Self::Bugis),
            "bul" => Ok(Self::Bulgarian),
            "byn" => Ok(Self::Bilen),
            "cab" => Ok(Self::CabindanMayombe),
            "cad" => Ok(Self::Caddo),
            "cap" => Ok(Self::CapeVerdean),
            "car" => Ok(Self::Kalina),
            "cat" => Ok(Self::Catalan),
            "ceb" => Ok(Self::Cebuano),
            "cha" => Ok(Self::Chamorro),
            "chc" => Ok(Self::Chukchi),
            "che" => Ok(Self::Chechen),
            "chg" => Ok(Self::Chagatai),
            "chi" => Ok(Self::Chinese),
            "chk" => Ok(Self::Chuukese),
            "chl" => Ok(Self::Chileans),
            "chm" => Ok(Self::Mari),
            "chn" => Ok(Self::Chinook),
            "cho" => Ok(Self::Choctaw),
            "chp" => Ok(Self::Chipewyan),
            "chr" => Ok(Self::Cherokee),
            "cht" => Ok(Self::Chorti),
            "chv" => Ok(Self::Chuvash),
            "chw" => Ok(Self::Chewa),
            "chy" => Ok(Self::Cheyenne),
            "cir" => Ok(Self::Adyghe),
            "cmc" => Ok(Self::Cham),
            "col" => Ok(Self::Colombian),
            "con" => Ok(Self::Confusian),
            "cop" => Ok(Self::CopticChristians),
            "cor" => Ok(Self::Cornish),
            "cos" => Ok(Self::Corsican),
            "cot" => Ok(Self::Cotiers),
            "cpe" => Ok(Self::EnglishCreole),
            "cpf" => Ok(Self::FrenchCreole),
            "cpp" => Ok(Self::PortugueseCreole),
            "cre" => Ok(Self::Cree),
            "crh" => Ok(Self::CrimeanTatar),
            "cri" => Ok(Self::Christian),
            "cro" => Ok(Self::OrthodoxChristian),
            "crp" => Ok(Self::Creole),
            "csb" => Ok(Self::Kashubian),
            "csr" => Ok(Self::CostaRicans),
            "cth" => Ok(Self::Catholics),
            "cus" => Ok(Self::Cushitic),
            "cze" => Ok(Self::Czech),
            "dai" => Ok(Self::Dai),
            "dak" => Ok(Self::Sioux),
            "dal" => Ok(Self::Dalit),
            "dam" => Ok(Self::Damara),
            "dan" => Ok(Self::Danes),
            "dao" => Ok(Self::YaoAsia),
            "dar" => Ok(Self::Dargwa),
            "dau" => Ok(Self::Daur),
            "day" => Ok(Self::Dayak),
            "del" => Ok(Self::Lenape),
            "den" => Ok(Self::Slavey),
            "dgr" => Ok(Self::Dogrib),
            "din" => Ok(Self::Dinka),
            "div" => Ok(Self::Maldivian),
            "dje" => Ok(Self::DjermaSonghai),
            "doi" => Ok(Self::Dogras),
            "dom" => Ok(Self::Dominicans),
            "don" => Ok(Self::Dong),
            "dox" => Ok(Self::Dongxiang),
            "dra" => Ok(Self::Dravidian),
            "dru" => Ok(Self::Druze),
            "drz" => Ok(Self::Druze),
            "dsb" => Ok(Self::LowerSorbian),
            "dua" => Ok(Self::Duala),
            "dut" => Ok(Self::Dutch),
            "dyu" => Ok(Self::Dyula),
            "dzo" => Ok(Self::Ngalop),
            "eat" => Ok(Self::EastTimorese),
            "ecu" => Ok(Self::Ecuadorians),
            "efi" => Ok(Self::Efik),
            "ein" => Ok(Self::EastIndian),
            "eka" => Ok(Self::Ekajuk),
            "eng" => Ok(Self::English),
            "esh" => Ok(Self::Eshira),
            "est" => Ok(Self::Estonian),
            "eth" => Ok(Self::EthiopianJews),
            "eur" => Ok(Self::Europeans),
            "eve" => Ok(Self::Evenks),
            "ewe" => Ok(Self::Ewe),
            "ewo" => Ok(Self::Ewondo),
            "fan" => Ok(Self::Fang),
            "fao" => Ok(Self::Faroese),
            "fat" => Ok(Self::Fante),
            "fij" => Ok(Self::Fijian),
            "fil" => Ok(Self::Filipino),
            "fin" => Ok(Self::Finns),
            "fiu" => Ok(Self::FinnoUgric),
            "fon" => Ok(Self::Fon),
            "fre" => Ok(Self::French),
            "fri" => Ok(Self::Santals),
            "frr" => Ok(Self::Frisians),
            "fru" => Ok(Self::Fur),
            "ful" => Ok(Self::Fula),
            "fur" => Ok(Self::Friulan),
            "gar" => Ok(Self::Garifuna),
            "gay" => Ok(Self::Gayo),
            "gba" => Ok(Self::Gbaya),
            "gel" => Ok(Self::Gelao),
            "geo" => Ok(Self::Georgian),
            "ger" => Ok(Self::German),
            "gia" => Ok(Self::GiaRai),
            "gil" => Ok(Self::Kiribati),
            "gin" => Ok(Self::Gin),
            "gio" => Ok(Self::Gio),
            "gla" => Ok(Self::Gaels),
            "gle" => Ok(Self::Irish),
            "glg" => Ok(Self::Galician),
            "glv" => Ok(Self::Manx),
            "gon" => Ok(Self::Gondi),
            "gor" => Ok(Self::Gorontalonese),
            "gra" => Ok(Self::Grassfielders),
            "grb" => Ok(Self::Grebo),
            "gre" => Ok(Self::Greek),
            "grn" => Ok(Self::Guarani),
            "gsw" => Ok(Self::SwissGermans),
            "gua" => Ok(Self::Guatemalan),
            "guj" => Ok(Self::Gujarati),
            "gun" => Ok(Self::Guan),
            "gwi" => Ok(Self::Gwichin),
            "had" => Ok(Self::Hadjerai),
            "hai" => Ok(Self::Haida),
            "har" => Ok(Self::Harari),
            "hat" => Ok(Self::Haitian),
            "hau" => Ok(Self::Hausa),
            "haw" => Ok(Self::Hawaiian),
            "haz" => Ok(Self::Hazara),
            "her" => Ok(Self::Herero),
            "hgh" => Ok(Self::HillTribes),
            "hil" => Ok(Self::Hiligayon),
            "him" => Ok(Self::Himachali),
            "hin" => Ok(Self::Hindu),
            "hjw" => Ok(Self::Hasidic),
            "hmn" => Ok(Self::Hmong),
            "hmo" => Ok(Self::HiriMotu),
            "hni" => Ok(Self::Hani),
            "hoa" => Ok(Self::Hoa),
            "hon" => Ok(Self::Hondurans),
            "hrt" => Ok(Self::Haratin),
            "hrv" => Ok(Self::Croats),
            "hsb" => Ok(Self::UpperSorbian),
            "hui" => Ok(Self::Hui),
            "hun" => Ok(Self::Hungarian),
            "hup" => Ok(Self::Hupa),
            "hut" => Ok(Self::Hutu),
            "iba" => Ok(Self::Iban),
            "ibo" => Ok(Self::Igbo),
            "ice" => Ok(Self::Icelanders),
            "idg" => Ok(Self::Indigenous),
            "idn" => Ok(Self::Indian),
            "iii" => Ok(Self::Yi),
            "ijo" => Ok(Self::Ijaw),
            "iku" => Ok(Self::Inuit),
            "ilo" => Ok(Self::Ilocono),
            "ind" => Ok(Self::Indonesian),
            "inh" => Ok(Self::Ingush),
            "ipk" => Ok(Self::Inupiat),
            "ira" => Ok(Self::Iranian),
            "iro" => Ok(Self::Iroquois),
            "ita" => Ok(Self::Itallian),
            "jan" => Ok(Self::Jain),
            "jav" => Ok(Self::Javanese),
            "jew" => Ok(Self::Jewish),
            "jhw" => Ok(Self::JehovahsWitnesses),
            "jin" => Ok(Self::Jino),
            "jol" => Ok(Self::Jola),
            "jpn" => Ok(Self::Japanese),
            "kaa" => Ok(Self::Karakalpak),
            "kab" => Ok(Self::Kabyle),
            "kac" => Ok(Self::Kachin),
            "kad" => Ok(Self::Kadazan),
            "kak" => Ok(Self::KakwaNubian),
            "kal" => Ok(Self::Kalaallit),
            "kam" => Ok(Self::Kamba),
            "kan" => Ok(Self::Kannada),
            "kao" => Ok(Self::Kaonde),
            "kar" => Ok(Self::Karen),
            "kas" => Ok(Self::Kashmiri),
            "kau" => Ok(Self::Kanuri),
            "kav" => Ok(Self::Kavango),
            "kaz" => Ok(Self::Kazakhs),
            "kbd" => Ok(Self::Kabarday),
            "kby" => Ok(Self::Kabye),
            "kch" => Ok(Self::Karachays),
            "kha" => Ok(Self::Khasi),
            "khi" => Ok(Self::Khoikhoi),
            "khk" => Ok(Self::Khakas),
            "khm" => Ok(Self::Khmer),
            "khu" => Ok(Self::Khmu),
            "kik" => Ok(Self::Kikuyu),
            "kin" => Ok(Self::KinyarwandaSpeakers),
            "kir" => Ok(Self::Kyrgyz),
            "kis" => Ok(Self::Kisii),
            "klm" => Ok(Self::Kalmyk),
            "kmb" => Ok(Self::NorthMbundu),
            "kno" => Ok(Self::Kono),
            "knr" => Ok(Self::Kanuri),
            "kok" => Ok(Self::Kokani),
            "kom" => Ok(Self::Komi),
            "kon" => Ok(Self::Kongo),
            "kor" => Ok(Self::Korean),
            "kos" => Ok(Self::Kosraean),
            "kou" => Ok(Self::Kouyou),
            "kpe" => Ok(Self::Kpelle),
            "krh" => Ok(Self::Krahn),
            "krl" => Ok(Self::Karelians),
            "krm" => Ok(Self::Karamojong),
            "kro" => Ok(Self::Kru),
            "kru" => Ok(Self::Kurukh),
            "kua" => Ok(Self::Kwanyama),
            "kum" => Ok(Self::Kumyks),
            "kur" => Ok(Self::Kurd),
            "KUR" => Ok(Self::Kurd),
            "kut" => Ok(Self::Ktunaxa),
            "lad" => Ok(Self::SephardicJew),
            "lak" => Ok(Self::LakRussia),
            "lam" => Ok(Self::Lamba),
            "lao" => Ok(Self::Lao),
            "lar" => Ok(Self::Lari),
            "lav" => Ok(Self::Latvian),
            "lba" => Ok(Self::Limba),
            "lds" => Ok(Self::LatterDaySaints),
            "len" => Ok(Self::Lenca),
            "lez" => Ok(Self::Lezgian),
            "lgb" => Ok(Self::Lugbara),
            "lhu" => Ok(Self::Lahu),
            "lii" => Ok(Self::Li),
            "lim" => Ok(Self::Limburgian),
            "lin" => Ok(Self::Lingala),
            "lit" => Ok(Self::Lithuanian),
            "lol" => Ok(Self::Mongo),
            "lom" => Ok(Self::Lomwe),
            "lov" => Ok(Self::Lovale),
            "loz" => Ok(Self::Lozi),
            "lsu" => Ok(Self::Lisu),
            "ltk" => Ok(Self::Latoka),
            "ltn" => Ok(Self::Latinos),
            "ltz" => Ok(Self::Luxembourgers),
            "lua" => Ok(Self::LubaKasai),
            "lub" => Ok(Self::LubaKatanga),
            "lug" => Ok(Self::Baganda),
            "luh" => Ok(Self::Luhya),
            "lui" => Ok(Self::Luiseno),
            "lul" => Ok(Self::Lulua),
            "lun" => Ok(Self::Lunda),
            "luo" => Ok(Self::Luo),
            "lus" => Ok(Self::Lusei),
            "mac" => Ok(Self::Macedonian),
            "mad" => Ok(Self::Madurese),
            "maf" => Ok(Self::Mafwe),
            "mag" => Ok(Self::Magahi),
            "mah" => Ok(Self::Marshallese),
            "mai" => Ok(Self::Maithili),
            "mak" => Ok(Self::Makassarese),
            "mal" => Ok(Self::Malayalam),
            "man" => Ok(Self::Mandinka),
            "mao" => Ok(Self::Maori),
            "mar" => Ok(Self::Marathi),
            "mas" => Ok(Self::Maasai),
            "may" => Ok(Self::Malays),
            "mba" => Ok(Self::Mbandja),
            "mbe" => Ok(Self::Mbere),
            "mbk" => Ok(Self::MBaka),
            "mbo" => Ok(Self::Mbochi),
            "mbu" => Ok(Self::MbunduMestico),
            "mdf" => Ok(Self::Mokshas),
            "mdh" => Ok(Self::Madhesi),
            "mdi" => Ok(Self::Madi),
            "mdr" => Ok(Self::Mandar),
            "men" => Ok(Self::Mende),
            "mia" => Ok(Self::Miao),
            "mic" => Ok(Self::Mikmaq),
            "mij" => Ok(Self::Mijikenda),
            "min" => Ok(Self::Minangkabau),
            "miz" => Ok(Self::Mizo),
            "mla" => Ok(Self::Mulatto),
            "mld" => Ok(Self::MoleDagbani),
            "mlg" => Ok(Self::Malagasy),
            "mlo" => Ok(Self::Mulao),
            "mlt" => Ok(Self::Maltese),
            "mnc" => Ok(Self::Manchu),
            "mnd" => Ok(Self::Mande),
            "mng" => Ok(Self::MananjaNayanja),
            "mnh" => Ok(Self::Minahasa),
            "mni" => Ok(Self::Manipuri),
            "mnj" => Ok(Self::Manjack),
            "mnn" => Ok(Self::Mano),
            "mno" => Ok(Self::Lumad),
            "mns" => Ok(Self::Mon),
            "mny" => Ok(Self::Manyika),
            "moh" => Ok(Self::Mohawk),
            "mok" => Ok(Self::Makonde),
            "mon" => Ok(Self::Mongol),
            "mos" => Ok(Self::Mossi),
            "mri" => Ok(Self::Mari),
            "mrn" => Ok(Self::Maronites),
            "mro" => Ok(Self::Moro),
            "msk" => Ok(Self::Miskito),
            "msl" => Ok(Self::Muslim),
            "mtn" => Ok(Self::Montenegrins),
            "mtz" => Ok(Self::Mestizo),
            "mun" => Ok(Self::Munda),
            "muo" => Ok(Self::Muong),
            "mus" => Ok(Self::Muscogee),
            "mwl" => Ok(Self::Mirandese),
            "mwr" => Ok(Self::Marwaris),
            "mya" => Ok(Self::Mayangnas),
            "mye" => Ok(Self::Myene),
            "myn" => Ok(Self::Maya),
            "myv" => Ok(Self::Mordvins),
            "nag" => Ok(Self::Naga),
            "nah" => Ok(Self::Nahua),
            "nai" => Ok(Self::NativeAmerican),
            "nam" => Ok(Self::Nama),
            "nap" => Ok(Self::Neapolitan),
            "nau" => Ok(Self::Nauruan),
            "nav" => Ok(Self::Navajo),
            "nax" => Ok(Self::Nakhi),
            "nba" => Ok(Self::Nuba),
            "nbl" => Ok(Self::SouthNdebele),
            "nca" => Ok(Self::Nicaraguan),
            "nde" => Ok(Self::NorthernNdebele),
            "ndo" => Ok(Self::Ndonga),
            "nep" => Ok(Self::Nepali),
            "ner" => Ok(Self::Nuer),
            "new" => Ok(Self::Newars),
            "ngn" => Ok(Self::Ngbandi),
            "ngo" => Ok(Self::Ngoni),
            "nia" => Ok(Self::Niasans),
            "nib" => Ok(Self::Nibolek),
            "nir" => Ok(Self::Niari),
            "niu" => Ok(Self::Niuean),
            "nkm" => Ok(Self::Nkomi),
            "nng" => Ok(Self::Nung),
            "nog" => Ok(Self::Nogais),
            "nor" => Ok(Self::Norwegians),
            "nso" => Ok(Self::NorthernSotho),
            "nub" => Ok(Self::Nubian),
            "nur" => Ok(Self::Nuristani),
            "nuu" => Ok(Self::Nu),
            "nya" => Ok(Self::Chewa),
            "nyk" => Ok(Self::Nyakyusa),
            "nym" => Ok(Self::Nyamwezi),
            "nyn" => Ok(Self::Ankole),
            "nyo" => Ok(Self::Nyoro),
            "nze" => Ok(Self::NewZealanders),
            "nzi" => Ok(Self::Nzema),
            "oci" => Ok(Self::Occitanians),
            "ogo" => Ok(Self::Ogoni),
            "oji" => Ok(Self::Ojibwe),
            "ojw" => Ok(Self::OrthodoxUltraOrthodoxJew),
            "oki" => Ok(Self::Okinawan),
            "ori" => Ok(Self::Oriya),
            "orm" => Ok(Self::Oromo),
            "oru" => Ok(Self::Orgunu),
            "osa" => Ok(Self::Osage),
            "oss" => Ok(Self::Ossetians),
            "oto" => Ok(Self::Otomi),
            "ova" => Ok(Self::Ovambo),
            "paa" => Ok(Self::Papuan),
            "pac" => Ok(Self::PacificIslanders),
            "pag" => Ok(Self::Pangasinan),
            "pal" => Ok(Self::Palestinian),
            "PAL" => Ok(Self::Palestinian),
            "pam" => Ok(Self::Kapampangan),
            "pan" => Ok(Self::Punjabi),
            "pap" => Ok(Self::PapiamentoCreole),
            "par" => Ok(Self::Paraguayan),
            "pau" => Ok(Self::Palauan),
            "per" => Ok(Self::Persian),
            "pgn" => Ok(Self::AnimistPagan),
            "phu" => Ok(Self::Puthai),
            "pnm" => Ok(Self::Panamanians),
            "pol" => Ok(Self::Poles),
            "pom" => Ok(Self::Pomaks),
            "pon" => Ok(Self::Pehnpeian),
            "por" => Ok(Self::Portuguese),
            "ppl" => Ok(Self::Papel),
            "pro" => Ok(Self::Protestant),
            "pru" => Ok(Self::Peruvian),
            "psh" => Ok(Self::Pashayi),
            "pum" => Ok(Self::Pumi),
            "pus" => Ok(Self::Pashtun),
            "qia" => Ok(Self::Qiang),
            "qiz" => Ok(Self::Qizilbash),
            "que" => Ok(Self::Quechua),
            "raj" => Ok(Self::Rajasthani),
            "ran" => Ok(Self::PahariRajput),
            "rap" => Ok(Self::RapaNui),
            "rar" => Ok(Self::CookIslandsMaori),
            "rel" => Ok(Self::UnspecifiedReligion),
            "roh" => Ok(Self::Romansh),
            "rom" => Ok(Self::Romani),
            "rum" => Ok(Self::Romanian),
            "run" => Ok(Self::Rundi),
            "rup" => Ok(Self::Aromanians),
            "rus" => Ok(Self::Russian),
            "sad" => Ok(Self::Sandawe),
            "sag" => Ok(Self::Sango),
            "sah" => Ok(Self::Yakuts),
            "sal" => Ok(Self::Salish),
            "sar" => Ok(Self::Sara),
            "sas" => Ok(Self::Sasak),
            "sat" => Ok(Self::Sudanese),
            "scn" => Ok(Self::Sicilian),
            "sco" => Ok(Self::Scottish),
            "sel" => Ok(Self::Selkup),
            "sen" => Ok(Self::Sena),
            "sfi" => Ok(Self::Sufi),
            "sha" => Ok(Self::Shafii),
            "she" => Ok(Self::She),
            "shi" => Ok(Self::Shiites),
            "shl" => Ok(Self::Shilluk),
            "shn" => Ok(Self::Shan),
            "shy" => Ok(Self::Shaigiya),
            "sid" => Ok(Self::Sidama),
            "sin" => Ok(Self::Sinhalese),
            "sio" => Ok(Self::Siouan),
            "sla" => Ok(Self::Slavic),
            "slo" => Ok(Self::Slovaks),
            "slr" => Ok(Self::Salar),
            "slv" => Ok(Self::Slovenes),
            "smi" => Ok(Self::Sami),
            "smo" => Ok(Self::Samoans),
            "sna" => Ok(Self::Shona),
            "snd" => Ok(Self::Sindhi),
            "snk" => Ok(Self::Soninke),
            "som" => Ok(Self::Somali),
            "son" => Ok(Self::Songhai),
            "sot" => Ok(Self::Sotho),
            "spa" => Ok(Self::Spanish),
            "srd" => Ok(Self::Sardinian),
            "srn" => Ok(Self::SrananTongo),
            "srp" => Ok(Self::Serbs),
            "srr" => Ok(Self::Serer),
            "ssw" => Ok(Self::Swazi),
            "sui" => Ok(Self::Sui),
            "suk" => Ok(Self::Sukama),
            "sun" => Ok(Self::Sunni),
            "sus" => Ok(Self::Susu),
            "swa" => Ok(Self::Swahili),
            "swe" => Ok(Self::Swedes),
            "swf" => Ok(Self::SwissFrench),
            "swt" => Ok(Self::SwissItalian),
            "tab" => Ok(Self::Tabasaran),
            "tah" => Ok(Self::Tahitian),
            "tai" => Ok(Self::Tai),
            "tam" => Ok(Self::Tamil),
            "tao" => Ok(Self::Taoist),
            "tat" => Ok(Self::Tatars),
            "taw" => Ok(Self::Tawahka),
            "tay" => Ok(Self::Tay),
            "tel" => Ok(Self::Telugu),
            "tem" => Ok(Self::Temne),
            "ter" => Ok(Self::Terenan),
            "tes" => Ok(Self::Teso),
            "tet" => Ok(Self::Tetum),
            "tgk" => Ok(Self::Tajik),
            "tgl" => Ok(Self::Tagalog),
            "tha" => Ok(Self::Thai),
            "tib" => Ok(Self::Tibetan),
            "tig" => Ok(Self::Tigre),
            "tir" => Ok(Self::TigrayTigrinya),
            "tiv" => Ok(Self::Tiv),
            "tkl" => Ok(Self::Tokelauan),
            "tli" => Ok(Self::Tlingit),
            "tmh" => Ok(Self::Tuareg),
            "tms" => Ok(Self::Tama),
            "tog" => Ok(Self::TongaAfrica),
            "ton" => Ok(Self::TongaPacific),
            "tor" => Ok(Self::Tooro),
            "tou" => Ok(Self::Toubou),
            "tpi" => Ok(Self::TokPisin),
            "tra" => Ok(Self::Transnistrians),
            "tri" => Ok(Self::Tripuri),
            "trn" => Ok(Self::Ternate),
            "tsi" => Ok(Self::Tsimshian),
            "tsn" => Ok(Self::Tswana),
            "tso" => Ok(Self::Tsonga),
            "tts" => Ok(Self::Tutsi),
            "tuj" => Ok(Self::Tujia),
            "tuk" => Ok(Self::Turkmen),
            "tum" => Ok(Self::Tumbuka),
            "tup" => Ok(Self::Tupi),
            "tur" => Ok(Self::Turkish),
            "tuu" => Ok(Self::Mongour),
            "tvl" => Ok(Self::Tuvaluans),
            "twi" => Ok(Self::Ashanti),
            "twn" => Ok(Self::Taiwanese),
            "tyv" => Ok(Self::Tuvans),
            "udm" => Ok(Self::Udmurt),
            "uig" => Ok(Self::Uyghur),
            "ukr" => Ok(Self::Ukranian),
            "umb" => Ok(Self::SouthernMbundu),
            "und" => Ok(Self::Undetermined),
            "urd" => Ok(Self::Urdu),
            "uzb" => Ok(Self::Uzbeks),
            "vaa" => Ok(Self::Va),
            "vai" => Ok(Self::Vai),
            "ven" => Ok(Self::Venda),
            "vie" => Ok(Self::Vietnamese),
            "vil" => Ok(Self::Vili),
            "vnz" => Ok(Self::Venezuelan),
            "vot" => Ok(Self::Votes),
            "wak" => Ok(Self::Wakashan),
            "wal" => Ok(Self::Welayta),
            "war" => Ok(Self::Waray),
            "was" => Ok(Self::Washoe),
            "wel" => Ok(Self::Welsch),
            "wen" => Ok(Self::Sorbs),
            "whi" => Ok(Self::Whites),
            "wln" => Ok(Self::Walloons),
            "wol" => Ok(Self::Wolof),
            "xal" => Ok(Self::Kalmyk),
            "xho" => Ok(Self::Xhosa),
            "xib" => Ok(Self::Xibe),
            "xnc" => Ok(Self::Xinca),
            "yao" => Ok(Self::Yao),
            "yap" => Ok(Self::Yapese),
            "yor" => Ok(Self::Yoruba),
            "ypk" => Ok(Self::Yupik),
            "yug" => Ok(Self::Yugur),
            "zag" => Ok(Self::Zaghawa),
            "zap" => Ok(Self::Zapotec),
            "zay" => Ok(Self::Zaidiyya),
            "zen" => Ok(Self::Zenaga),
            "zha" => Ok(Self::Zhuang),
            "znd" => Ok(Self::Azande),
            "zom" => Ok(Self::Zomi),
            "zor" => Ok(Self::Zoroastrians),
            "zul" => Ok(Self::Zulu),
            "zun" => Ok(Self::Zuni),
            "zza" => Ok(Self::Zaza),
            _ => Err(anyhow!("Invalid Ethnicity Code")),
        }
    }
}
