#!/usr/bin/env python3
"""
Generate a Rust static HashMap from the GCAM Master Codebook CSV.

This script reads the GCAM Master Codebook CSV file and generates a Rust source file
containing a compile-time initialized HashMap using phf (perfect hash function).
The generated file should be feature-gated due to its large size.

Usage:
    python3 scripts/generate_gcam_hashmap.py [input_csv] [output_rs]
"""

import csv
import sys
from pathlib import Path
from typing import List, Tuple


def sanitize_rust_string(s: str) -> str:
    """Escape special characters in strings for Rust."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')


def generate_rust_code(csv_path: Path, output_path: Path):
    """Generate Rust code from GCAM codebook CSV."""

    print(f"Reading GCAM codebook from: {csv_path}")

    entries: List[Tuple[str, str, str, str, str, str, str, str]] = []

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f, delimiter='\t')
        for row in reader:
            variable = row['Variable']
            dictionary_id = row['DictionaryID']
            dimension_id = row['DimensionID']
            measurement_type = row['Type']
            language_code = row['LanguageCode']
            dictionary_name = row['DictionaryHumanName']
            dimension_name = row['DimensionHumanName']
            citation = row['DictionaryCitation']

            entries.append((
                variable,
                dictionary_id,
                dimension_id,
                measurement_type,
                language_code,
                dictionary_name,
                dimension_name,
                citation
            ))

    print(f"Loaded {len(entries)} GCAM codebook entries")
    print(f"Generating Rust code to: {output_path}")

    # Generate the Rust source file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("""//! GCAM Codebook Static HashMap
//!
//! This file is auto-generated from the GCAM Master Codebook CSV.
//! DO NOT EDIT THIS FILE MANUALLY.
//!
//! Generated by: scripts/generate_gcam_hashmap.py
//!
//! This module provides a compile-time initialized HashMap for GCAM codebook lookups.
//! Due to the large size of this data, it is feature-gated behind the `gcam-hashmap` feature.

use phf::phf_map;

/// GCAM Codebook entry metadata
#[derive(Debug, Clone, Copy)]
pub struct GCAMCodebookEntry {
    pub variable: &'static str,
    pub dictionary_id: u32,
    pub dimension_id: u32,
    pub measurement_type: &'static str,
    pub language_code: &'static str,
    pub dictionary_name: &'static str,
    pub dimension_name: &'static str,
    pub citation: &'static str,
}

impl GCAMCodebookEntry {
    pub const fn new(
        variable: &'static str,
        dictionary_id: u32,
        dimension_id: u32,
        measurement_type: &'static str,
        language_code: &'static str,
        dictionary_name: &'static str,
        dimension_name: &'static str,
        citation: &'static str,
    ) -> Self {
        Self {
            variable,
            dictionary_id,
            dimension_id,
            measurement_type,
            language_code,
            dictionary_name,
            dimension_name,
            citation,
        }
    }
}

/// Static compile-time HashMap of GCAM codebook entries
///
/// This uses a perfect hash function (phf) for O(1) lookup performance
/// with zero runtime initialization cost.
pub static GCAM_CODEBOOK: phf::Map<&'static str, GCAMCodebookEntry> = phf_map! {
""")

        # Write all entries
        for i, (variable, dict_id, dim_id, mtype, lang, dict_name, dim_name, cite) in enumerate(entries):
            # Sanitize strings
            variable_safe = sanitize_rust_string(variable)
            mtype_safe = sanitize_rust_string(mtype)
            lang_safe = sanitize_rust_string(lang)
            dict_name_safe = sanitize_rust_string(dict_name)
            dim_name_safe = sanitize_rust_string(dim_name)
            cite_safe = sanitize_rust_string(cite)

            # Write the entry
            f.write(f'    "{variable_safe}" => GCAMCodebookEntry::new(\n')
            f.write(f'        "{variable_safe}",\n')
            f.write(f'        {dict_id},\n')
            f.write(f'        {dim_id},\n')
            f.write(f'        "{mtype_safe}",\n')
            f.write(f'        "{lang_safe}",\n')
            f.write(f'        "{dict_name_safe}",\n')
            f.write(f'        "{dim_name_safe}",\n')
            f.write(f'        "{cite_safe}",\n')
            f.write(f'    )')

            # Add comma if not the last entry
            if i < len(entries) - 1:
                f.write(',')

            f.write('\n')

        # Close the phf_map
        f.write("""};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gcam_codebook_lookup() {
        // Test that we can look up a known entry
        let entry = GCAM_CODEBOOK.get("c1.1");
        assert!(entry.is_some(), "Should find c1.1 in codebook");

        let entry = entry.unwrap();
        assert_eq!(entry.variable, "c1.1");
        assert_eq!(entry.dictionary_id, 1);
        assert_eq!(entry.dimension_id, 1);
    }

    #[test]
    fn test_gcam_codebook_count() {
        // Verify we loaded all entries
        assert_eq!(GCAM_CODEBOOK.len(), """ + str(len(entries)) + """);
    }

    #[test]
    fn test_gcam_codebook_iteration() {
        // Test that we can iterate over all entries
        let mut count = 0;
        for (key, entry) in GCAM_CODEBOOK.entries() {
            assert_eq!(key, &entry.variable);
            count += 1;
        }
        assert_eq!(count, GCAM_CODEBOOK.len());
    }
}
""")

    print(f"✅ Successfully generated Rust code with {len(entries)} entries")
    print(f"   Output file size: {output_path.stat().st_size:,} bytes")


def main():
    """Main entry point."""
    if len(sys.argv) > 1:
        input_csv = Path(sys.argv[1])
    else:
        input_csv = Path(__file__).parent.parent / "GCAM-MASTER-CODEBOOK-fixed.csv"

    if len(sys.argv) > 2:
        output_rs = Path(sys.argv[2])
    else:
        output_rs = Path(__file__).parent.parent / "models" / "src" / "gcam" / "static_hashmap.rs"

    if not input_csv.exists():
        print(f"❌ Error: Input CSV file not found: {input_csv}")
        sys.exit(1)

    # Create output directory if it doesn't exist
    output_rs.parent.mkdir(parents=True, exist_ok=True)

    generate_rust_code(input_csv, output_rs)

    print("\n✅ Done! To use this in your code:")
    print("   1. Add 'phf = { version = \"0.11\", features = [\"macros\"] }' to Cargo.toml")
    print("   2. Add a feature gate '[features]' with 'gcam-hashmap = []'")
    print("   3. In your mod.rs, add: #[cfg(feature = \"gcam-hashmap\")] pub mod static_hashmap;")
    print("   4. Build with: cargo build --features gcam-hashmap")


if __name__ == "__main__":
    main()
