use std::str;

use crate::components::base_components::raw_types::{CAMEOCountryCode, location::FIPSCountryCode};

pub enum CountryZone {
    Unspecified,
    WestBank,
    Baghdad,
    GazaStrip,
    Africa,
    Asia,
    Balkans,
    Caribbean,
    Caucasus,
    CentralAfrica,
    CentralAsia,
    CentralEurope,
    EastIndies,
    EasternAfrica,
    EasternEurope,
    Europe,
    LatinAmerica,
    MiddleEast,
    Mediterranean,
    NorthAfrica,
    NorthAmerica,
    PersianGulf,
    Scandinavia,
    SouthAmerica,
    SouthAsia,
    SoutheastAsia,
    SouthernAfrica,
    WestAfrica,
    TheWest,
    Afghanistan,
    AlandIslands,
    Albania,
    Algeria,
    AmericanSamoa,
    Andorra,
    Angola,
    Anguilla,
    AntiguaandBarbuda,
    Argentina,
    Armenia,
    Aruba,
    Australia,
    Austria,
    Azerbaijan,
    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bermuda,
    Bhutan,
    Bolivia,
    BosniaandHerzegovina,
    Botswana,
    Brazil,
    BritishVirginIslands,
    BruneiDarussalam,
    Bulgaria,
    BurkinaFaso,
    Burundi,
    Cambodia,
    Cameroon,
    Canada,
    CapeVerde,
    CaymanIslands,
    CentralAfricanRepublic,
    Chad,
    Chile,
    China,
    Columbia,
    Comoros,
    DemocraticRepublicoftheCongo,
    PeoplesRepublicoftheCongo,
    CookIslands,
    CostaRica,
    IvoryCoast,
    Croatia,
    Cuba,
    Cyprus,
    CzechRepublic,
    Denmark,
    Djibouti,
    Dominica,
    DominicanRepublic,
    EastTimor,
    Ecuador,
    Egypt,
    ElSalvador,
    EquatorialGuinea,
    Eritrea,
    Estonia,
    Ethiopia,
    FaeroeIslands,
    FalklandIslands,
    Fiji,
    Finland,
    France,
    FrenchGuiana,
    FrenchPolynesia,
    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Gibraltar,
    Greece,
    Greenland,
    Grenada,
    Guadeloupe,
    Guam,
    Guatemala,
    Guinea,
    GuineaBissau,
    Guyana,
    Haiti,
    VaticanCity,
    Honduras,
    HongKong,
    Hungary,
    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    IsleofMan,
    Israel,
    Italy,
    Jamaica,
    Japan,
    Jordan,
    Kazakhstan,
    Kenya,
    Kiribati,
    NorthKorea,
    SouthKorea,
    Kuwait,
    Kyrgyzstan,
    Laos,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Macao,
    Macedonia,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    MarshallIslands,
    Martinique,
    Mauritania,
    Mauritius,
    Mayotte,
    Mexico,
    Micronesia,
    Moldova,
    Monaco,
    Mongolia,
    Montenegro,
    Montserrat,
    Morocco,
    Mozambique,
    Myanmar,
    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    NetherlandsAntilles,
    NewCaledonia,
    NewZealand,
    Nicaragua,
    Niger,
    Nigeria,
    Niue,
    NorfolkIsland,
    NorthernMarianaIslands,
    Norway,
    OccupiedPalestinianTerritory,
    Oman,
    Pakistan,
    Palau,
    Panama,
    PapuaNewGuinea,
    Paraguay,
    Peru,
    Philippines,
    Pitcairn,
    Poland,
    Portugal,
    PuertoRico,
    Qatar,
    Runion,
    Romania,
    Russia,
    Rwanda,
    SaintHelena,
    SaintKittsNevis,
    SaintLucia,
    SaintPierreandMiquelon,
    SaintVincentandtheGrenadines,
    Samoa,
    SanMarino,
    SaoTomeandPrincipe,
    SaudiArabia,
    Senegal,
    Serbia,
    Seychelles,
    SierraLeone,
    Singapore,
    Slovakia,
    Slovenia,
    SolomonIslands,
    Somalia,
    SouthAfrica,
    Spain,
    SriLanka,
    Sudan,
    Suriname,
    SvalbardandJanMayenIslands,
    Swaziland,
    Sweden,
    Switzerland,
    Syria,
    Taiwan,
    Tajikistan,
    Tanzania,
    Thailand,
    Togo,
    Tokelau,
    Tonga,
    TrinidadandTobago,
    Tunisia,
    Turkey,
    Turkmenistan,
    TurksandCaicosIslands,
    Tuvalu,
    Uganda,
    Ukraine,
    UnitedArabEmirates,
    UnitedKingdom,
    UnitedStates,
    UnitedStatesVirginIslands,
    Uruguay,
    Uzbekistan,
    Vanuatu,
    Venezuela,
    Vietnam,
    WallisandFutunaIslands,
    WesternSahara,
    Yemen,
    Zambia,
    Zimbabwe,

    AkrotiriSovereignBaseArea,
    Antarctica,
    AshmoreandCartierIslands,

    BahamasThe,
    BakerIsland,
    BassasdaIndia,
    BosniaHerzegovina,
    BouvetIsland,
    BritishIndianOceanTerritory,
    Brunei,
    ChristmasIsland,
    ClippertonIsland,
    CocosKeelingIslands,
    Colombia,
    Congo,
    CoralSeaIslands,
    CotedIvoire,
    Czechoslovakia,
    DhekeliaSovereignBaseArea,
    EtorofuHabomaiKunashiriandShikotanIslands,
    EuropaIsland,
    FalklandIslandsIslasMalvinas,
    FaroeIslands,
    FrenchSouthernandAntarcticLands,
    GloriosoIslands,
    Guernsey,
    HeardIslandandMcDonaldIslands,
    HowlandIsland,
    JanMayen,
    JarvisIsland,
    Jersey,
    JohnstonAtoll,
    JuandeNovaIsland,
    KingmanReef,
    Kosovo,
    Macau,
    MidwayIslands,
    NavassaIsland,
    NoMansLand,
    Oceans,
    PalmyraAtoll,
    ParacelIslands,
    PitcairnIslands,
    Reunion,
    SaintKittsandNevis,
    SaintMartin,
    SaintBarthelemyIsland,
    SouthGeorgiaandtheSouthSandwichIslands,
    SouthSudan,
    SpratlyIslands,
    Svalbard,
    TromelinIsland,
    UnderseaFeatures,
    UndesignatedSovereignty,
    VietnamDemocraticRepublicof,
    VirginIslands,
    WakeIsland,
    WallisandFutuna,
}

impl From<FIPSCountryCode> for CountryZone {
    fn from(value: FIPSCountryCode) -> Self {
        let str_value = std::str::from_utf8(&value.0).expect("Invalid FIPS Code format");
        match str_value {
            "AF" => CountryZone::Afghanistan,
            "AX" => CountryZone::AkrotiriSovereignBaseArea,
            "AL" => CountryZone::Albania,
            "AG" => CountryZone::Algeria,
            "AQ" => CountryZone::AmericanSamoa,
            "AN" => CountryZone::Andorra,
            "AO" => CountryZone::Angola,
            "AV" => CountryZone::Anguilla,
            "AY" => CountryZone::Antarctica,
            "AC" => CountryZone::AntiguaandBarbuda,
            "AR" => CountryZone::Argentina,
            "AM" => CountryZone::Armenia,
            "AA" => CountryZone::Aruba,
            "AT" => CountryZone::AshmoreandCartierIslands,
            "AS" => CountryZone::Australia,
            "AU" => CountryZone::Austria,
            "AJ" => CountryZone::Azerbaijan,
            "BF" => CountryZone::BahamasThe,
            "BA" => CountryZone::Bahrain,
            "FQ" => CountryZone::BakerIsland,
            "BG" => CountryZone::Bangladesh,
            "BB" => CountryZone::Barbados,
            "BS" => CountryZone::BassasdaIndia,
            "BO" => CountryZone::Belarus,
            "BE" => CountryZone::Belgium,
            "BH" => CountryZone::Belize,
            "BN" => CountryZone::Benin,
            "BD" => CountryZone::Bermuda,
            "BT" => CountryZone::Bhutan,
            "BL" => CountryZone::Bolivia,
            "BK" => CountryZone::BosniaHerzegovina,
            "BC" => CountryZone::Botswana,
            "BV" => CountryZone::BouvetIsland,
            "BR" => CountryZone::Brazil,
            "IO" => CountryZone::BritishIndianOceanTerritory,
            "VI" => CountryZone::BritishVirginIslands,
            "BX" => CountryZone::Brunei,
            "BU" => CountryZone::Bulgaria,
            "UV" => CountryZone::BurkinaFaso,
            "BY" => CountryZone::Burundi,
            "CB" => CountryZone::Cambodia,
            "CM" => CountryZone::Cameroon,
            "CA" => CountryZone::Canada,
            "CV" => CountryZone::CapeVerde,
            "CJ" => CountryZone::CaymanIslands,
            "CT" => CountryZone::CentralAfricanRepublic,
            "CD" => CountryZone::Chad,
            "CI" => CountryZone::Chile,
            "CH" => CountryZone::China,
            "KT" => CountryZone::ChristmasIsland,
            "IP" => CountryZone::ClippertonIsland,
            "CK" => CountryZone::CocosKeelingIslands,
            "CO" => CountryZone::Colombia,
            "CN" => CountryZone::Comoros,
            "CF" => CountryZone::Congo,
            "CW" => CountryZone::CookIslands,
            "CR" => CountryZone::CoralSeaIslands,
            "CS" => CountryZone::CostaRica,
            "IV" => CountryZone::CotedIvoire,
            "HR" => CountryZone::Croatia,
            "CU" => CountryZone::Cuba,
            "CY" => CountryZone::Cyprus,
            "EZ" => CountryZone::CzechRepublic,
            "LO" => CountryZone::Czechoslovakia,
            "CG" => CountryZone::DemocraticRepublicoftheCongo,
            "DA" => CountryZone::Denmark,
            "DX" => CountryZone::DhekeliaSovereignBaseArea,
            "DJ" => CountryZone::Djibouti,
            "DO" => CountryZone::Dominica,
            "DR" => CountryZone::DominicanRepublic,
            "TT" => CountryZone::EastTimor,
            "EC" => CountryZone::Ecuador,
            "EG" => CountryZone::Egypt,
            "ES" => CountryZone::ElSalvador,
            "GV" => CountryZone::EquatorialGuinea,
            "EK" => CountryZone::EquatorialGuinea,
            "ER" => CountryZone::Eritrea,
            "EN" => CountryZone::Estonia,
            "ET" => CountryZone::Ethiopia,
            "PJ" => CountryZone::EtorofuHabomaiKunashiriandShikotanIslands,
            "EU" => CountryZone::EuropaIsland,
            "FK" => CountryZone::FalklandIslandsIslasMalvinas,
            "FO" => CountryZone::FaroeIslands,
            "FJ" => CountryZone::Fiji,
            "FI" => CountryZone::Finland,
            "FR" => CountryZone::France,
            "FG" => CountryZone::FrenchGuiana,
            "FP" => CountryZone::FrenchPolynesia,
            "FS" => CountryZone::FrenchSouthernandAntarcticLands,
            "GB" => CountryZone::Gabon,
            "GA" => CountryZone::Gambia,
            "GZ" => CountryZone::GazaStrip,
            "GG" => CountryZone::Georgia,
            "GM" => CountryZone::Germany,
            "GH" => CountryZone::Ghana,
            "GI" => CountryZone::Gibraltar,
            "GO" => CountryZone::GloriosoIslands,
            "GR" => CountryZone::Greece,
            "GL" => CountryZone::Greenland,
            "GJ" => CountryZone::Grenada,
            "GP" => CountryZone::Guadeloupe,
            "GQ" => CountryZone::Guam,
            "GT" => CountryZone::Guatemala,
            "GK" => CountryZone::Guernsey,
            "PU" => CountryZone::GuineaBissau,
            "GY" => CountryZone::Guyana,
            "HA" => CountryZone::Haiti,
            "HM" => CountryZone::HeardIslandandMcDonaldIslands,
            "HO" => CountryZone::Honduras,
            "HK" => CountryZone::HongKong,
            "HQ" => CountryZone::HowlandIsland,
            "HU" => CountryZone::Hungary,
            "IC" => CountryZone::Iceland,
            "IN" => CountryZone::India,
            "ID" => CountryZone::Indonesia,
            "IR" => CountryZone::Iran,
            "IZ" => CountryZone::Iraq,
            "EI" => CountryZone::Ireland,
            "IM" => CountryZone::IsleofMan,
            "IS" => CountryZone::Israel,
            "IT" => CountryZone::Italy,
            "JM" => CountryZone::Jamaica,
            "JN" => CountryZone::JanMayen,
            "JA" => CountryZone::Japan,
            "DQ" => CountryZone::JarvisIsland,
            "JE" => CountryZone::Jersey,
            "JQ" => CountryZone::JohnstonAtoll,
            "JO" => CountryZone::Jordan,
            "JU" => CountryZone::JuandeNovaIsland,
            "KZ" => CountryZone::Kazakhstan,
            "KE" => CountryZone::Kenya,
            "KQ" => CountryZone::KingmanReef,
            "KR" => CountryZone::Kiribati,
            "KV" => CountryZone::Kosovo,
            "KU" => CountryZone::Kuwait,
            "KG" => CountryZone::Kyrgyzstan,
            "LA" => CountryZone::Laos,
            "LG" => CountryZone::Latvia,
            "LE" => CountryZone::Lebanon,
            "LT" => CountryZone::Lesotho,
            "LI" => CountryZone::Liberia,
            "LY" => CountryZone::Libya,
            "LS" => CountryZone::Liechtenstein,
            "LH" => CountryZone::Lithuania,
            "LU" => CountryZone::Luxembourg,
            "MC" => CountryZone::Macau,
            "MK" => CountryZone::Macedonia,
            "MA" => CountryZone::Madagascar,
            "MI" => CountryZone::Malawi,
            "MY" => CountryZone::Malaysia,
            "MV" => CountryZone::Maldives,
            "ML" => CountryZone::Mali,
            "MT" => CountryZone::Malta,
            "RM" => CountryZone::MarshallIslands,
            "MB" => CountryZone::Martinique,
            "MR" => CountryZone::Mauritania,
            "MP" => CountryZone::Mauritius,
            "MF" => CountryZone::Mayotte,
            "MX" => CountryZone::Mexico,
            "FM" => CountryZone::Micronesia,
            "MQ" => CountryZone::MidwayIslands,
            "MD" => CountryZone::Moldova,
            "MN" => CountryZone::Monaco,
            "MG" => CountryZone::Mongolia,
            "MJ" => CountryZone::Montenegro,
            "MH" => CountryZone::Montserrat,
            "MO" => CountryZone::Morocco,
            "MZ" => CountryZone::Mozambique,
            "BM" => CountryZone::Myanmar,
            "WA" => CountryZone::Namibia,
            "NR" => CountryZone::Nauru,
            "BQ" => CountryZone::NavassaIsland,
            "NP" => CountryZone::Nepal,
            "NL" => CountryZone::Netherlands,
            "NT" => CountryZone::NetherlandsAntilles,
            "NC" => CountryZone::NewCaledonia,
            "NZ" => CountryZone::NewZealand,
            "NU" => CountryZone::Nicaragua,
            "NG" => CountryZone::Niger,
            "NI" => CountryZone::Nigeria,
            "NE" => CountryZone::Niue,
            "NM" => CountryZone::NoMansLand,
            "NF" => CountryZone::NorfolkIsland,
            "KN" => CountryZone::NorthKorea,
            "CQ" => CountryZone::NorthernMarianaIslands,
            "NO" => CountryZone::Norway,
            "OS" => CountryZone::Oceans,
            "MU" => CountryZone::Oman,
            "PK" => CountryZone::Pakistan,
            "PS" => CountryZone::Palau,
            "LQ" => CountryZone::PalmyraAtoll,
            "PM" => CountryZone::Panama,
            "PP" => CountryZone::PapuaNewGuinea,
            "PF" => CountryZone::ParacelIslands,
            "PA" => CountryZone::Paraguay,
            "PE" => CountryZone::Peru,
            "RP" => CountryZone::Philippines,
            "PC" => CountryZone::PitcairnIslands,
            "PL" => CountryZone::Poland,
            "PO" => CountryZone::Portugal,
            "RQ" => CountryZone::PuertoRico,
            "QA" => CountryZone::Qatar,
            "RE" => CountryZone::Reunion,
            "RO" => CountryZone::Romania,
            "RS" => CountryZone::Russia,
            "RW" => CountryZone::Rwanda,
            "SH" => CountryZone::SaintHelena,
            "SC" => CountryZone::SaintKittsandNevis,
            "ST" => CountryZone::SaintLucia,
            "RN" => CountryZone::SaintMartin,
            "SB" => CountryZone::SaintPierreandMiquelon,
            "VC" => CountryZone::SaintVincentandtheGrenadines,
            "TB" => CountryZone::SaintBarthelemyIsland,
            "WS" => CountryZone::Samoa,
            "SM" => CountryZone::SanMarino,
            "TP" => CountryZone::SaoTomeandPrincipe,
            "SA" => CountryZone::SaudiArabia,
            "SG" => CountryZone::Senegal,
            "RI" => CountryZone::Serbia,
            "SE" => CountryZone::Seychelles,
            "SL" => CountryZone::SierraLeone,
            "SN" => CountryZone::Singapore,
            "SI" => CountryZone::Slovenia,
            "BP" => CountryZone::SolomonIslands,
            "SO" => CountryZone::Somalia,
            "SF" => CountryZone::SouthAfrica,
            "SX" => CountryZone::SouthGeorgiaandtheSouthSandwichIslands,
            "KS" => CountryZone::SouthKorea,
            "OD" => CountryZone::SouthSudan,
            "SP" => CountryZone::Spain,
            "PG" => CountryZone::SpratlyIslands,
            "CE" => CountryZone::SriLanka,
            "SU" => CountryZone::Sudan,
            "NS" => CountryZone::Suriname,
            "SV" => CountryZone::Svalbard,
            "WZ" => CountryZone::Swaziland,
            "SW" => CountryZone::Sweden,
            "SZ" => CountryZone::Switzerland,
            "SY" => CountryZone::Syria,
            "TW" => CountryZone::Taiwan,
            "TI" => CountryZone::Tajikistan,
            "TZ" => CountryZone::Tanzania,
            "TH" => CountryZone::Thailand,
            "TO" => CountryZone::Togo,
            "TL" => CountryZone::Tokelau,
            "TN" => CountryZone::Tonga,
            "TD" => CountryZone::TrinidadandTobago,
            "TE" => CountryZone::TromelinIsland,
            "TS" => CountryZone::Tunisia,
            "TU" => CountryZone::Turkey,
            "TX" => CountryZone::Turkmenistan,
            "TK" => CountryZone::TurksandCaicosIslands,
            "TV" => CountryZone::Tuvalu,
            "UG" => CountryZone::Uganda,
            "UP" => CountryZone::Ukraine,
            "UF" => CountryZone::UnderseaFeatures,
            "UU" => CountryZone::UndesignatedSovereignty,
            "AE" => CountryZone::UnitedArabEmirates,
            "UK" => CountryZone::UnitedKingdom,
            "US" => CountryZone::UnitedStates,
            "UY" => CountryZone::Uruguay,
            "UZ" => CountryZone::Uzbekistan,
            "NH" => CountryZone::Vanuatu,
            "VT" => CountryZone::VaticanCity,
            "VE" => CountryZone::Venezuela,
            "VM" => CountryZone::VietnamDemocraticRepublicof,
            "VQ" => CountryZone::VirginIslands,
            "WQ" => CountryZone::WakeIsland,
            "WF" => CountryZone::WallisandFutuna,
            "WE" => CountryZone::WestBank,
            "WI" => CountryZone::WesternSahara,
            "YM" => CountryZone::Yemen,
            "ZA" => CountryZone::Zambia,
            "ZI" => CountryZone::Zimbabwe,
            _ => CountryZone::Unspecified,
        }
    }
}

impl From<CAMEOCountryCode> for CountryZone {
    fn from(value: CAMEOCountryCode) -> Self {
        let str_value = std::str::from_utf8(&value.0).expect("Invalid CAMEO Code format");
        match str_value {
            "WSB" => CountryZone::WestBank,
            "BAG" => CountryZone::Baghdad,
            "GZS" => CountryZone::GazaStrip,
            "AFR" => CountryZone::Africa,
            "ASA" => CountryZone::Asia,
            "BLK" => CountryZone::Balkans,
            "CRB" => CountryZone::Caribbean,
            "CAU" => CountryZone::Caucasus,
            "CFR" => CountryZone::CentralAfrica,
            "CAS" => CountryZone::CentralAsia,
            "CEU" => CountryZone::CentralEurope,
            "EIN" => CountryZone::EastIndies,
            "EAF" => CountryZone::EasternAfrica,
            "EEU" => CountryZone::EasternEurope,
            "EUR" => CountryZone::Europe,
            "LAM" => CountryZone::LatinAmerica,
            "MEA" => CountryZone::MiddleEast,
            "MDT" => CountryZone::Mediterranean,
            "NAF" => CountryZone::NorthAfrica,
            "NMR" => CountryZone::NorthAmerica,
            "PGS" => CountryZone::PersianGulf,
            "SCN" => CountryZone::Scandinavia,
            "SAM" => CountryZone::SouthAmerica,
            "SAS" => CountryZone::SouthAsia,
            "SEA" => CountryZone::SoutheastAsia,
            "SAF" => CountryZone::SouthernAfrica,
            "WAF" => CountryZone::WestAfrica,
            "WST" => CountryZone::TheWest,
            "AFG" => CountryZone::Afghanistan,
            "ALA" => CountryZone::AlandIslands,
            "ALB" => CountryZone::Albania,
            "DZA" => CountryZone::Algeria,
            "ASM" => CountryZone::AmericanSamoa,
            "AND" => CountryZone::Andorra,
            "AGO" => CountryZone::Angola,
            "AIA" => CountryZone::Anguilla,
            "ATG" => CountryZone::AntiguaandBarbuda,
            "ARG" => CountryZone::Argentina,
            "ARM" => CountryZone::Armenia,
            "ABW" => CountryZone::Aruba,
            "AUS" => CountryZone::Australia,
            "AUT" => CountryZone::Austria,
            "AZE" => CountryZone::Azerbaijan,
            "BHS" => CountryZone::Bahamas,
            "BHR" => CountryZone::Bahrain,
            "BGD" => CountryZone::Bangladesh,
            "BRB" => CountryZone::Barbados,
            "BLR" => CountryZone::Belarus,
            "BEL" => CountryZone::Belgium,
            "BLZ" => CountryZone::Belize,
            "BEN" => CountryZone::Benin,
            "BMU" => CountryZone::Bermuda,
            "BTN" => CountryZone::Bhutan,
            "BOL" => CountryZone::Bolivia,
            "BIH" => CountryZone::BosniaandHerzegovina,
            "BWA" => CountryZone::Botswana,
            "BRA" => CountryZone::Brazil,
            "VGB" => CountryZone::BritishVirginIslands,
            "BRN" => CountryZone::BruneiDarussalam,
            "BGR" => CountryZone::Bulgaria,
            "BFA" => CountryZone::BurkinaFaso,
            "BDI" => CountryZone::Burundi,
            "KHM" => CountryZone::Cambodia,
            "CMR" => CountryZone::Cameroon,
            "CAN" => CountryZone::Canada,
            "CPV" => CountryZone::CapeVerde,
            "CYM" => CountryZone::CaymanIslands,
            "CAF" => CountryZone::CentralAfricanRepublic,
            "TCD" => CountryZone::Chad,
            "CHL" => CountryZone::Chile,
            "CHN" => CountryZone::China,
            "COL" => CountryZone::Columbia,
            "COM" => CountryZone::Comoros,
            "COD" => CountryZone::DemocraticRepublicoftheCongo,
            "COG" => CountryZone::PeoplesRepublicoftheCongo,
            "COK" => CountryZone::CookIslands,
            "CRI" => CountryZone::CostaRica,
            "CIV" => CountryZone::IvoryCoast,
            "HRV" => CountryZone::Croatia,
            "CUB" => CountryZone::Cuba,
            "CYP" => CountryZone::Cyprus,
            "CZE" => CountryZone::CzechRepublic,
            "DNK" => CountryZone::Denmark,
            "DJI" => CountryZone::Djibouti,
            "DMA" => CountryZone::Dominica,
            "DOM" => CountryZone::DominicanRepublic,
            "TMP" => CountryZone::EastTimor,
            "ECU" => CountryZone::Ecuador,
            "EGY" => CountryZone::Egypt,
            "SLV" => CountryZone::ElSalvador,
            "GNQ" => CountryZone::EquatorialGuinea,
            "ERI" => CountryZone::Eritrea,
            "EST" => CountryZone::Estonia,
            "ETH" => CountryZone::Ethiopia,
            "FRO" => CountryZone::FaeroeIslands,
            "FLK" => CountryZone::FalklandIslands,
            "FJI" => CountryZone::Fiji,
            "FIN" => CountryZone::Finland,
            "FRA" => CountryZone::France,
            "GUF" => CountryZone::FrenchGuiana,
            "PYF" => CountryZone::FrenchPolynesia,
            "GAB" => CountryZone::Gabon,
            "GMB" => CountryZone::Gambia,
            "GEO" => CountryZone::Georgia,
            "DEU" => CountryZone::Germany,
            "GHA" => CountryZone::Ghana,
            "GIB" => CountryZone::Gibraltar,
            "GRC" => CountryZone::Greece,
            "GRL" => CountryZone::Greenland,
            "GRD" => CountryZone::Grenada,
            "GLP" => CountryZone::Guadeloupe,
            "GUM" => CountryZone::Guam,
            "GTM" => CountryZone::Guatemala,
            "GIN" => CountryZone::Guinea,
            "GNB" => CountryZone::GuineaBissau,
            "GUY" => CountryZone::Guyana,
            "HTI" => CountryZone::Haiti,
            "VAT" => CountryZone::VaticanCity,
            "HND" => CountryZone::Honduras,
            "HKG" => CountryZone::HongKong,
            "HUN" => CountryZone::Hungary,
            "ISL" => CountryZone::Iceland,
            "IND" => CountryZone::India,
            "IDN" => CountryZone::Indonesia,
            "IRN" => CountryZone::Iran,
            "IRQ" => CountryZone::Iraq,
            "IRL" => CountryZone::Ireland,
            "IMY" => CountryZone::IsleofMan,
            "ISR" => CountryZone::Israel,
            "ITA" => CountryZone::Italy,
            "JAM" => CountryZone::Jamaica,
            "JPN" => CountryZone::Japan,
            "JOR" => CountryZone::Jordan,
            "KAZ" => CountryZone::Kazakhstan,
            "KEN" => CountryZone::Kenya,
            "KIR" => CountryZone::Kiribati,
            "PRK" => CountryZone::NorthKorea,
            "KOR" => CountryZone::SouthKorea,
            "KWT" => CountryZone::Kuwait,
            "KGZ" => CountryZone::Kyrgyzstan,
            "LAO" => CountryZone::Laos,
            "LVA" => CountryZone::Latvia,
            "LBN" => CountryZone::Lebanon,
            "LSO" => CountryZone::Lesotho,
            "LBR" => CountryZone::Liberia,
            "LBY" => CountryZone::Libya,
            "LIE" => CountryZone::Liechtenstein,
            "LTU" => CountryZone::Lithuania,
            "LUX" => CountryZone::Luxembourg,
            "MAC" => CountryZone::Macao,
            "MKD" => CountryZone::Macedonia,
            "MDG" => CountryZone::Madagascar,
            "MWI" => CountryZone::Malawi,
            "MYS" => CountryZone::Malaysia,
            "MDV" => CountryZone::Maldives,
            "MLI" => CountryZone::Mali,
            "MLT" => CountryZone::Malta,
            "MHL" => CountryZone::MarshallIslands,
            "MTQ" => CountryZone::Martinique,
            "MRT" => CountryZone::Mauritania,
            "MUS" => CountryZone::Mauritius,
            "MYT" => CountryZone::Mayotte,
            "MEX" => CountryZone::Mexico,
            "FSM" => CountryZone::Micronesia,
            "MDA" => CountryZone::Moldova,
            "MCO" => CountryZone::Monaco,
            "MNG" => CountryZone::Mongolia,
            "MTN" => CountryZone::Montenegro,
            "MSR" => CountryZone::Montserrat,
            "MAR" => CountryZone::Morocco,
            "MOZ" => CountryZone::Mozambique,
            "MMR" => CountryZone::Myanmar,
            "NAM" => CountryZone::Namibia,
            "NRU" => CountryZone::Nauru,
            "NPL" => CountryZone::Nepal,
            "NLD" => CountryZone::Netherlands,
            "ANT" => CountryZone::NetherlandsAntilles,
            "NCL" => CountryZone::NewCaledonia,
            "NZL" => CountryZone::NewZealand,
            "NIC" => CountryZone::Nicaragua,
            "NER" => CountryZone::Niger,
            "NGA" => CountryZone::Nigeria,
            "NIU" => CountryZone::Niue,
            "NFK" => CountryZone::NorfolkIsland,
            "MNP" => CountryZone::NorthernMarianaIslands,
            "NOR" => CountryZone::Norway,
            "PSE" => CountryZone::OccupiedPalestinianTerritory,
            "OMN" => CountryZone::Oman,
            "PAK" => CountryZone::Pakistan,
            "PLW" => CountryZone::Palau,
            "PAN" => CountryZone::Panama,
            "PNG" => CountryZone::PapuaNewGuinea,
            "PRY" => CountryZone::Paraguay,
            "PER" => CountryZone::Peru,
            "PHL" => CountryZone::Philippines,
            "PCN" => CountryZone::Pitcairn,
            "POL" => CountryZone::Poland,
            "PRT" => CountryZone::Portugal,
            "PRI" => CountryZone::PuertoRico,
            "QAT" => CountryZone::Qatar,
            "REU" => CountryZone::Runion,
            "ROM" => CountryZone::Romania,
            "RUS" => CountryZone::Russia,
            "RWA" => CountryZone::Rwanda,
            "SHN" => CountryZone::SaintHelena,
            "KNA" => CountryZone::SaintKittsNevis,
            "LCA" => CountryZone::SaintLucia,
            "SPM" => CountryZone::SaintPierreandMiquelon,
            "VCT" => CountryZone::SaintVincentandtheGrenadines,
            "WSM" => CountryZone::Samoa,
            "SMR" => CountryZone::SanMarino,
            "STP" => CountryZone::SaoTomeandPrincipe,
            "SAU" => CountryZone::SaudiArabia,
            "SEN" => CountryZone::Senegal,
            "SRB" => CountryZone::Serbia,
            "SYC" => CountryZone::Seychelles,
            "SLE" => CountryZone::SierraLeone,
            "SGP" => CountryZone::Singapore,
            "SVK" => CountryZone::Slovakia,
            "SVN" => CountryZone::Slovenia,
            "SLB" => CountryZone::SolomonIslands,
            "SOM" => CountryZone::Somalia,
            "ZAF" => CountryZone::SouthAfrica,
            "ESP" => CountryZone::Spain,
            "LKA" => CountryZone::SriLanka,
            "SDN" => CountryZone::Sudan,
            "SUR" => CountryZone::Suriname,
            "SJM" => CountryZone::SvalbardandJanMayenIslands,
            "SWZ" => CountryZone::Swaziland,
            "SWE" => CountryZone::Sweden,
            "CHE" => CountryZone::Switzerland,
            "SYR" => CountryZone::Syria,
            "TWN" => CountryZone::Taiwan,
            "TJK" => CountryZone::Tajikistan,
            "TZA" => CountryZone::Tanzania,
            "THA" => CountryZone::Thailand,
            "TGO" => CountryZone::Togo,
            "TKL" => CountryZone::Tokelau,
            "TON" => CountryZone::Tonga,
            "TTO" => CountryZone::TrinidadandTobago,
            "TUN" => CountryZone::Tunisia,
            "TUR" => CountryZone::Turkey,
            "TKM" => CountryZone::Turkmenistan,
            "TCA" => CountryZone::TurksandCaicosIslands,
            "TUV" => CountryZone::Tuvalu,
            "UGA" => CountryZone::Uganda,
            "UKR" => CountryZone::Ukraine,
            "ARE" => CountryZone::UnitedArabEmirates,
            "GBR" => CountryZone::UnitedKingdom,
            "USA" => CountryZone::UnitedStates,
            "VIR" => CountryZone::UnitedStatesVirginIslands,
            "URY" => CountryZone::Uruguay,
            "UZB" => CountryZone::Uzbekistan,
            "VUT" => CountryZone::Vanuatu,
            "VEN" => CountryZone::Venezuela,
            "VNM" => CountryZone::Vietnam,
            "WLF" => CountryZone::WallisandFutunaIslands,
            "ESH" => CountryZone::WesternSahara,
            "YEM" => CountryZone::Yemen,
            "ZMB" => CountryZone::Zambia,
            "ZWE" => CountryZone::Zimbabwe,
            _ => Self::Unspecified,
        }
    }
}
