use crate::components::base_components::raw_types::RawCAMEOEthnicCode;

pub enum Ethnicity {
    Unspecified,
    Afar,
    Abkhaz,
    AboriginalAustralians,
    Acehnese,
    Achang,
    Acholi,
    Ga,
    Adivasi,
    Adjarians,
    Adyghe,
    BlackAfrican,
    Afrikaners,
    Ahmadis,
    Ainu,
    Aja,
    Akan,
    Aku,
    Alawi,
    Albanian,
    Aleut,
    Algonquian,
    Altay,
    Alur,
    Ambonese,
    AmericoLiberians,
    Amhara,
    AngikaSpeakers,
    Apache,
    Arab,
    Aragonese,
    Armenian,
    Mapuche,
    Arapaho,
    Arawak,
    Asian,
    AshkenaziJews,
    Assamese,
    Asturian,
    Assyrian,
    Atacamenos,
    Argentinians,
    Athabaskan,
    AgnosticAthiest,
    Australians,
    Austrians,
    CaucasianAvars,
    Awadhi,
    Aymara,
    Azerbaijani,
    Baganda,
    Bahais,
    Bamileke,
    Bashkirs,
    Baloch,
    Bambara,
    Balinese,
    Basque,
    Bari,
    Basoga,
    Gbaya,
    Rakhine,
    Beja,
    Belarusians,
    Bemba,
    BengaliHindu,
    Berber,
    Beydan,
    Bhojpuri,
    Bihari,
    Bai,
    Bicolano,
    Edo,
    UrbanniVanautu,
    Bateke,
    Bakongo,
    Bakweri,
    Siksikawa,
    Blang,
    Balkars,
    Balanta,
    Bamar,
    BeniShugalGumez,
    Bantu,
    Banyarwanda,
    Bodo,
    Tibetan,
    Bolivia,
    Bonan,
    Bosniaks,
    Buyei,
    Brijwasi,
    Bariba,
    Breton,
    Brahui,
    Burakumin,
    Kurichiya,
    Bushmen,
    Baster,
    Subiya,
    BetiPahuin,
    Batak,
    Buryat,
    Buddhist,
    Bugis,
    Bulgarian,
    Bilen,
    CabindanMayombe,
    Caddo,
    CapeVerdean,
    Kalina,
    Catalan,
    Cebuano,
    Chamorro,
    Chukchi,
    Chechen,
    Chagatai,
    Chinese,
    Chuukese,
    Chileans,
    Mari,
    Chinook,
    Choctaw,
    Chipewyan,
    Cherokee,
    Chorti,
    Chuvash,
    Chewa,
    Cheyenne,
    Cham,
    Colombian,
    Confusian,
    CopticChristians,
    Cornish,
    Corsican,
    Cotiers,
    EnglishCreole,
    FrenchCreole,
    PortugueseCreole,
    Cree,
    CrimeanTatar,
    Christian,
    OrthodoxChristian,
    Creole,
    Kashubian,
    CostaRicans,
    Catholics,
    Cushitic,
    Czech,
    Dai,
    Sioux,
    Dalit,
    Damara,
    Danes,
    YaoAsia,
    Dargwa,
    Daur,
    Dayak,
    Lenape,
    Slavey,
    Dogrib,
    Dinka,
    Maldivian,
    DjermaSonghai,
    Dogras,
    Dominicans,
    Dong,
    Dongxiang,
    Dravidian,
    Druze,
    LowerSorbian,
    Duala,
    Dutch,
    Dyula,
    Ngalop,
    EastTimorese,
    Ecuadorians,
    Efik,
    EastIndian,
    Ekajuk,
    English,
    Eshira,
    Estonian,
    EthiopianJews,
    Europeans,
    Evenks,
    Ewe,
    Ewondo,
    Fang,
    Faroese,
    Fante,
    Fijian,
    Filipino,
    Finns,
    FinnoUgric,
    Fon,
    French,
    Santals,
    Frisians,
    Fur,
    Fula,
    Friulan,
    Garifuna,
    Gayo,
    Gelao,
    Georgian,
    German,
    GiaRai,
    Kiribati,
    Gin,
    Gio,
    Gaels,
    Irish,
    Galician,
    Manx,
    Gondi,
    Gorontalonese,
    Grassfielders,
    Grebo,
    Greek,
    Guarani,
    SwissGermans,
    Guatemalan,
    Gujarati,
    Guan,
    Gwichin,
    Hadjerai,
    Haida,
    Harari,
    Haitian,
    Hausa,
    Hawaiian,
    Hazara,
    Herero,
    HillTribes,
    Hiligayon,
    Himachali,
    Hindu,
    Hasidic,
    Hmong,
    HiriMotu,
    Hani,
    Hoa,
    Hondurans,
    Haratin,
    Croats,
    UpperSorbian,
    Hui,
    Hungarian,
    Hupa,
    Hutu,
    Iban,
    Igbo,
    Icelanders,
    Indigenous,
    Indian,
    Yi,
    Ijaw,
    Inuit,
    Ilocono,
    Indonesian,
    Ingush,
    Inupiat,
    Iranian,
    Iroquois,
    Itallian,
    Jain,
    Javanese,
    Jewish,
    JehovahsWitnesses,
    Jino,
    Jola,
    Japanese,
    Karakalpak,
    Kabyle,
    Kachin,
    Kadazan,
    KakwaNubian,
    Kalaallit,
    Kamba,
    Kannada,
    Kaonde,
    Karen,
    Kashmiri,
    Kanuri,
    Kavango,
    Kazakhs,
    Kabarday,
    Kabye,
    Karachays,
    Khasi,
    Khoikhoi,
    Khakas,
    Khmer,
    Khmu,
    Kikuyu,
    KinyarwandaSpeakers,
    Kyrgyz,
    Kisii,
    Kalmyk,
    NorthMbundu,
    Kono,
    Kokani,
    Komi,
    Kongo,
    Korean,
    Kosraean,
    Kouyou,
    Kpelle,
    Krahn,
    Karelians,
    Karamojong,
    Kru,
    Kurukh,
    Kwanyama,
    Kumyks,
    Kurd,
    Ktunaxa,
    SephardicJew,
    LakRussia,
    Lamba,
    Lao,
    Lari,
    Latvian,
    Limba,
    LatterDaySaints,
    Lenca,
    Lezgian,
    Lugbara,
    Lahu,
    Li,
    Limburgian,
    Lingala,
    Lithuanian,
    Mongo,
    Lomwe,
    Lovale,
    Lozi,
    Lisu,
    Latoka,
    Latinos,
    Luxembourgers,
    LubaKasai,
    LubaKatanga,
    Luhya,
    Luiseno,
    Lulua,
    Lunda,
    Luo,
    Lusei,
    Macedonian,
    Madurese,
    Mafwe,
    Magahi,
    Marshallese,
    Maithili,
    Makassarese,
    Malayalam,
    Mandinka,
    Maori,
    Marathi,
    Maasai,
    Malays,
    Mbandja,
    Mbere,
    MBaka,
    Mbochi,
    MbunduMestico,
    Mokshas,
    Madhesi,
    Madi,
    Mandar,
    Mende,
    Miao,
    Mikmaq,
    Mijikenda,
    Minangkabau,
    Mizo,
    Mulatto,
    MoleDagbani,
    Malagasy,
    Mulao,
    Maltese,
    Manchu,
    Mande,
    MananjaNayanja,
    Minahasa,
    Manipuri,
    Manjack,
    Mano,
    Lumad,
    Mon,
    Manyika,
    Mohajirs,
    Mohawk,
    Makonde,
    Maonan,
    Mongol,
    Mossi,
    Maronites,
    Moro,
    Miskito,
    Muslim,
    Montenegrins,
    Mestizo,
    Munda,
    Muong,
    Muscogee,
    Mirandese,
    Marwaris,
    Mayangnas,
    Myene,
    Maya,
    Mordvins,
    Naga,
    Nahua,
    NativeAmerican,
    Nama,
    Neapolitan,
    Nauruan,
    Navajo,
    Nakhi,
    Nuba,
    SouthNdebele,
    Nicaraguan,
    NorthernNdebele,
    Ndonga,
    Nepali,
    Nuer,
    Newars,
    Ngbandi,
    Ngoni,
    Niasans,
    Nibolek,
    Niari,
    Niuean,
    Nkomi,
    Nung,
    Nogais,
    Norwegians,
    NorthernSotho,
    Nubian,
    Nuristani,
    Nu,
    Nyakyusa,
    Nyamwezi,
    Ankole,
    Nyoro,
    NewZealanders,
    Nzema,
    Occitanians,
    Ogoni,
    Ojibwe,
    OrthodoxUltraOrthodoxJew,
    Okinawan,
    Oriya,
    Oromo,
    Orgunu,
    Osage,
    Ossetians,
    Otomi,
    Ovambo,
    Papuan,
    PacificIslanders,
    Pangasinan,
    Palestinian,
    Kapampangan,
    Punjabi,
    PapiamentoCreole,
    Paraguayan,
    Palauan,
    Persian,
    AnimistPagan,
    Puthai,
    Panamanians,
    Poles,
    Pomaks,
    Pehnpeian,
    Portuguese,
    Papel,
    Protestant,
    Peruvian,
    Pashayi,
    Pumi,
    Pashtun,
    Qiang,
    Qizilbash,
    Quechua,
    Rajasthani,
    PahariRajput,
    RapaNui,
    CookIslandsMaori,
    UnspecifiedReligion,
    Romansh,
    Romani,
    Romanian,
    Rundi,
    Aromanians,
    Russian,
    Sandawe,
    Sango,
    Yakuts,
    Salish,
    Sara,
    Sasak,
    Sudanese,
    Sicilian,
    Scottish,
    Selkup,
    Sena,
    Sufi,
    Shafii,
    She,
    Shiites,
    Shilluk,
    Shan,
    Shaigiya,
    Sidama,
    Sinhalese,
    Siouan,
    Slavic,
    Slovaks,
    Salar,
    Slovenes,
    Sami,
    Samoans,
    Shona,
    Sindhi,
    Soninke,
    Somali,
    Songhai,
    Sotho,
    Spanish,
    Sardinian,
    SrananTongo,
    Serbs,
    Serer,
    Swazi,
    Sui,
    Sukama,
    Sunni,
    Susu,
    Swahili,
    Swedes,
    SwissFrench,
    SwissItalian,
    Tabasaran,
    Tahitian,
    Tai,
    Tamil,
    Taoist,
    Tatars,
    Tawahka,
    Tay,
    Telugu,
    Temne,
    Terenan,
    Teso,
    Tetum,
    Tajik,
    Tagalog,
    Thai,
    Tigre,
    TigrayTigrinya,
    Tiv,
    Tokelauan,
    Tlingit,
    Tuareg,
    Tama,
    TongaAfrica,
    TongaPacific,
    Tooro,
    Toubou,
    TokPisin,
    Transnistrians,
    Tripuri,
    Ternate,
    Tsimshian,
    Tswana,
    Tsonga,
    Tutsi,
    Tujia,
    Turkmen,
    Tumbuka,
    Tupi,
    Turkish,
    Mongour,
    Tuvaluans,
    Ashanti,
    Taiwanese,
    Tuvans,
    Udmurt,
    Uyghur,
    Ukranian,
    SouthernMbundu,
    Undetermined,
    Urdu,
    Uzbeks,
    Va,
    Vai,
    Venda,
    Vietnamese,
    Vili,
    Venezuelan,
    Votes,
    Wakashan,
    Welayta,
    Waray,
    Washoe,
    Welsch,
    Welsh,
    Sorbs,
    Whites,
    Walloons,
    Wolof,
    Xhosa,
    Xibe,
    Xinca,
    Yao,
    Yapese,
    Yoruba,
    Yupik,
    Yugur,
    Zaghawa,
    Zapotec,
    Zaidiyya,
    Zenaga,
    Zhuang,
    Azande,
    Zomi,
    Zoroastrians,
    Zulu,
    Zuni,
    Zaza,
}

impl From<RawCAMEOEthnicCode> for Ethnicity {
    fn from(value: RawCAMEOEthnicCode) -> Self {
        let str_value = std::str::from_utf8(&value.0).expect("Invalid Ethnicity Code format");
        match str_value {
            "aar" => Self::Afar,
            "abk" => Self::Abkhaz,
            "abr" => Self::AboriginalAustralians,
            "ace" => Self::Acehnese,
            "acg" => Self::Achang,
            "ach" => Self::Acholi,
            "ada" => Self::Ga,
            "adi" => Self::Adivasi,
            "adj" => Self::Adjarians,
            "ady" => Self::Adyghe,
            "afa" => Self::BlackAfrican,
            "afr" => Self::Afrikaners,
            "ahm" => Self::Ahmadis,
            "ain" => Self::Ainu,
            "aja" => Self::Aja,
            "aka" => Self::Akan,
            "aku" => Self::Aku,
            "ala" => Self::Alawi,
            "alb" => Self::Albanian,
            "ale" => Self::Aleut,
            "alg" => Self::Algonquian,
            "alt" => Self::Altay,
            "alu" => Self::Alur,
            "amb" => Self::Ambonese,
            "ame" => Self::AmericoLiberians,
            "amh" => Self::Amhara,
            "anp" => Self::AngikaSpeakers,
            "apa" => Self::Apache,
            "ara" => Self::Arab,
            "ARB" => Self::Arab,
            "arg" => Self::Aragonese,
            "arm" => Self::Armenian,
            "arn" => Self::Mapuche,
            "arp" => Self::Arapaho,
            "arw" => Self::Arawak,
            "asa" => Self::Asian,
            "ash" => Self::AshkenaziJews,
            "asm" => Self::Assamese,
            "ast" => Self::Asturian,
            "asy" => Self::Assyrian,
            "ata" => Self::Atacamenos,
            "atg" => Self::Argentinians,
            "ath" => Self::Athabaskan,
            "ats" => Self::AgnosticAthiest,
            "aus" => Self::Australians,
            "auu" => Self::Austrians,
            "ava" => Self::CaucasianAvars,
            "awa" => Self::Awadhi,
            "aym" => Self::Aymara,
            "aze" => Self::Azerbaijani,
            "bad" => Self::Baganda,
            "bah" => Self::Bahais,
            "bai" => Self::Bamileke,
            "bak" => Self::Bashkirs,
            "bal" => Self::Baloch,
            "bam" => Self::Bambara,
            "ban" => Self::Balinese,
            "baq" => Self::Basque,
            "bar" => Self::Bari,
            "bas" => Self::Basoga,
            "bay" => Self::Gbaya,
            "bda" => Self::Rakhine,
            "bej" => Self::Beja,
            "bel" => Self::Belarusians,
            "bem" => Self::Bemba,
            "ben" => Self::BengaliHindu,
            "ber" => Self::Berber,
            "bey" => Self::Beydan,
            "bho" => Self::Bhojpuri,
            "bih" => Self::Bihari,
            "bii" => Self::Bai,
            "bik" => Self::Bicolano,
            "bin" => Self::Edo,
            "bis" => Self::UrbanniVanautu,
            "bke" => Self::Bateke,
            "bkn" => Self::Bakongo,
            "bkw" => Self::Bakweri,
            "bla" => Self::Siksikawa,
            "blg" => Self::Blang,
            "blk" => Self::Balkars,
            "bln" => Self::Balanta,
            "bmr" => Self::Bamar,
            "bni" => Self::BeniShugalGumez,
            "bnt" => Self::Bantu,
            "bny" => Self::Banyarwanda,
            "bod" => Self::Tibetan,
            "bol" => Self::Bolivia,
            "bon" => Self::Bonan,
            "bos" => Self::Bosniaks,
            "bou" => Self::Buyei,
            "bra" => Self::Brijwasi,
            "brb" => Self::Bariba,
            "bre" => Self::Breton,
            "brh" => Self::Brahui,
            "brk" => Self::Burakumin,
            "brm" => Self::Kurichiya,
            "bsh" => Self::Bushmen,
            "bst" => Self::Baster,
            "bsu" => Self::Subiya,
            "bte" => Self::BetiPahuin,
            "btk" => Self::Batak,
            "bua" => Self::Buryat,
            "bud" => Self::Buddhist,
            "bug" => Self::Bugis,
            "bul" => Self::Bulgarian,
            "byn" => Self::Bilen,
            "cab" => Self::CabindanMayombe,
            "cad" => Self::Caddo,
            "cap" => Self::CapeVerdean,
            "car" => Self::Kalina,
            "cat" => Self::Catalan,
            "ceb" => Self::Cebuano,
            "cha" => Self::Chamorro,
            "chc" => Self::Chukchi,
            "che" => Self::Chechen,
            "chg" => Self::Chagatai,
            "chi" => Self::Chinese,
            "chk" => Self::Chuukese,
            "chl" => Self::Chileans,
            "chm" => Self::Mari,
            "chn" => Self::Chinook,
            "cho" => Self::Choctaw,
            "chp" => Self::Chipewyan,
            "chr" => Self::Cherokee,
            "cht" => Self::Chorti,
            "chv" => Self::Chuvash,
            "chw" => Self::Chewa,
            "chy" => Self::Cheyenne,
            "cir" => Self::Adyghe,
            "cmc" => Self::Cham,
            "col" => Self::Colombian,
            "con" => Self::Confusian,
            "cop" => Self::CopticChristians,
            "cor" => Self::Cornish,
            "cos" => Self::Corsican,
            "cot" => Self::Cotiers,
            "cpe" => Self::EnglishCreole,
            "cpf" => Self::FrenchCreole,
            "cpp" => Self::PortugueseCreole,
            "cre" => Self::Cree,
            "crh" => Self::CrimeanTatar,
            "cri" => Self::Christian,
            "cro" => Self::OrthodoxChristian,
            "crp" => Self::Creole,
            "csb" => Self::Kashubian,
            "csr" => Self::CostaRicans,
            "cth" => Self::Catholics,
            "cus" => Self::Cushitic,
            "cze" => Self::Czech,
            "dai" => Self::Dai,
            "dak" => Self::Sioux,
            "dal" => Self::Dalit,
            "dam" => Self::Damara,
            "dan" => Self::Danes,
            "dao" => Self::YaoAsia,
            "dar" => Self::Dargwa,
            "dau" => Self::Daur,
            "day" => Self::Dayak,
            "del" => Self::Lenape,
            "den" => Self::Slavey,
            "dgr" => Self::Dogrib,
            "din" => Self::Dinka,
            "div" => Self::Maldivian,
            "dje" => Self::DjermaSonghai,
            "doi" => Self::Dogras,
            "dom" => Self::Dominicans,
            "don" => Self::Dong,
            "dox" => Self::Dongxiang,
            "dra" => Self::Dravidian,
            "dru" => Self::Druze,
            "drz" => Self::Druze,
            "dsb" => Self::LowerSorbian,
            "dua" => Self::Duala,
            "dut" => Self::Dutch,
            "dyu" => Self::Dyula,
            "dzo" => Self::Ngalop,
            "eat" => Self::EastTimorese,
            "ecu" => Self::Ecuadorians,
            "efi" => Self::Efik,
            "ein" => Self::EastIndian,
            "eka" => Self::Ekajuk,
            "eng" => Self::English,
            "esh" => Self::Eshira,
            "est" => Self::Estonian,
            "eth" => Self::EthiopianJews,
            "eur" => Self::Europeans,
            "eve" => Self::Evenks,
            "ewe" => Self::Ewe,
            "ewo" => Self::Ewondo,
            "fan" => Self::Fang,
            "fao" => Self::Faroese,
            "fat" => Self::Fante,
            "fij" => Self::Fijian,
            "fil" => Self::Filipino,
            "fin" => Self::Finns,
            "fiu" => Self::FinnoUgric,
            "fon" => Self::Fon,
            "fre" => Self::French,
            "fri" => Self::Santals,
            "frr" => Self::Frisians,
            "fru" => Self::Fur,
            "ful" => Self::Fula,
            "fur" => Self::Friulan,
            "gar" => Self::Garifuna,
            "gay" => Self::Gayo,
            "gba" => Self::Gbaya,
            "gel" => Self::Gelao,
            "geo" => Self::Georgian,
            "ger" => Self::German,
            "gia" => Self::GiaRai,
            "gil" => Self::Kiribati,
            "gin" => Self::Gin,
            "gio" => Self::Gio,
            "gla" => Self::Gaels,
            "gle" => Self::Irish,
            "glg" => Self::Galician,
            "glv" => Self::Manx,
            "gon" => Self::Gondi,
            "gor" => Self::Gorontalonese,
            "gra" => Self::Grassfielders,
            "grb" => Self::Grebo,
            "gre" => Self::Greek,
            "grn" => Self::Guarani,
            "gsw" => Self::SwissGermans,
            "gua" => Self::Guatemalan,
            "guj" => Self::Gujarati,
            "gun" => Self::Guan,
            "gwi" => Self::Gwichin,
            "had" => Self::Hadjerai,
            "hai" => Self::Haida,
            "har" => Self::Harari,
            "hat" => Self::Haitian,
            "hau" => Self::Hausa,
            "haw" => Self::Hawaiian,
            "haz" => Self::Hazara,
            "her" => Self::Herero,
            "hgh" => Self::HillTribes,
            "hil" => Self::Hiligayon,
            "him" => Self::Himachali,
            "hin" => Self::Hindu,
            "hjw" => Self::Hasidic,
            "hmn" => Self::Hmong,
            "hmo" => Self::HiriMotu,
            "hni" => Self::Hani,
            "hoa" => Self::Hoa,
            "hon" => Self::Hondurans,
            "hrt" => Self::Haratin,
            "hrv" => Self::Croats,
            "hsb" => Self::UpperSorbian,
            "hui" => Self::Hui,
            "hun" => Self::Hungarian,
            "hup" => Self::Hupa,
            "hut" => Self::Hutu,
            "iba" => Self::Iban,
            "ibo" => Self::Igbo,
            "ice" => Self::Icelanders,
            "idg" => Self::Indigenous,
            "idn" => Self::Indian,
            "iii" => Self::Yi,
            "ijo" => Self::Ijaw,
            "iku" => Self::Inuit,
            "ilo" => Self::Ilocono,
            "ind" => Self::Indonesian,
            "inh" => Self::Ingush,
            "ipk" => Self::Inupiat,
            "ira" => Self::Iranian,
            "iro" => Self::Iroquois,
            "ita" => Self::Itallian,
            "jan" => Self::Jain,
            "jav" => Self::Javanese,
            "jew" => Self::Jewish,
            "jhw" => Self::JehovahsWitnesses,
            "jin" => Self::Jino,
            "jol" => Self::Jola,
            "jpn" => Self::Japanese,
            "kaa" => Self::Karakalpak,
            "kab" => Self::Kabyle,
            "kac" => Self::Kachin,
            "kad" => Self::Kadazan,
            "kak" => Self::KakwaNubian,
            "kal" => Self::Kalaallit,
            "kam" => Self::Kamba,
            "kan" => Self::Kannada,
            "kao" => Self::Kaonde,
            "kar" => Self::Karen,
            "kas" => Self::Kashmiri,
            "kau" => Self::Kanuri,
            "kav" => Self::Kavango,
            "kaz" => Self::Kazakhs,
            "kbd" => Self::Kabarday,
            "kby" => Self::Kabye,
            "kch" => Self::Karachays,
            "kha" => Self::Khasi,
            "khi" => Self::Khoikhoi,
            "khk" => Self::Khakas,
            "khm" => Self::Khmer,
            "khu" => Self::Khmu,
            "kik" => Self::Kikuyu,
            "kin" => Self::KinyarwandaSpeakers,
            "kir" => Self::Kyrgyz,
            "kis" => Self::Kisii,
            "klm" => Self::Kalmyk,
            "kmb" => Self::NorthMbundu,
            "kno" => Self::Kono,
            "knr" => Self::Kanuri,
            "kok" => Self::Kokani,
            "kom" => Self::Komi,
            "kon" => Self::Kongo,
            "kor" => Self::Korean,
            "kos" => Self::Kosraean,
            "kou" => Self::Kouyou,
            "kpe" => Self::Kpelle,
            "krh" => Self::Krahn,
            "krl" => Self::Karelians,
            "krm" => Self::Karamojong,
            "kro" => Self::Kru,
            "kru" => Self::Kurukh,
            "kua" => Self::Kwanyama,
            "kum" => Self::Kumyks,
            "kur" => Self::Kurd,
            "KUR" => Self::Kurd,
            "kut" => Self::Ktunaxa,
            "lad" => Self::SephardicJew,
            "lak" => Self::LakRussia,
            "lam" => Self::Lamba,
            "lao" => Self::Lao,
            "lar" => Self::Lari,
            "lav" => Self::Latvian,
            "lba" => Self::Limba,
            "lds" => Self::LatterDaySaints,
            "len" => Self::Lenca,
            "lez" => Self::Lezgian,
            "lgb" => Self::Lugbara,
            "lhu" => Self::Lahu,
            "lii" => Self::Li,
            "lim" => Self::Limburgian,
            "lin" => Self::Lingala,
            "lit" => Self::Lithuanian,
            "lol" => Self::Mongo,
            "lom" => Self::Lomwe,
            "lov" => Self::Lovale,
            "loz" => Self::Lozi,
            "lsu" => Self::Lisu,
            "ltk" => Self::Latoka,
            "ltn" => Self::Latinos,
            "ltz" => Self::Luxembourgers,
            "lua" => Self::LubaKasai,
            "lub" => Self::LubaKatanga,
            "lug" => Self::Baganda,
            "luh" => Self::Luhya,
            "lui" => Self::Luiseno,
            "lul" => Self::Lulua,
            "lun" => Self::Lunda,
            "luo" => Self::Luo,
            "lus" => Self::Lusei,
            "mac" => Self::Macedonian,
            "mad" => Self::Madurese,
            "maf" => Self::Mafwe,
            "mag" => Self::Magahi,
            "mah" => Self::Marshallese,
            "mai" => Self::Maithili,
            "mak" => Self::Makassarese,
            "mal" => Self::Malayalam,
            "man" => Self::Mandinka,
            "mao" => Self::Maori,
            "mar" => Self::Marathi,
            "mas" => Self::Maasai,
            "may" => Self::Malays,
            "mba" => Self::Mbandja,
            "mbe" => Self::Mbere,
            "mbk" => Self::MBaka,
            "mbo" => Self::Mbochi,
            "mbu" => Self::MbunduMestico,
            "mdf" => Self::Mokshas,
            "mdh" => Self::Madhesi,
            "mdi" => Self::Madi,
            "mdr" => Self::Mandar,
            "men" => Self::Mende,
            "mia" => Self::Miao,
            "mic" => Self::Mikmaq,
            "mij" => Self::Mijikenda,
            "min" => Self::Minangkabau,
            "miz" => Self::Mizo,
            "mla" => Self::Mulatto,
            "mld" => Self::MoleDagbani,
            "mlg" => Self::Malagasy,
            "mlo" => Self::Mulao,
            "mlt" => Self::Maltese,
            "mnc" => Self::Manchu,
            "mnd" => Self::Mande,
            "mng" => Self::MananjaNayanja,
            "mnh" => Self::Minahasa,
            "mni" => Self::Manipuri,
            "mnj" => Self::Manjack,
            "mnn" => Self::Mano,
            "mno" => Self::Lumad,
            "mns" => Self::Mon,
            "mny" => Self::Manyika,
            "moh" => Self::Mohawk,
            "mok" => Self::Makonde,
            "mon" => Self::Mongol,
            "mos" => Self::Mossi,
            "mri" => Self::Mari,
            "mrn" => Self::Maronites,
            "mro" => Self::Moro,
            "msk" => Self::Miskito,
            "msl" => Self::Muslim,
            "mtn" => Self::Montenegrins,
            "mtz" => Self::Mestizo,
            "mun" => Self::Munda,
            "muo" => Self::Muong,
            "mus" => Self::Muscogee,
            "mwl" => Self::Mirandese,
            "mwr" => Self::Marwaris,
            "mya" => Self::Mayangnas,
            "mye" => Self::Myene,
            "myn" => Self::Maya,
            "myv" => Self::Mordvins,
            "nag" => Self::Naga,
            "nah" => Self::Nahua,
            "nai" => Self::NativeAmerican,
            "nam" => Self::Nama,
            "nap" => Self::Neapolitan,
            "nau" => Self::Nauruan,
            "nav" => Self::Navajo,
            "nax" => Self::Nakhi,
            "nba" => Self::Nuba,
            "nbl" => Self::SouthNdebele,
            "nca" => Self::Nicaraguan,
            "nde" => Self::NorthernNdebele,
            "ndo" => Self::Ndonga,
            "nep" => Self::Nepali,
            "ner" => Self::Nuer,
            "new" => Self::Newars,
            "ngn" => Self::Ngbandi,
            "ngo" => Self::Ngoni,
            "nia" => Self::Niasans,
            "nib" => Self::Nibolek,
            "nir" => Self::Niari,
            "niu" => Self::Niuean,
            "nkm" => Self::Nkomi,
            "nng" => Self::Nung,
            "nog" => Self::Nogais,
            "nor" => Self::Norwegians,
            "nso" => Self::NorthernSotho,
            "nub" => Self::Nubian,
            "nur" => Self::Nuristani,
            "nuu" => Self::Nu,
            "nya" => Self::Chewa,
            "nyk" => Self::Nyakyusa,
            "nym" => Self::Nyamwezi,
            "nyn" => Self::Ankole,
            "nyo" => Self::Nyoro,
            "nze" => Self::NewZealanders,
            "nzi" => Self::Nzema,
            "oci" => Self::Occitanians,
            "ogo" => Self::Ogoni,
            "oji" => Self::Ojibwe,
            "ojw" => Self::OrthodoxUltraOrthodoxJew,
            "oki" => Self::Okinawan,
            "ori" => Self::Oriya,
            "orm" => Self::Oromo,
            "oru" => Self::Orgunu,
            "osa" => Self::Osage,
            "oss" => Self::Ossetians,
            "oto" => Self::Otomi,
            "ova" => Self::Ovambo,
            "paa" => Self::Papuan,
            "pac" => Self::PacificIslanders,
            "pag" => Self::Pangasinan,
            "pal" => Self::Palestinian,
            "PAL" => Self::Palestinian,
            "pam" => Self::Kapampangan,
            "pan" => Self::Punjabi,
            "pap" => Self::PapiamentoCreole,
            "par" => Self::Paraguayan,
            "pau" => Self::Palauan,
            "per" => Self::Persian,
            "pgn" => Self::AnimistPagan,
            "phu" => Self::Puthai,
            "pnm" => Self::Panamanians,
            "pol" => Self::Poles,
            "pom" => Self::Pomaks,
            "pon" => Self::Pehnpeian,
            "por" => Self::Portuguese,
            "ppl" => Self::Papel,
            "pro" => Self::Protestant,
            "pru" => Self::Peruvian,
            "psh" => Self::Pashayi,
            "pum" => Self::Pumi,
            "pus" => Self::Pashtun,
            "qia" => Self::Qiang,
            "qiz" => Self::Qizilbash,
            "que" => Self::Quechua,
            "raj" => Self::Rajasthani,
            "ran" => Self::PahariRajput,
            "rap" => Self::RapaNui,
            "rar" => Self::CookIslandsMaori,
            "rel" => Self::UnspecifiedReligion,
            "roh" => Self::Romansh,
            "rom" => Self::Romani,
            "rum" => Self::Romanian,
            "run" => Self::Rundi,
            "rup" => Self::Aromanians,
            "rus" => Self::Russian,
            "sad" => Self::Sandawe,
            "sag" => Self::Sango,
            "sah" => Self::Yakuts,
            "sal" => Self::Salish,
            "sar" => Self::Sara,
            "sas" => Self::Sasak,
            "sat" => Self::Sudanese,
            "scn" => Self::Sicilian,
            "sco" => Self::Scottish,
            "sel" => Self::Selkup,
            "sen" => Self::Sena,
            "sfi" => Self::Sufi,
            "sha" => Self::Shafii,
            "she" => Self::She,
            "shi" => Self::Shiites,
            "shl" => Self::Shilluk,
            "shn" => Self::Shan,
            "shy" => Self::Shaigiya,
            "sid" => Self::Sidama,
            "sin" => Self::Sinhalese,
            "sio" => Self::Siouan,
            "sla" => Self::Slavic,
            "slo" => Self::Slovaks,
            "slr" => Self::Salar,
            "slv" => Self::Slovenes,
            "smi" => Self::Sami,
            "smo" => Self::Samoans,
            "sna" => Self::Shona,
            "snd" => Self::Sindhi,
            "snk" => Self::Soninke,
            "som" => Self::Somali,
            "son" => Self::Songhai,
            "sot" => Self::Sotho,
            "spa" => Self::Spanish,
            "srd" => Self::Sardinian,
            "srn" => Self::SrananTongo,
            "srp" => Self::Serbs,
            "srr" => Self::Serer,
            "ssw" => Self::Swazi,
            "sui" => Self::Sui,
            "suk" => Self::Sukama,
            "sun" => Self::Sunni,
            "sus" => Self::Susu,
            "swa" => Self::Swahili,
            "swe" => Self::Swedes,
            "swf" => Self::SwissFrench,
            "swt" => Self::SwissItalian,
            "tab" => Self::Tabasaran,
            "tah" => Self::Tahitian,
            "tai" => Self::Tai,
            "tam" => Self::Tamil,
            "tao" => Self::Taoist,
            "tat" => Self::Tatars,
            "taw" => Self::Tawahka,
            "tay" => Self::Tay,
            "tel" => Self::Telugu,
            "tem" => Self::Temne,
            "ter" => Self::Terenan,
            "tes" => Self::Teso,
            "tet" => Self::Tetum,
            "tgk" => Self::Tajik,
            "tgl" => Self::Tagalog,
            "tha" => Self::Thai,
            "tib" => Self::Tibetan,
            "tig" => Self::Tigre,
            "tir" => Self::TigrayTigrinya,
            "tiv" => Self::Tiv,
            "tkl" => Self::Tokelauan,
            "tli" => Self::Tlingit,
            "tmh" => Self::Tuareg,
            "tms" => Self::Tama,
            "tog" => Self::TongaAfrica,
            "ton" => Self::TongaPacific,
            "tor" => Self::Tooro,
            "tou" => Self::Toubou,
            "tpi" => Self::TokPisin,
            "tra" => Self::Transnistrians,
            "tri" => Self::Tripuri,
            "trn" => Self::Ternate,
            "tsi" => Self::Tsimshian,
            "tsn" => Self::Tswana,
            "tso" => Self::Tsonga,
            "tts" => Self::Tutsi,
            "tuj" => Self::Tujia,
            "tuk" => Self::Turkmen,
            "tum" => Self::Tumbuka,
            "tup" => Self::Tupi,
            "tur" => Self::Turkish,
            "tuu" => Self::Mongour,
            "tvl" => Self::Tuvaluans,
            "twi" => Self::Ashanti,
            "twn" => Self::Taiwanese,
            "tyv" => Self::Tuvans,
            "udm" => Self::Udmurt,
            "uig" => Self::Uyghur,
            "ukr" => Self::Ukranian,
            "umb" => Self::SouthernMbundu,
            "und" => Self::Undetermined,
            "urd" => Self::Urdu,
            "uzb" => Self::Uzbeks,
            "vaa" => Self::Va,
            "vai" => Self::Vai,
            "ven" => Self::Venda,
            "vie" => Self::Vietnamese,
            "vil" => Self::Vili,
            "vnz" => Self::Venezuelan,
            "vot" => Self::Votes,
            "wak" => Self::Wakashan,
            "wal" => Self::Welayta,
            "war" => Self::Waray,
            "was" => Self::Washoe,
            "wel" => Self::Welsch,
            "wen" => Self::Sorbs,
            "whi" => Self::Whites,
            "wln" => Self::Walloons,
            "wol" => Self::Wolof,
            "xal" => Self::Kalmyk,
            "xho" => Self::Xhosa,
            "xib" => Self::Xibe,
            "xnc" => Self::Xinca,
            "yao" => Self::Yao,
            "yap" => Self::Yapese,
            "yor" => Self::Yoruba,
            "ypk" => Self::Yupik,
            "yug" => Self::Yugur,
            "zag" => Self::Zaghawa,
            "zap" => Self::Zapotec,
            "zay" => Self::Zaidiyya,
            "zen" => Self::Zenaga,
            "zha" => Self::Zhuang,
            "znd" => Self::Azande,
            "zom" => Self::Zomi,
            "zor" => Self::Zoroastrians,
            "zul" => Self::Zulu,
            "zun" => Self::Zuni,
            "zza" => Self::Zaza,
            _ => Self::Unspecified,
        }
    }
}
