use crate::components::base_components::raw_types::CAMEOKnownGroupCode;

pub enum KnownGroup {
    Unspecified,
    AlAqsaMartyrsBrigade,
    ArabBankforEconomicDevelopmentinAfrica,
    ArabCooperationCouncil,
    AsianDevelopmentBank,
    ArabEconomicUnityCouncil,
    AfricanDevelopmentBank,
    AlQaeda,
    ArabMonetaryFundforEconomicandSocialDevelopment,
    AmalMilitia,
    AmnestyInternational,
    ArabMaghrebUnion,
    AbuNidalOrganization,
    OrgofArabPetroleumExportingCountriesOAPEC,
    ArabLeague,
    SouthLebanonArmy,
    AssociationofSoutheastAsianNationsASEAN,
    EasternandSouthernAfricanTradeandDevelopmentBank,
    BankofCentralAfricanStatesBEAC,
    BankforInternationalSettlements,
    BaathParty,
    CommonMarketforEasternandSouthernAfrica,
    MonetaryandEconomicCommunityofCentralAfrica,
    FrancZoneFinancialCommunityofAfrica,
    CommonwealthofIndependentStates,
    Communist,
    CouncilofEurope,
    CocoaProducersAlliance,
    AssociationofCoffeeProducingCountries,
    InternationalFedofRedCrossandRedCrescentICRC,
    CommunityofSahelSaharanStatesCENSAD,
    CommonwealthofNations,
    DemocraticFrontfortheLibofPalestineDFLP,
    EuropeanBankforReconstructionandDevelopment,
    EconomicCommunityofCentralAfricanStates,
    EuropeanUnion,
    EuropeanFreeTradeAssociation,
    EnnahdaMovement,
    UnitedNationsFoodandAgricultureOrganization,
    InternationalFederationofHumanRightsFIDH,
    IslamicSalvationArmy,
    NationalLiberationFrontFLN,
    Fatah,
    GulfCooperationCouncil,
    ArmedIslamicGroupGIA,
    GroupofEightG8G7plusRussia,
    GroupofSevenG7,
    SalafistGroup,
    GroupofSeventySevenG77,
    UNHighCommissionforHumanRights,
    UNHighCommissionforRefugees,
    Hezbullah,
    HighlyIndebtedPoorCountriesHIPC,
    Hamas,
    HumanRightsWatch,
    InterAfricanCoffeeOrganizationIACO,
    IntergovernmentalAuthorityonDevelopmentIGAD,
    InternationalAtomicEnergyAgencyIAEA,
    IslamicActionFront,
    InternationalCriminalCourt,
    InternationalCrisisGroup,
    InternationalCourtofJusticeICJ,
    InternationalCocoaOrganizationICCO,
    IslamicDevelopmentBank,
    InternationalGrainsCouncil,
    InternationalHelsinkiFederationforHumanRights,
    InternationalLaborOrganization,
    InternationalMonetaryFundIMF,
    InternationalOrganizationforMigration,
    InterParliamentaryUnion,
    RedCross,
    PalestinianIslamicJihad,
    Interpol,
    InternationalCommissionofJurists,
    KurdishDemocraticPartyKDP,
    UnitedNationsChildrensFundUNICEF,
    IsraeliLaborParty,
    LikudParty,
    MuslimBrotherhood,
    MeretzParty,
    MedecinsSansFrontieresDoctorsWithoutBorders,
    MovementoftheSocietyforPeace,
    NorthAtlanticTreatyOrganizationNATO,
    NewEconomicPartnershipforAfricasDevelopment,
    OrganizationofNonAlignedCountries,
    OrganizationofAmericanStates,
    OrganizationofAfricanUnityOAU,
    OrganizationofIslamicConferencesOIC,
    OrganizationofPetroleumExportingCountriesOPEC,
    PanAfricanParliament,
    PeoplesFrontfortheLiberationofPalestinePFLP,
    PalestineLiberationFront,
    PalestineLiberationOrganization,
    PolisarioGuerillas,
    PeoplesMujahedeen,
    ParisClub,
    OccupiedPalestinianTerritories,
    RedCrescent,
    DemocraticNationalRally,
    SouthAsianAssociation,
    SouthernAfricanDevelopmentCommunity,
    CouncilofSecurityandCooperationinEuropeOSCE,
    ShasParty,
    SoutheastAsiaCollectiveDefenseTreatySEATO,
    Taliban,
    EconomicandMonetaryUnionofWestAfricaUEMOA,
    UnitedNations,
    WestAfricaDevelopmentBank,
    WestAfricaMonetaryandEconomicUnion,
    EconomicCommunityofWestAfricanStatesECOWAS,
    WorldBank,
    InternationalWarCrimesTribunals,
    WorldEconomicForum,
    WorldFoodProgram,
    WorldHealthOrganization,
    WorldTradeOrganization,
    WorldTradeOrganizationWTO,
    Oxfam,
}

impl From<CAMEOKnownGroupCode> for KnownGroup {
    fn from(value: CAMEOKnownGroupCode) -> Self {
        let str_value = std::str::from_utf8(&value.0).expect("Invalid FIPS Code format");
        match str_value {
            "AAM" => Self::AlAqsaMartyrsBrigade,
            "ABD" => Self::ArabBankforEconomicDevelopmentinAfrica,
            "ACC" => Self::ArabCooperationCouncil,
            "ADB" => Self::AsianDevelopmentBank,
            "AEU" => Self::ArabEconomicUnityCouncil,
            "AFB" => Self::AfricanDevelopmentBank,
            "ALQ" => Self::AlQaeda,
            "AMF" => Self::ArabMonetaryFundforEconomicandSocialDevelopment,
            "AML" => Self::AmalMilitia,
            "AMN" => Self::AmnestyInternational,
            "AMU" => Self::ArabMaghrebUnion,
            "ANO" => Self::AbuNidalOrganization,
            "APE" => Self::OrgofArabPetroleumExportingCountriesOAPEC,
            "ARL" => Self::ArabLeague,
            "ASL" => Self::SouthLebanonArmy,
            "ASN" => Self::AssociationofSoutheastAsianNationsASEAN,
            "ATD" => Self::EasternandSouthernAfricanTradeandDevelopmentBank,
            "BCA" => Self::BankofCentralAfricanStatesBEAC,
            "BIS" => Self::BankforInternationalSettlements,
            "BTH" => Self::BaathParty,
            "CEM" => Self::CommonMarketforEasternandSouthernAfrica,
            "CFA" => Self::FrancZoneFinancialCommunityofAfrica,
            "CIS" => Self::CommonwealthofIndependentStates,
            "CMN" => Self::Communist,
            "COE" => Self::CouncilofEurope,
            "CPA" => Self::CocoaProducersAlliance,
            "CPC" => Self::AssociationofCoffeeProducingCountries,
            "CRC" => Self::InternationalFedofRedCrossandRedCrescentICRC,
            "CSS" => Self::CommunityofSahelSaharanStatesCENSAD,
            "CWN" => Self::CommonwealthofNations,
            "DFL" => Self::DemocraticFrontfortheLibofPalestineDFLP,
            "EBR" => Self::EuropeanBankforReconstructionandDevelopment,
            "ECA" => Self::EconomicCommunityofCentralAfricanStates,
            "EEC" => Self::EuropeanUnion,
            "EFT" => Self::EuropeanFreeTradeAssociation,
            "ENN" => Self::EnnahdaMovement,
            "FAO" => Self::UnitedNationsFoodandAgricultureOrganization,
            "FID" => Self::InternationalFederationofHumanRightsFIDH,
            "FIS" => Self::IslamicSalvationArmy,
            "FLN" => Self::NationalLiberationFrontFLN,
            "FTA" => Self::Fatah,
            "GCC" => Self::GulfCooperationCouncil,
            "GIA" => Self::ArmedIslamicGroupGIA,
            "GOE" => Self::GroupofEightG8G7plusRussia,
            "GOS" => Self::GroupofSevenG7,
            "GSP" => Self::SalafistGroup,
            "GSS" => Self::GroupofSeventySevenG77,
            "HCH" => Self::UNHighCommissionforHumanRights,
            "HCR" => Self::UNHighCommissionforRefugees,
            "HEZ" => Self::Hezbullah,
            "HIP" => Self::HighlyIndebtedPoorCountriesHIPC,
            "HMS" => Self::Hamas,
            "HRW" => Self::HumanRightsWatch,
            "IAC" => Self::InterAfricanCoffeeOrganizationIACO,
            "IAD" => Self::IntergovernmentalAuthorityonDevelopmentIGAD,
            "IAE" => Self::InternationalAtomicEnergyAgencyIAEA,
            "IAF" => Self::IslamicActionFront,
            "ICC" => Self::InternationalCriminalCourt,
            "ICG" => Self::InternationalCrisisGroup,
            "ICJ" => Self::InternationalCourtofJusticeICJ,
            "ICO" => Self::InternationalCocoaOrganizationICCO,
            "IDB" => Self::IslamicDevelopmentBank,
            "IGC" => Self::InternationalGrainsCouncil,
            "IHF" => Self::InternationalHelsinkiFederationforHumanRights,
            "ILO" => Self::InternationalLaborOrganization,
            "IMF" => Self::InternationalMonetaryFundIMF,
            "IOM" => Self::InternationalOrganizationforMigration,
            "IPU" => Self::InterParliamentaryUnion,
            "IRC" => Self::RedCross,
            "ISJ" => Self::PalestinianIslamicJihad,
            "ITP" => Self::Interpol,
            "JUR" => Self::InternationalCommissionofJurists,
            "KDP" => Self::KurdishDemocraticPartyKDP,
            "KID" => Self::UnitedNationsChildrensFundUNICEF,
            "LBA" => Self::IsraeliLaborParty,
            "LKD" => Self::LikudParty,
            "MBR" => Self::MuslimBrotherhood,
            "MRZ" => Self::MeretzParty,
            "MSF" => Self::MedecinsSansFrontieresDoctorsWithoutBorders,
            "MSP" => Self::MovementoftheSocietyforPeace,
            "NAT" => Self::NorthAtlanticTreatyOrganizationNATO,
            "NEP" => Self::NewEconomicPartnershipforAfricasDevelopment,
            "NON" => Self::OrganizationofNonAlignedCountries,
            "OAS" => Self::OrganizationofAmericanStates,
            "OAU" => Self::OrganizationofAfricanUnityOAU,
            "OIC" => Self::OrganizationofIslamicConferencesOIC,
            "OPC" => Self::OrganizationofPetroleumExportingCountriesOPEC,
            "PAP" => Self::PanAfricanParliament,
            "PFL" => Self::PeoplesFrontfortheLiberationofPalestinePFLP,
            "PLF" => Self::PalestineLiberationFront,
            "PLO" => Self::PalestineLiberationOrganization,
            "PLS" => Self::PolisarioGuerillas,
            "PMD" => Self::PeoplesMujahedeen,
            "PRC" => Self::ParisClub,
            "PSE" => Self::OccupiedPalestinianTerritories,
            "RCR" => Self::RedCrescent,
            "RND" => Self::DemocraticNationalRally,
            "SAA" => Self::SouthAsianAssociation,
            "SAD" => Self::SouthernAfricanDevelopmentCommunity,
            "SCE" => Self::CouncilofSecurityandCooperationinEuropeOSCE,
            "SHA" => Self::ShasParty,
            "SOT" => Self::SoutheastAsiaCollectiveDefenseTreatySEATO,
            "TAL" => Self::Taliban,
            "UEM" => Self::EconomicandMonetaryUnionofWestAfricaUEMOA,
            "UNO" => Self::UnitedNations,
            "WAD" => Self::WestAfricaDevelopmentBank,
            "WAM" => Self::WestAfricaMonetaryandEconomicUnion,
            "WAS" => Self::EconomicCommunityofWestAfricanStatesECOWAS,
            "WBK" => Self::WorldBank,
            "WCT" => Self::InternationalWarCrimesTribunals,
            "WEF" => Self::WorldEconomicForum,
            "WFP" => Self::WorldFoodProgram,
            "WHO" => Self::WorldHealthOrganization,
            "WTO" => Self::WorldTradeOrganization,
            "WTO" => Self::WorldTradeOrganization,
            "XFM" => Self::Oxfam,
            _ => Self::Unspecified,
        }
    }
}
